### ISSUE TITLE
Product lables were devided on PDF

### ISSUE THREAD

**Issue by aroscha** [foodcoopshop/foodcoopshop#1014]
* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.6.0
* Browser und Betriebssystem / Browser and Operating System: FIREFOX 124.0.1/Linux
* Platform and Target: Selfhosted, Apache at Uberspace
### Was hast du gemacht? What you did?
Created PDF with Product Lables.

### Was ist passiert? What happened? 
PDF with Labels has been created, but with wrong page separation. The last two labels of 6  on one A4 Page were devided on two pages so that the Code and the Product name are not together. See screenshot.

Is it only me who are facing that issue?

### Was sollte passieren? What you expected to happen?
Labels should be complet out of Productname+Barcode.
![Bildschirmfoto vom 2024-03-27 14-00-41](https://github.com/foodcoopshop/foodcoopshop/assets/102872469/23589c6e-0856-4528-afb4-06c50bf2c033)

**Comment by mrothauer** [comment]
can you please share the whole pdf?
does this problem occur on all pdfs? can you narrow it down?
try to change the height of the barcode here
https://github.com/foodcoopshop/foodcoopshop/blob/14ec0bcca0540d86c467feb1182390467e30bff2/plugins/Admin/templates/pdf/product_cards_service.php#L67

**Comment by mrothauer** [comment]
ps: before v4.0
https://github.com/foodcoopshop/foodcoopshop/blob/18a78dd0bfa00f8214522145bc84bf1edc418ca7/plugins/Admin/templates/pdf/product_cards.php#L67
