### ISSUE TITLE
Login-Button auf Startseite "Selbstbedienungsmodus"

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#1016]
Auf der Startseite zur Selbstbedienung sollte zwischen der Überschrift "Anmelden zur Selbstbedienung" und "Kundenkarte scannen..." ein Button angezeigt werden "Selbstbedienung starten".
Klickt man auf diesen soll mit dem im System hinterlegten Selbstbedienungs-Laufkundschaftsbenutzer (Kunde mit Gruppe = SB-Kunde) angemeldet werden.
Hintergrund: aktuell liegt zB bei mir in der Selbstbedienung eine eingeschweißte Karte mit Barcode-Karte des SB-Kunden auf welche zum Starten der Selbstbedienung gescannt werden muss. Obwohl sehr einfach ist das trotzdem für viele eine "Hürde", man kennt es aus den meisten Selbstbedienungsläden eher mit Klickt auf so einen Button daher die Idee.

**Comment by mrothauer** [comment]
duplicate with #1031
