### ISSUE TITLE
Abholtag ändern, letzte Bestelltage nicht.

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#1023]
Das ist eine Frage

* FoodCoopShop Version: 3.4.2

Hallo,
wir wollen den Abholtag von aktuell Samstag auf Donnerstag verschieben.
Wenn ich der Doku von hier folge https://foodcoopshop.github.io/dev/configuration müsste ich dafür zweimal `bin/cake ChangeWeeklyPickupDayByOneDay decrease` ausführen.
"Send Orderlist" nutzen wir nicht und die letzten Bestelltage (Dienstag und Mittwoch) sollen unverändert bleiben. Ich bin mir nicht sicher ob dafür bereits der Befehl von oben reicht oder nicht? Oder ob das überhaupt so funktioniert wie gedacht?
Ich dachte ich frage lieber vorher, als dass ich erst den Shop verhunze ;-)

**Comment by mrothauer** [comment]
> Wenn ich der Doku von hier folge https://foodcoopshop.github.io/dev/configuration müsste ich dafür zweimal bin/cake ChangeWeeklyPickupDayByOneDay decrease ausführen.

Wenn du das Skript zweimal wie beschrieben ausführst, werden auch gleichzeitig die letzten Bestelltage um zwei Tage verschoben. Um das zu verhindern, müsstest manuell in der Tabelle fcs_configuration `FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA` auf 0 setzen (also Mittwoch Mitternacht Hauptbestellschluss). Oder 1 wenn Dienstag der Hauptbestellschluss ist.
