### ISSUE TITLE
Artikel vs. Produkt

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#103]
es soll in der gesamten software nur noch die rede von "Produkten" sein und nicht mehr von "Artikel". Nur noch eine Bezeichnung für die gleiche Sache.

**Comment by gueterwege** [comment]
wärs nicht für die programmiersprache leichter umgekehrt? denn bei artikel gibts nur ein wort in einzahl und mehrzahl. bei produkt mehrere (produkt, produkte, produkten)
für mich klingen beide wörter passend. einheitlich klingt sinnvoll

**Comment by k-pd** [comment]
Einheitlich bezeichnen ja. Einen Grammatik-Vorteil sehe ich hingegen nicht, insbesondere bei Übersetzungen müssen immer Einzahl und Mehrzahl sowie passender Fall angegeben werden. Hier ist es sogar einfacher, wenn aus dem Text selbst erkennbar ist, ob Ein- oder Mehrzahl bzw. in welchem Fall das Wort steht.

Mein Favorit: Produkt. Ist näher an Produzent, näher am Ursprung. Zumindest begrifflich.
