### ISSUE TITLE
Selbstbedienung: Anmeldebutton für Selbstbedienungsbenutzer

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#1031]
Anstelle der aktuellen Lösung das in der Selbstbedienung der Einkauf eines "Selbstbedienungs-Laufkunde" durch Scannen dessen aufliegender Mitgliederkarte gestartet werden kann, soll es einen Anmeldebutton auf der Selbstbedienungsseite geben, welcher sich mit Kundenkonto des Selbstbedienungs-Laufkunden anmeldet.
Hintergrund: einfacher und leichter zu verstehen für die Kunden

Die Möglichkeiten zur Anmeldung anderer Kunden mit Kundenkarte oder Email/Passwort soll weiterhin bestehen bleiben

**Comment by mrothauer** [comment]
* [ ] Bei Einstellungen anzeigen
