### ISSUE TITLE
Selbstbedienung vereinfachen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#1064]
Die beiden Hakerl (AGB / Rücktrittsrecht) sind eine Hürde zu bestellen, soweit klar.

Die Hakerl einfach wegzugeben halte ich nicht für sinnvoll. Erstens rechtlich (da die AGB nicht akzeptiert wurden, aber evtl. ist das vor Ort gar nicht notwendig, gleiches gilt für das Rücktrittsrecht). Zweitens technisch, da ohne Bestätigung Bestellungen getätigt werden können und das Risiko von Fehlbestellungen hoch ist). Geklickt wird viel und schnell.

Vorschlag:
* [ ] Neue Configuration: selfServiceShowConfirmDialogOnSubmit = false (default)
* [ ] Beide Hakerl weggeben und bei Klick auf "Einkauf abschließen" wird ein Confirm-Dialogangezeigt mit folgendem Inhalt "Möchtest du wirklich den Einkauf tätigen und ABG/Rücktrittsrecht akzeptiteren?" Ja Nein bzw. Abbrechen Buttons.

Ob das dann auch rechtlich passt weiß ich nicht - keine Gewähr.

Aber für den User hätte es  große Vorteile.

@pabneukistl So kannst du das gerne umsetzen, die Hakerl einfach wegzugeben würde ich aus besagten Gründen nicht mergen.

**Comment by pabneukistl** [comment]
Hallo Mario! Wurde an der config was geändert? Wollte gerade mit diesem Issue anfangen, aber die Teststeite bleibt bei mir immer grau?
<img width="950" alt="image" src="https://github.com/user-attachments/assets/fdad1b7c-1e86-4d02-802e-e90ec5602ab7">

**Comment by pabneukistl** [comment]
<img width="948" alt="image" src="https://github.com/user-attachments/assets/19fb8275-532f-42b3-b7c6-34cb42ed4b30">

**Comment by pabneukistl** [comment]
Ich hab jetzt mal "blind" was committed, das funktioniert so sicher noch nicht, aber vielleicht kannst mal einen Blick rein werfen ob du dir das so in etwa vorgestellt hättest?

**Comment by mrothauer** [comment]
bitte keine db-basierte config, das brauchts nicht. ist zu aufwändig wegen migrations. bitte in die app_config.php mit entsprechendem default-wert siehe `'selfServiceModeAutoGenerateInvoice' => true,`
kann dann in der custom_config.php überschrieben werden.
graue seite ist meistens js-fehler (dev-tools - console) zum debuggen

**Comment by pabneukistl** [comment]
<img width="820" alt="image" src="https://github.com/user-attachments/assets/9c7444fe-eac7-4019-a412-ee7d4b3b7103">

**Comment by pabneukistl** [comment]
hast du da eine Idee dazu?
Das graue Fenster krieg ich gleich auch im branch develop, sprich auch ohne meine Änderungen.. wurde in die Richtung wo was geändert?

**Comment by pabneukistl** [comment]
<img width="499" alt="image" src="https://github.com/user-attachments/assets/e581201b-e920-496d-8a43-d3377e07870e">

**Comment by pabneukistl** [comment]
beim Öffnen von develop hab ich hier gleich eine Änderung angezeigt?

**Comment by mrothauer** [comment]
siehe tests

Line   templates/SelfService/index.php           
⚠️  Result is incomplete because of severe errors. ⚠️
   Fix these errors first and then re-run PHPStan
   to get all reported errors.

 ------ ------------------------------------------ 
  1[7](https://github.com/foodcoopshop/foodcoopshop/actions/runs/10023360992/job/27704179103#step:11:8)4    Syntax error, unexpected EOF on line 174  
 ------ ------------------------------------------

**Comment by pabneukistl** [comment]
Hallo Mario! Hab den neuen Dialog und Anzeige der Checkboxen je Konfig jetzt mal soweit eingebaut.
Bei Klick auf Einkauf abschließen wird mir der neue Dialog auch kurz angezeigt aber ist gleich wieder weg und Commited, dh. es wird hier nicht auf die Eingabe im Dialog gewartet? Wie/wo kann ich das hier den machen, dass hier auf die Auswahl im neue Dialog gewartet wird?

**Comment by mrothauer** [comment]
habs mir kurz angesehen - das hängt damit zusammen, dass der button ein "normaler" form-submit-button ist (button type="submit")
wenn du da jetzt einen js-click event bindest, macht er trotzdem den submit. du musst das über den default-form-onsubmit handler regeln.
dafür gibts verschiedene lösungen, hier kannst du dich mal einlesen
https://stackoverflow.com/questions/3350247/how-to-prevent-form-from-being-submitted

eine vielleicht einfacherer lösung wäre, den alten button zu verstecken (display: none) und einen eigenen button (dafür zu verwenden (ohne type="submit")

vielleicht gehts auch, nur das type="submit" wegzulassen,  wäre auch eine lösung.

lg,
Mario
