### ISSUE TITLE
Prepare database for MySQL 5.7

### ISSUE THREAD

**Issue by k-pd** [foodcoopshop/foodcoopshop#108]
Running all tests results in the errors shown in [error.txt](https://github.com/foodcoopshop/foodcoopshop/files/1161603/error.txt), mostly coming from more strict default config values in MySQL. There are SQL errors with incomplete ORDER_BY clauses, missing values for insertions (or missing default values in table definition) and incorrect DATETIME formats.

Instead of reconfiguring MySQL to be less strict with these issues, the app should be doing it correctly.

My new computer:
```
$ uname -a
Linux mk 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ apache2ctl -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-05-05T16:32:00
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
```

**Comment by mrothauer** [comment]
as you are using ubuntu trusty (14.04) it may be the same or a similar problem to #106

**Comment by k-pd** [comment]
It's not Ubuntu Trusty, it's Mint 18.1 (based on Ubuntu 17.04). The link mentioned in #106 doesn't do anything to MySQL config files. The app is running smoothly on my machine, until there is something done wrong with the DB (e.g. registering a new user results in SQL error "no value or default for id_gender").

**Comment by mrothauer** [comment]
sorry, just read "14.14", and thought:, the same trusty problem i had to deal with yesterday... trusty has 14.04 i know :-)

the app should definitely do it correctely, some fields need valid default values, the order by errors need to be fixed and customer.gender_id for example could be deleted as it's not used.

on mysql 5.6.33 everything works fine, it might be a 5.7 issue but needs to be done.

**Comment by k-pd** [comment]
Please assign a migration number to this issue (on develop the next is 008.sql). I would open a branch and add default values to all DB columns as a starter.

**Comment by mrothauer** [comment]
008.sql is ok
