### ISSUE TITLE
Travis CI: MySQL 5.7 verwenden

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#116]
seems promising but does not work
https://medium.com/@mtparet/install-mysql-server-5-7-on-travis-96f2ebc0f339
see branch
https://github.com/foodcoopshop/foodcoopshop/tree/feature/issue-116-use-travis-with-mysql-5.7

**Comment by mrothauer** [comment]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by mrothauer** [comment]
@k-pd maybe this is something for you :-)

**Comment by k-pd** [comment]
I don't have time to help with that. Some hints:
- Running MySQL in a Docker-Container requires connecting via network-components, not sockets
- Not sure, if it's possible to load Travis mysql service and then use mysql via network at all. Maybe try mysql-client only?

**Comment by mrothauer** [comment]
thanks for your reply, i'll give it a try

**Comment by mrothauer** [comment]
#144
