### ISSUE TITLE
Serielles Abarbeiten der Migrations

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#122]
ich habe vor kurzem updates für 7 installationen eingespielt, mit den migrations 8 bis 11. das hat bei allen installationen bis auf eine geklappt. bei der einen installation gabs fehler. kann es sein, dass eine migration länger gedauert hat, und die nächste bereits ausgeführt wurde, bevor die vorherige fertig war? es ist unwahrscheinlich (aber nicht ganz auszuschließen, dass die datenbank der einen installation anders war).
danke

**Comment by k-pd** [comment]
Es ist eine foreach-Schleife, also prinzipiell streng seriell. ABER: Es gibt keine Verriegelung gegen mehrfache Aufrufe. Könnte also sein, dass da was schief gelaufen ist. Siehe auch #35 .

**Comment by mrothauer** [comment]
So eine Verriegelung wär super.

**Comment by mrothauer** [comment]
seit cakephp 3 wird das cake plugin "migrations" (ein wrapper für phinx) verwendet, das tool sollte das können.
