### ISSUE TITLE
Untermenüpunkte zentrieren

### ISSUE THREAD

**Issue by veronimus** [foodcoopshop/foodcoopshop#132]
Wenn man auf einer Seite Unterseiten angelegt hat, so erscheinen die grünen Anklickflächen, wenn man mit der Maus drüberfährt. Nur sind die ein bisserl dezentral auf dem weißen Balken, mit dem sie hinterlegt sind, positioniert. Könnte man den Balken kürzen oder zumindest die grünen Felder zentriert darstellen?

**Comment by mrothauer** [comment]
Es geht um das Untermenü am Frontend.

**Comment by mrothauer** [comment]
Nicht so leicht umzusetzen, ein Beispiel: Wenn man z.B. zwei kurze Unterpunkte hat und der Hauptmenüpunkt ganz rechts steht, siehts zentriert auch nicht so toll aus. Man müsste das dann rechtsbündig machen, die gleiche Logik, wenn links ausgerichtet ist (erster Menüpunkt), dann aber eben linksbündig.
![image](https://user-images.githubusercontent.com/527787/39693042-f7d011a8-51e2-11e8-8c04-609653ca8d5c.png)
