### ISSUE TITLE
Is there an api available?

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#137]
I want to write an app for mobile devices.
Is there an api to which can be used?

**Comment by mrothauer** [comment]
Hi confuset. No, there is no api available. There is already a browser based mobile version of the software, what ideas do you have for the app?

**Comment by Confuset** [comment]
sorry was a bit stressed.
my idea was to have some sort of todo/pickup list style app. where everything you ordered is listed and can easily be dismissed by swiping on the screen. Also this feedback would be sent back to the server/website to make it easy to get an overview who already picked up some stuff etc.

is it easy to get this data directly from the database? iam aware of the risks here…

**Comment by k-pd** [comment]
We use a login based on http(s), which could also serve for an API authentication. If You plan to write Your own DB retrieval and API backend, you may provide a [Cake 2.x Plugin](https://book.cakephp.org/2.0/en/plugins/how-to-create-plugins.html) for that. DB details can be found [here](https://github.com/foodcoopshop/foodcoopshop/blob/develop/Config/sql/_installation/clean-db-structure.sql) and [here](https://github.com/foodcoopshop/foodcoopshop/blob/develop/Config/sql/_installation/clean-db-data.sql).

But beware: DB strucure still changes a lot and there is an update planned to use Cake 3.x in near future. So You may find yourself to soon rewrite Your code.

**Comment by mrothauer** [comment]
the basic authentification via https is part of the network plugin
https://github.com/foodcoopshop/fcs-network-plugin

this plugin is currently in development and version 1.0 will be released by the end of this year.

the api controller could be used for your idea
https://github.com/foodcoopshop/fcs-network-plugin/blob/develop/Controller/ApiController.php
