### ISSUE TITLE
Beschreibung mehrerer Produkte auf einmal ändern

### ISSUE THREAD

**Issue by tantelisl** [foodcoopshop/foodcoopshop#139]
Für Sammelbestellung wäre es praktisch wenn ich für mehrere Produkte die Produktebeschreibung aufeinmal ändern könnte (z.B Sammelbestellung bis 9.Oktober, Abholung ab 22.Oktober) da bei allen Produkten gleich.

**Comment by veronimus** [comment]
Genau!

**Comment by mrothauer** [comment]
nicht mehr notwendig - sammelbestellungen sind jetzt einfacher:
https://foodcoopshop.github.io/de/bestellabwicklung
zum testen:
https://demo-de.foodcoopshop.com/
