### ISSUE TITLE
AP07: Änderung des Preises eines bestellten Produktes durch Eingabe des gelieferten Gewichts

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#14]
der preis für nullpreis-artikel kann geändert werden, in dem man den neuen preis einträgt. dies ist fehleranfällig, weil meistens die tatsächliche menge bekannt ist und der daraus resultierende preis selbst berechnet werden muss.

* man soll also die neue menge eintragen können und der preis berechnet sich automatisch
* zur umsetzung braucht man ein neues feld / "preis pro einheit"
* der preis pro einheit soll automatisch bei der langen Beschreibung (Lebensmittelkennzeichnung) aufscheinen
* auch für varianten umsetzen

**Comment by SaibotP** [comment]
Das finde ich auch super! Es sollten aber auch eine Kommastelle möglich sein, weil wir bei Käse oder Fisch z.B. den Preis immer für 100 g Einheiten angeben. Wenn der Käse dann 120 g oder der Fisch 550 g hat, sollte man auch 1,2 oder 5,5 Einheiten angeben können.

Ich glaube nicht, dass es dazu ein neues Feld "Preis pro Einheit" braucht. Bei der Einheit wird wie bisher eingetragen "Stück, 100 g" beim Preis der Preis pro Einheit. Was sich ändern muss, ist die bestellte Menge. Man müsste diese seitens aller Beteiligten (Korrektur durch Herstellers, Shopdienst oder Mitglieder) auch erhöhen bzw. auch mit einer Kommastelle eingeben können. Die Frage ist, ob es eine Checkbox braucht, die diese Anpassung durch alle Beteiligten erlaubt, z.B. Checkbox "Variables Gewicht" oder "Abrechnung per Gewicht". Dann sieht das Mitglied sofort, dass das Gewicht hier variieren kann. Im Shop ist dann die Erhöhung bzw. Anpassung der Menge möglich. Ohne diese Checkbox kann die Menge das Produkts nicht beliebig angepasst werden. Was haltet ihr davon?

Eine weitere Frage, die sich mir stellt, ob die Menge des Produkts wirklich beliebig angepasst werden darf. Sinnvoll wäre eher eine Anpassung mit Bereich von maximal +50%. Ich will ja dann nicht die doppelte Menge Käse oder Fisch. Andererseits erhalte ich ein E-Mail und kann die Bestellung noch immer stornieren oder den Hersteller kontaktieren, wenn es mir zu viel oder zu wenig. Was meint ihr?

Liebe Grüße,

Tobias
