### ISSUE TITLE
Anpassungen für MySQL 5.7

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#144]
Es treten bei Verwendung von MySQL 5.7 noch Fehler auf, z.B.

[PDOException] SQLSTATE[HY000]: General error: 3065 Expression #2 of ORDER BY clause is not in SELECT list, references column 'foodcoopshop.ProductLang.name' which is not in SELECT list; this is incompatible with DISTINCT
Request URL: /admin/products

oder

[PDOException] SQLSTATE[HY000]: General error: 3065 Expression #3 of ORDER BY clause is not in SELECT list, references column 'foodcoopshop.ImageShop.id_image' which is not in SELECT list; this is incompatible with DISTINCT
Request URL: /admin/products

und wahrscheinlich noch einige Fehler mehr...

**Comment by mrothauer** [comment]
Ich konnte den Fehler für das folgende SQL-Statement **nicht** reproduzieren. (db: test-db-structure.sql and test-db-data.sql).

Alle Unit Tests waren OK (13.10.2017).

Server-Typ: Percona Server
Server-Version: 5.7.18-16-log - Percona Server (GPL), Release '16'

SELECT DISTINCT Product.id_product, Product.id_product, Product.active, Product.id_manufacturer, Product.id_tax, `Product`.`id_product` FROM `fcs_product` AS `Product` LEFT JOIN `fcs_manufacturer` AS `Manufacturer` ON (`Product`.`id_manufacturer` = `Manufacturer`.`id_manufacturer`) LEFT JOIN `fcs_product_lang` AS `ProductLang` ON (`Product`.`id_product` = `ProductLang`.`id_product`) LEFT JOIN `fcs_product_shop` AS `ProductShop` ON (`Product`.`id_product` = `ProductShop`.`id_product`) LEFT JOIN `fcs_stock_available` AS `StockAvailable` ON (`Product`.`id_product` = `StockAvailable`.`id_product`) LEFT JOIN `fcs_tax` AS `Tax` ON (`Product`.`id_tax` = `Tax`.`id_tax`) LEFT JOIN `fcs_cake_deposits` AS `CakeDepositProduct` ON (`CakeDepositProduct`.`id_product` = `Product`.`id_product`) LEFT JOIN `fcs_image_shop` AS `ImageShop` ON (`ImageShop`.`id_product` = `Product`.`id_product` AND `ImageShop`.`id_shop` = 1 AND `ImageShop`.`cover` = '1')  WHERE `Product`.`id_manufacturer` = 5   ORDER BY `Product`.`active` DESC, `ProductLang`.`name` ASC, `ImageShop`.`id_image` DESC  LIMIT 100000

Der Fehler trat mit MySQL 5.7.19 auf

Liegt's tatsächlich an 5.7.19 vs. 5.7.18?

Kann den Fehler jemand reproduzieren?

**Comment by k-pd** [comment]
Die [MySQL-Doku](https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_field_in_order_not_select) sagt, das es seit 5.7.5 gemeldet wird. In meiner 5.7.19 ist das auch so. In den Release-Notes für 5.7.19 steht allerdings nix davon drin, das ein Bug oder Feature diesbezüglich behoben bzw. hinzugefügt worden sei. In den Release-Notes für 5.7.5 steht drin, dass diese Meldungen mit dem [ONLY_FULL_GROUP_BY SQL mode](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by) nötig geworden sind, um SQL2003 zu erfüllen.

Warum die 5.7.18 die Meldung nicht ausgibt, könnte also an der Konfiguration liegen. Nach der [Doku](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by) ist das Flag im Standard-Modus an.

**Comment by mrothauer** [comment]
danke für deine antwort. only_full_group_by sql mode war richtig gesetzt... egal, hab jetzt in travis 5.7.20 zum laufen gebracht und bin dabei, die bugs zu beheben. @see https://github.com/foodcoopshop/foodcoopshop/compare/feature/issue-144-anpassungen-fuer-mysql-5.7

**Comment by mrothauer** [comment]
Eine Fehlermeldung, bei der ich auf die schnelle nicht weiterkomme:

ManufacturersControllerTest::testAutomaticAddingOfCustomerRecord

```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC3\xC5\xB8e 4' for column 'address1' at row 1

Oooohhh, es ist ein Fehler aufgetreten.

Stack Trace

APP/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php line 472 → PDOStatement->execute(array)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php line 438 → DboSource->_execute(string, array)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php line 424 → DboSource->execute(string)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php line 1924 → Mysql->update(AddressManufacturer, array, array)
APP/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php line 1758 → Model->_doSave(array, array)
APP/Plugin/Admin/Controller/ManufacturersController.php line 174 → Model->save(array, array)
[internal function] → ManufacturersController->edit(string)
APP/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(ManufacturersController, array)
APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
APP/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(ManufacturersController, CakeRequest)
APP/webroot/index.php line 111 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

**Comment by k-pd** [comment]
Sieht schwer nach Zeichensatz-Fehler aus. Ist evtl. irgendwo ein ISO-8859-15 Zeichen reingerutscht? Oder ein Editor hat beim Laden/Speichern eine Konvertierung versucht?

**Comment by mrothauer** [comment]
Das Problem ist ein ß in der Test-Datenbank:

https://github.com/foodcoopshop/foodcoopshop/blob/7cf61ce33b0de77207f63e06cf53ff339b040835/Test/test_files/Config/sql/test-db-data.sql#L61

Beim Versuch, den Datensatz zu speichern, wird es im Debug-Log so ausgegeben:

`[address1] => Demostra�Ÿe 4`

Das Ändern der Collation auf utf8_unicode_ci scheint nichts zu bringen:
`ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;`

https://github.com/foodcoopshop/foodcoopshop/compare/feature/issue-144-anpassungen-fuer-mysql-5.7

Any hints?

**Comment by k-pd** [comment]
Zeichensatz-Fehler sind definitiv die schwersten Fehler...

Ich habe kurz die geänderten Dateien gecheckt, sind alle einheitlich UTF-8 (auch keine falschen Zeichen eingestreut).

Die Stelle, an der Du das ß ins Log schreibst, verwendet HTTP-Request-Daten zum Schreiben in die DB. Die SQL-Datei mit den Test-Daten ist OK, sicher hast Du geprüft, dass nach dem Import auch alles OK in der DB ist. Das Test-Programm liest die Daten aus der DB und sendet Sie an den Controller. Dabei können an folgenden Stellen Probleme sein:
- $this->browser schickt String falsch codiert raus (sollte UTF-8 sein, könnte aber auch ISO-8859-1 oder so sein)
- $this->browser codiert zwar richtig, schreibt aber falsches in den HTTP-Header
- Der eingebaute Webserver geht bei fehlender Codierungsangabe von falscher Grundeinstellung aus (sehr häufig!)
- Ein Kombi aus obigem

Insbesondere die Webserver-Konfiguration kann hier ein Problem sein, weil normalerweise Browser und Server beim Abrufen des Formulars aushandeln, in welchem Zeichensatz die Daten zurückkommen werden.

**Comment by mrothauer** [comment]
Danke für dein Feedback. Ich denke nicht, dass es am SimpleBrowser oder am Webserver liegt, denn mit MySQL 5.6 läuft ja alles super. Mit MySQL 5.7 kommt es zu dem Fehler.

**Comment by mrothauer** [comment]
.travis.yml
  - mysql -e 'CREATE DATABASE foodcoopshop_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
bringt nichts...

**Comment by mrothauer** [comment]
Update: Bei MySQL 5.6 scheint das auch schon falsch gewesen zu sein, nur hat MySQL 5.6 nicht gemeckert. Ich hab jetzt einfach mal in der Test-Datenbank ß in ss umbenannt, dann laufen die Tests wieder.

Ich gehe mal davon aus, dass es am Simplebrowser liegt, sonst hätte ich wohl schon berichtet bekommen, dass Umlaute falsch oder gar nicht gepeichert werden.

**Comment by mrothauer** [comment]
@k-pd vielleicht könntest du den branch mal auschecken und bei dir lokal testen, ob beim bearbeiten eines herstellers im feld straße ein "ß" korrekt gespeichert wird? danke.

**Comment by k-pd** [comment]
Wollte ich gerade machen, aber siehe Anhang. Der Branch ist issue-144-..., die DB wurde nicht aktualisiert (jedenfalls wurde nichts gemeldet). Gleich beim ersten Aufruf kamen die Meldungen:
* Notice (8): Undefined index: message [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/SessionHelper.php, line 137]
* Notice (8): Undefined index: element [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/SessionHelper.php, line 144]
* Notice (8): Undefined index: element [APP/Vendor/cakephp/cakephp/lib/Cake/View/Helper/SessionHelper.php, line 150]

![bildschirmfoto_2017-10-23_16-33-23](https://user-images.githubusercontent.com/26119310/31895059-7c369f1a-b810-11e7-8324-d1f1bc4f3063.png)

**Comment by k-pd** [comment]
Ich habe gerade wenig Zeit, den Shop neu einzuspielen (der Abgabe-Termin ist schon vorbei...)

**Comment by mrothauer** [comment]
Ich hab nur die Datenbank mit den Daten für die Tests geändert. Da werden keine Migrations ausgeführt. Ich bin mir ziemlich sicher, dass alles richtig eingecheckt ist, sonst würde Travis auf dem Branch auch nicht starten.
Hat alles keine Eile, bis zum nächsten Release (Dezember) sollte die Software auch auf MySQL 5.7 laufen.
