### ISSUE TITLE
Produkt-Verwaltung: Kein Scrollen nach Deaktivieren von Produkt

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#146]
Issue von @EvaSee
* beim Deaktivieren von Produkten nicht in der Ansicht runterspringen in den Bereich der deaktivierten Produkte

**Comment by mrothauer** [comment]
@EvaSee bitte immer nur einen thematischen Punkt pro Issue - ich habs jetzt aufgeteilt. Aber vielen Dank fürs Eintragen!

**Comment by mrothauer** [comment]
soda erledigt und geht in den nächsten online... lg mario

**Comment by EvaSee** [comment]
Super, vielen vielen herzlichen Dank, lieber Mario!

GLG Eva


________________________________
Von: Mario Rothauer <notifications@github.com>
Gesendet: Montag, 07. Mai 2018 10:00
An: foodcoopshop/foodcoopshop
Cc: EvaSee; Mention
Betreff: Re: [foodcoopshop/foodcoopshop] Produkt-Verwaltung: Kein Scrollen nach Deaktivieren von Produkt (#146)


soda erledigt und geht in den nächsten online... lg mario
