### ISSUE TITLE
Bestellstatus für Rechnungen: offen zulassen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#148]
Aufgrund der Einführung der Kommentarfunktion bei Bestellungen kam es beim Fairteiler ab und zu vor, dass bei einigen Bestellungen der Status nicht auf "abgeschlossen" gestellt wurde. Der Abholdienst ließ die Bestellung offen, weil laut Kommentar ja später abgeholt wird, und der Abholende vergisst dann, den Status umzustellen.

Das Problem dabei: Diese offenen Bestellungen werden in den Rechnungen nicht berücksichtigt und der Bauer bekommt das Geld nicht.

Nach dieser Änderung müsste man Bestellungen stornieren (ja, das geht auch :-)), damit sie nicht in den Rechnungen aufscheinen - was ja auch ok wäre.

**Comment by mrothauer** [comment]
Feedbacks verschiedener Foodcoops dazu:

**Güterwege** - OK
Wir verwenden das Bestellung Abschließen nur zur Übersicht wer schon da war. Wobei das wird auch schlampig angewendet. Daher würde es bei unserer Foodcoop keinen Unterschied machen ob die Bestellung abgeschlossen ist oder nicht. Im Gegenteil. Die Funktion Bestellung abgeschlossen verkompliziert bei uns einiges wenn bestellungen im spiel sind die erst eine woche später geliefert werden. Denn dann ist die Bestellung für die aktuelle Woche erledigt, doch der zb. noch offene Käse, noch nicht da. Die Bestellung wird abgeschlossen. Und eine Woche später, wenn der Käse geliefert wird, dann müssen die abgeschlossenen Bestellungen wieder geöffnet werden, damit der preis geändert werden kann. 

**Speis Vorchdorf** - OK
bei uns werden alle Bestellungen am Freitag durch die diensthabenden Mitglieder abgeschlossen.
Die nicht abgeholten Waren werden fertig zusammengestellt und die Mitglieder holen diese
meist am gleichen Abend oder Samstag ab. Dies passiert bei solchen die Freitags einfach länger
arbeiten müssen.
Wir finden dass man mit einer Online-Bestellung diesen Kauf akzeptiert (lt. Bestimmungen).
Daher wird dieser Kauf am Freitag auch abgeschlossen. Für die Abholung ist das Mitglied dann
selbst verantwortlich. Sollte das Mitglied darauf vergessen, so trägt es selbst dafür die
Verantwortung. Dies sollte auf keinen Fall auf Kosten des Herstellers gehen.
Daher trifft bei uns der Fall einer nicht abgeschlossenen Einkaufes nicht zu.
Von uns aus geht eine Abrechnung von nicht abgeschlossenen Bestellungen daher ok.

**Gutes von Dahoam** - OK
Wir schließen alle Bestellungen ab, es bleibt nichts offen.

**Fairteiler Scharnstein** - OK
siehe Kommentar weiter oben

**Comment by gueterwege** [comment]
Hallo, 
nachdem es das Bestellung abschließen schon wieder zum Verhängnis geworden ist, bin ich für abschaffen. dann gehen die preisänderungen unkomplizierter.
