### ISSUE TITLE
Datenexport bzw. WebServices

### ISSUE THREAD

**Issue by MarkusGVD** [foodcoopshop/foodcoopshop#149]
Hallo.

Um den Export von Daten anstelle Copy/Paste durchzuführen wäre ein WebService oder ein anderer Zugriff auf die Datenbank hilfreich.
Desweiteren wäre es auch wünschenswert wenn von Extern z.b. WebServices zum Erstellen einer Bestellung gerufen werden können.
Danke.

lg
Markus

**Comment by mrothauer** [comment]
Hallo Markus,
kannst du bitte ein paar Beispiele nennen, welche Daten exportiert werden sollen und was dann damit gemacht wird?
Und was wäre der Anwendungsfall für das Erstellen einer Bestellung über eine API / WebService?
Lg,
Mario

**Comment by MarkusGVD** [comment]
Hallo.

Beispiele zum Export der Daten:
1) die monatlichen Überweisungen an die Hersteller erfolgen mit der Herstellerliste per Monat. Dzt. ist es nur möglich diese via Copy/Paste ins Excel zur Verarbeitung im Kassabuch oder zur Aufbereitung für die Überweisung zu kopieren. Eine Schnittstelle zum Export dieser Daten welche z.b. übers VB aufgerufen werden kann wäre hilfreich
2) Guthaben Verwaltung: Zur Kontrolle der überwiesenen Guthaben und der in Shop gebuchten Guthaben wäre es ebenfalls hilfreich diese aus dem Shop z.b. ins Excel via Schnittstelle zu übertragen.

Beispiel für das externe Erstellen einer Bestellung:
z.b. Eisbestellung: aufgrund der Vorbereitungszeit muss die Eisbestellung bereits 2 Wochen im vorhinein passieren. Dazu können sich die Mitglieder in eine Cloud Tabelle eintragen. Die wird dann 2 Wochen im vorhinein händisch heruntergeladen und dem Hersteller übermittelt. In der Woche der Auslieferung wird dzt. händisch jeder Eintrag der Tabelle in eine Bestellung im Shop umgewandelt (also händisch eingegeben).
Erneut wäre es praktisch z.b. aus einem Excel via VB eine Schnittstelle zu rufen welche die Bestellungen automatisch anlegt. Würde Zeit sparen.

VIELEN DANK

lg
Markus

**Comment by mrothauer** [comment]
1) Verstanden, dafür wäre eine Export-Funktion wirklich sinnvoll. Es ist aber auch Copy/Paste ganz praktikabel, da beim Einfügen in Excel in einzelne Zellen eingefügt wird und so gut weitergearbeitet werden kann.

2) Dazu gibt's eine praktische Funktion im FoodCoopShop - Superadmins sehen im Admin-Bereich unter "Homepage-Verwaltung" den Menüpunkt "Finanzberichte", das ist genau dafür gedacht. Genaueres hier:
https://foodcoopshop.github.io/de/guthaben-system

3) Das klingt ziemlich kompliziert. Probiert's doch mal mit einer "Sammelbestellung"?  Ich hab das mit Bernd schon mal besprochen.
https://foodcoopshop.github.io/de/sammelbestellungen

Lg,
Mario
