### ISSUE TITLE
Allow more values for app.sendOrderListsWeekday

### ISSUE THREAD

**Issue by christiankaindl** [foodcoopshop/foodcoopshop#151]
Currently `app.sendOrderListsWeekday` only allows for two vaues: `tuesday` and `wednesday`. It would be useful to extend this to also include other weekdays as well.

I currently try to implement this, but for anyone interested that is what I found so far:

It seems all functions that need to be modified live in a file located at `view` > `Helper` > `MyTimeHelper.php`. Inside this file there are a bunch of function. Relevant for us are `getOrderPeriodLastDay()`, `getOrderPeriodFirstDay()`, `getDateForShopOrder()`, which have to be modified in order to support other weekdays as well. (the logic has to be simplified/optimized because right now every day is hardcoded)
 
Thanks for this great software!
Christian Kaindl and Roland Dunzendorfer

**Comment by mrothauer** [comment]
It would be great if you provide unit tests for the new implementation! Good luck and if you need help, please just ask.
Mario
