### ISSUE TITLE
Sofortbestellung auch bei "Bestellte Produkte" anzeigen

### ISSUE THREAD

**Issue by MadPac** [foodcoopshop/foodcoopshop#155]
Es wäre super wenn man auch direkt in der Bestellung eines Mitglieds auf die Sofortbestellung zugreifen könnte und nicht erst in die Bestellnummer zurück muss.

**Comment by mrothauer** [comment]
Hallo,
meinst du mit "in der Bestellung" die Ansicht, in der die bestellten Produkte angezeigt werden? Also die Liste, die man sieht, wenn man unter "Bestellungen" auf "Bestellte Produkte" neben dem Namen klickt?
Lg,
Mario

**Comment by mrothauer** [comment]
Pfand-Rückgabe in dieser Liste ist auch sehr praktisch - mach ich gleich mit.
