### ISSUE TITLE
Eigener Warenkorb für Sofort-Bestellung und normale Bestellung

### ISSUE THREAD

**Issue by Speis-Vorchdorf** [foodcoopshop/foodcoopshop#160]
Es gibt Mitglieder die den Warenkorb ab Mittwoch schon immer laufend befüllen bis alles was gebraucht wird bis Dienstag drin ist...
 
Diese Mitglieder holen aber dann Freitags die Bestellung der Vorwoche ab.
 
Jetzt kommt es ab und an vor, dass sie per Sofortbestellung noch etwas brauchen. Man geht auf Sofortbestellung und dann sieht man aber den bereits befüllten Warenkorb für die folgende Woche.
 
2 Möglichkeiten - das Mitglied nimmt die Ware einfach nicht - oder man muss den Warenkorb vorher löschen. Was aber nicht jeder möchte, weil sie dann wieder alles extra raussuchen müssen.

Gibts da eine andere Möglichkeit irgendwie?

**Comment by mrothauer** [comment]
Man könnte für jedes Mitglied mit zwei Warenkörben arbeiten - einen für Sofort-Bestellungen und einen für normale Bestellungen. Der Programmier-Aufwand dafür wäre überschaubar - das wär vermutlich die beste Lösung. Eine bessere Lösung fällt mir dazu nicht ein.

**Comment by Speis-Vorchdorf** [comment]
Hallo Mario,

 

vielleicht telefonieren wir die Tage mal deswegen.

 

lg

Petra


Gesendet: Mittwoch, 06. Dezember 2017 um 22:54 Uhr
Von: "Mario Rothauer" <notifications@github.com>
An: foodcoopshop/foodcoopshop <foodcoopshop@noreply.github.com>
Cc: Speis-Vorchdorf <speisvorchdorf@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [foodcoopshop/foodcoopshop] Sofortbestellungen bei bereits befülltem Warenkorb (#160)


Man könnte für jedes Mitglied mit zwei Warenkörben arbeiten - einen für Sofort-Bestellungen und einen für normale Bestellungen. Der Programmier-Aufwand dafür wäre überschaubar - das wär vermutlich die beste Lösung. Eine bessere Lösung fällt mir dazu nicht ein.
