### ISSUE TITLE
Discourse SSO API

### ISSUE THREAD

**Issue by paroga** [foodcoopshop/foodcoopshop#164]
Um sich vom FoodCoopShop direkt ins österreichische Foodcoops-Forum ohne erneute Registrierung einloggen zu können ist die Implementierung des [Discourse SSO API](https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045) notwendig.
Um den Erfahrungsaustausch zwischen den einzelnen Foodcoops so einfach wie möglich zu gestalten wäre es wünschenswert wenn sich die Foodcoop-Mitglieder, die bereits im FoodCoopShop angelegt sind, auch gleich im foodcoops.at-Forum einloggen können. Die [Foodsoft](https://github.com/foodcoops/foodsoft/) unterstützt diese Möglichkeit [schon länger](https://github.com/foodcoops/foodsoft/commit/01950b48a18a9e26fcbf27aa8596dcc0724f89cc).
Die eigentliche Implementierung sollte in [5 Zeilen](https://meta.discourse.org/t/discourse-sso-and-api-helper-for-php/51172) machbar sein

**Comment by mrothauer** [comment]
Servus Patrick,

ich hab sehr wenig Zeit gerade, es wäre super, wenn du die Implementierung machen könntest. Ich würde das dann in den Core übernehmen und die Installationen anpassen.

Ich hab dir einen Branch erstellt, an dem du weiterarbeiten kannst (hab dir eine Einladung zum FoodCoopShop-Team geschickt, dann sparen wir uns den Umweg über Forks) und du kannst direkt am Branch arbeiten:

https://github.com/foodcoopshop/foodcoopshop/tree/feature/issue-164-sso-for-discourse

Folgende Configs hab ich schon hinzugefügt, du kannst sie in deiner Implementierung verwenden (der Secret ist natürlich nicht eingecheckt, du müsstest ihn in deiner lokalen custom_config.php einfügen:

Configure::read('app.foodcoopsAtForumUrl');
Configure::read('app.ssoSecret');

Den Installation Guide findest du hier:
https://foodcoopshop.github.io/en/installation-details

Gutes Gelingen und herzlichen Dank!
Mario

PS: Zukünftige Fragen bitte der Transparenz wegen direkt ins Github-Issue. Danke.

**Comment by paroga** [comment]
Ich habe die Konfigurations-Variablen etwas generischer gemacht und an die üblichen Namen angepasst.
Meine Implementierung habe ich in den [Branch](https://github.com/foodcoopshop/foodcoopshop/tree/feature/issue-164-sso-for-discourse) gepusht. Da ich mich jetzt nicht sonderlich in das Framework einlesen wolle, sind noch ein paar unschöne `die()` drinnen, was die Funktionalität aber nicht stören sollte. Ich bin mir auch nicht sicher, ob ich den richtigen User verwende. Das SSO sollte eigentlich nur für _Customer_ erlaubt sein.

BTW: In der [Installationsanleitung](https://foodcoopshop.github.io/en/installation-details) steht nirgends etwas von den Node-Dependencies...

**Comment by mrothauer** [comment]
Hallo Patrick,

vielen Dank für deine Arbeit. Ich hab ein paar Kleinigkeiten angepasst.

Ich hab den Code jetzt mal auf https://demo-en.foodcoopshop.com deployed.
discourseSsoSecret: 51gqJ5rfxivML5bYEFbO (ändere ich nach dem Testen wieder)
discourseUrl: https://forum.foodcoops.at

Zugangsdaten sind
fcs-demo-member@mailinator.com / pw: foodcoopshop

$discourse_url = Configure::read('app.discourseUrl');
Die Variable wird nicht verwendet. Ist das Absicht?

Lg,
Mario

PS: Die Installationsanleitung hab ich angepasst, in der readme.md wär's gestanden. Danke

**Comment by mrothauer** [comment]
Da fällt mir noch was ein:
Falls nicht extra mittels if ($this->AppAuth->isManufacturer()) ausgenommen, würde sich auch Hersteller ins Forum einloggen können. Ob ihr als IG Foodcoops das wollt, müsst ihr entscheiden. Ich persönlich fände es sogar gut, wenn sich die Hersteller einloggen könnten, weil Foodcoops nun mal Produzenten-Konsumenten-Gemeinschaften sind.

**Comment by paroga** [comment]
Danke fürs anpassen. Was noch cool wäre, wenn statt dem `die('No User')` ein Redirect über da Login-Prompt kommen würde. Ich hätte jetzt nicht viel Nutzen für die Hersteller gesehen, aber sehe aktuell auch keinen ernsthaften Grund es zu verbieten. Bist du sicher das das `discourseSsoSecret` stimmt? Irgendetwas funktioniert noch nicht ganz (bin gerade beim genauer Herausfinden)...

**Comment by paroga** [comment]
nein geht eh, war ein config fehler bei mir 😉
ad `discourseUrl`) im Normalfall wird es als Fallback genutzt wenn die `return_sso_url` nicht gesetzt ist. da das aber nur bei recht alten Discourse Versionen der Fall ist, ist es mittlerweile eigentlich unnötig. Die verwendetet Library wirf eine Exception, wenn sie nicht gesetzt ist, wodurch der Fallback nur bedingt Sinn macht. K.A. ob das Rauswerfen oder eine `try` `catch` ums `getSsoReturnUrl()` schöner ist.

**Comment by mrothauer** [comment]
* super wenns funktioniert!
* discourseUrl: wenns nicht benötigt wird, würd ich's rausgeben. such dir was aus :-)
* ich würd dann im nächsten schritt mal den fairteiler scharnstein umstellen und dir per mail den secret schicken. kannst du dazu den fairteiler in der liste der foodcoops nach "via foodcoop anmelden" ergänzen bitte?

**Comment by mrothauer** [comment]
und vielleicht fällt dir ja noch ein, wie man das ganze testen könnte. (falls die dependency mal upgedatet wird oder ähnliches). weil wenns nach einer zeit "auf einmal" nicht mehr geht, ist's halt nervig.

**Comment by paroga** [comment]
ja, dann wirf es raus.
ich schicke dir das ssoSecret für den Fairteiler als PM. Freue mich schon den ersten FCS in die Liste aufnehemen zu können und hoffe auf viele weitere 😄

**Comment by paroga** [comment]
ich habe extra eine dependency mit ordentlicher testabdeckung ausgesucht. für einen 100% E2E test müsste das discourse-login-verfahren im test nachgebaut werden, weiß aber nicht ob es sinn macht die test aus der dependency zu duplizieren...

**Comment by mrothauer** [comment]
ok alles klar, super.
bitte NOCHMAL auf demo-en testen, ich hab den neuen code grad nochmal deployed.
neue config discourseSsoEnabled um sso generell zu aktivieren / deaktivieren.
sobald ich den ssoSecret von dir hab, stell ich den fairteiler um.

**Comment by mrothauer** [comment]
und vielleicht kannst du noch die vorgehensweise beschreiben, wie foodcoops, die ich nicht hoste, den sso verwenden können? mit wem muss kontakt aufgenommen werden usw.
danke
https://foodcoopshop.github.io/de/
https://github.com/foodcoopshop/foodcoopshop.github.io

**Comment by paroga** [comment]
Könntest du noch eine Anmeldung über `/anmelden` erzwingen, wenn `/discourse/sso` ohne eingeloggtem User geöffnet wird oder mir kurz einen Tip geben, wie ich das Einbauen kann. Ohne das Login-Prompt ist die Usability sehr fragwürdig. 😢

**Comment by paroga** [comment]
Ich denke das ein kleines Formular auf der Homepage wo das erzeugte SSO-Secret eingeben werden kann, wohl die einfachste Lösung sein wir, oder? Verschlüsselte Mails sind wohl zu umständlich. 😉 Wenn du das auch so siehst, würde ich dir dann den Link zukommen lassen, sobald ich es aufgesetzt habe.

**Comment by paroga** [comment]
das login-forum ist zwar etwas groß, aber sonst funktioniert alles. COOL!

**Comment by mrothauer** [comment]
das layout kann ich noch anpassen. ich deploy jetzt mal den fairteiler.
