### ISSUE TITLE
Kategorie-Filter für Produkte im Admin-Bereich

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#166]
Filter wären praktisch, z.B. nach

* Stückzahl (geringer Lagerstand)
* fehlende Preise
* Kategorien

**Comment by mrothauer** [comment]
@SaibotP 
* Stückzahl und Preise können mit der Sortierung eingegrenzt werden
* Filter nach Kategorie ist implementiert (Einfach-Filter, Mehrfach-Filter wär ein ziemlich großer Aufwand). Ich hoffe, das reicht fürs Erste.

Zum Testen auf demo.foodcoopshop.com

**Comment by mrothauer** [comment]
#188 muss noch umgesetzt werden

**Comment by SaibotP** [comment]
Hallo Mario, das Filtern nach Kategorien ist super (Einfach-Filter ist völlig ausreichend). Ist noch ein einfaches Sortieren nach Kategorien umsetzbar? LG Tobias

**Comment by mrothauer** [comment]
Mit Cake3 waren Mehrfach-Filter kein Problem, ist schon umgesetzt... Sortieren ist da schon schwieriger, ich würde das auch so lassen, wie es ist. Lg Mario
