### ISSUE TITLE
deactivate forgot password function for deactivated users

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#17]
currently it is possible for deactivated users to retrieve a new password. they get it via email, but then they can't log in because they are deactivated.

url: www.example.com/neues-passwort-anfordern

**task**
1) change flash message if email address of user (table fcs_customer) is in database but active is set to 0 to
"Dein Mitgliedskonto ist nicht mehr aktiv. Falls du es wieder aktivieren möchtest, schreib uns bitte eine E-Mail."

2) and do not send the email with the new password!

**Comment by k-pd** [comment]
Ich kann nicht unterscheiden zwischen "noch nicht aktiviert nach der
Registrierung" und "wurde deaktiviert". Beides steckt in dem einen Flag.

Dann ist in der DB auch noch 'deleted'. Wird das genutzt?

Soll es setFlashMessage() oder setFlashError() sein? Error passt mMn
besser.
Am 01.03.2017 um 19:34 schrieb Mario Rothauer:

**Comment by mrothauer** [comment]
einfach das flag 'active' abfragen, wenn 0 dann "nicht aktiv". aber du hast recht, da stecken zwei zustände drin.
deleted wird noch gar nicht genutzt, man kann mitglieder momentan noch gar nicht löschen.
und setFlashError() ist ok.
