### ISSUE TITLE
Weitere E-Mail-Adressen zu Mitgliedskonto eintragen

### ISSUE THREAD

**Issue by FloorWolff** [foodcoopshop/foodcoopshop#174]
Liebe Foodcoopshop-Gemeinschaft,
Wie hilfreich wäre es, eine zweite (oder noch mehr) Emailadresse angeben zu können, an die dann die System-Emails in Kopie geschickt werden? Für Haushälte mit mehreren aktiven Mitgliedern ist es öfters angenehm zu sehen, was der/die andere/n schon bestellt haben, wenn Änderungen vorgenommen wurden usw. Welche andere Wege gibt es, die nicht unbedingt von der Software abhängig sind? Emailfilter einrichten? Kann man das allen Mitgliedern zumuten? Funktioniert das gut? Welche Vor- und Nachteile ergeben sich daraus? Wie schwierig ist es, das in die Software einzubetten?
Wird das in anderen Foodcoops auch von manchen Mitgliedern verlangt?
THANKS for Inputs!
LG Floor

**Comment by mrothauer** [comment]
Im Profil ein neues Feld "Kopie aller automatischen E-Mails an:" einzubinden ist ein überschaubarer Aufwand. Reicht das für die Anforderungen? Ist es wirklich notwendig? Weil man kann sich ja auch einloggen und z. B. die Bestellungen, Stornierungen usw. in der Software direkt.

**Comment by SigiK** [comment]
Hallo, 
auch ich finde diese Funktion nicht wirklich notwendig, aber seis drum. Ich hätte den Text des Feldes genannt: "Weiterleitung an (E-Mails)" ein neues nullable feld in der Datenbank wie E-Mail als varchar(255) angelegt. Werden mehrere E-Mailadressen benötigt oder nur eine? Emails könnten Komma, Strichpunkt oder Space separiert werden.

Beispiel
![emailweiterleitung](https://user-images.githubusercontent.com/9429172/54418042-0c1a4400-4704-11e9-9548-2a32944de55b.png)

Lg Sigi

**Comment by mrothauer** [comment]
Die Funktion ist super sinnvoll, damit mehrere Familienmitglieder ein Konto verwenden können.

1) Bitte mit Komma trennen, da gibt's auch schon einen Validator (see https://github.com/foodcoopshop/foodcoopshop/blob/b38c5da7d6ddb8c7522a2ba98d1d88705553c364/src/Model/Table/ManufacturersTable.php#L69)

2) Mit `bin/cake migrations create AddEmailCCForMembers` (oder einem anderen Namen) kannst du eine neue Migration erstellen, die das notwendige SQL beinhaltet. `bin/cake migrations migrate` führt die Migration dann aus.

3) Tests: Bevor du oder ich Tests schreiben, erstelle bitte einen Pull-Request. Ich muss die Migration noch in die Dumps für die Tests mergen, das ist (noch) ein bissl kompliziert.

**Comment by SigiK** [comment]
Hi,
sorry, dass ich solange auf mich warten lassen habe, hatte wenig Zeit und dann Urlaub. Habe jetzt mal einen Branch erstellt mit meinen Änderungen und weiß jetzt nicht wie ich (über Netbeans) den Pull-Request erstellen kann?! Ebenso habe ich keine Ahnung wie ich da Tests erstelle... wie gesagt bin ich neu mit Git und PHP und deshalb etwas ratlos. 
Getestet habe ich das ganze aber schon mit XDebug. Sollen die binären Locale-Dateien wie mo usw. auch commited werden? Ich hab sie jetzt mal reingetan.

Vielen Dank und Lg Sigi

**Comment by mrothauer** [comment]
Hallo Sigi,
um den PR zu erstellen, musst du deinen Branch erst mal pushen. Dann kannst du auf Github direkt den Pull-Request erstellen.
Arbeitest du auf einem Fork? Weil wenn du auf dem Haupt-Repo arbeitest (foodcoopshop/foodcoopshop), dann musst du meine Einladung zum Team annehmen, sonst hast du keinen Push-Access.
Lg,
Mario

**Comment by SigiK** [comment]
Hallo Mario,
ich arbeite auf keinem Fork, sollte ich das sicherheitshalber tun? Kann ich jetzt den Branch pushen, oder sollte ich irgendwelche Sicherheitsvorkehrungen treffen? Notfalls können wir das ganze eh wieder reseten oder? Ich arbeite auf einem branch von develop/develop auf repository foodcoopshop/foodcoopshop.

```
[core]
	symlinks = false
	repositoryformatversion = 0
	filemode = false
	logallrefupdates = true
	bare = false
[remote "develop"]
	url = https://SigiK@github.com/foodcoopshop/foodcoopshop.git
	fetch = +refs/heads/*:refs/remotes/develop/*
[branch "develop"]
	remote = develop
	merge = refs/heads/develop
[pack]
	buildbitmaps = false
[branch "feature/issue-174-additional-email-addresses"]
	remote = develop
	merge = refs/heads/develop
```

**Comment by mrothauer** [comment]
servus sigi,
du kannst den branch gerne pushen. jetzt gehts, weil du push-rechte für neue branches hast.

**Comment by SigiK** [comment]
Ok ich hab es mal gepushed und einen Pull Request erstellt. Bin gerne für Änderungen offen! 
Hoffe das passt so vom Workflow, wenn ich das jetzt über den Branch pushe!?
Ich kann das ganze gerne auch systemweit (wohin mit der function getForwardingMails?) realisieren.

**Comment by mrothauer** [comment]
danke für den PR. bitte ab jetzt direkt im PR weiterschreiben.
see #353
