### ISSUE TITLE
Hersteller: Gruppierung nach "Bestellte Produkte" + Datumsfilter

### ISSUE THREAD

**Issue by EvaSee** [foodcoopshop/foodcoopshop#175]
Aus ProduzentInnen-Sicht erscheint mir die Detailübersicht nach Produkt bzw. Produktkategorien interessanter als nach Mitgliedern. 
Zumindest aus unserer (DAXanBau) Sicht interessieren mich Details zu wie sich der Rechnungsbetrag nach Kategorien (Jungpflanzen, Gemüse) oder einzelnen Produkten (Gemüsesorten) aufteilt mehr. 

Aber vielleicht gibt es gute Gründe für die Mitgliederauflistung, die ich noch nicht durchschaut hab??

Viele liebe Grüße, eva

**Comment by EvaSee** [comment]
Bzw. am allereinfachsten kommt mir grad vor, wäre es, wenn ich im Foodcoopshop selbst die bestellten Jahresmengen nach Kategorien filtern könnte - zB bzgl. Überlegung wieviele Jungpflanzen haben wir über die eine oder die andere Foodcoop verkauft?

**Comment by EvaSee** [comment]
Aktuell lese ich die unterschiedlichen Kategorien aus den Rechnungen raus (da ich mir keine Aufzeichnungen während des Jahres gemacht hab - eh selber schuld ;) bzw. eben auch durchführbar...

**Comment by mrothauer** [comment]
Hallo Eva,

wenn ich dich richtig verstehe, gehts's überhaupt nicht um die Rechnungen. Vielmehr wollt ihr wissen, wie viele Produkte in einem bestimmten Zeitraum verkauft wurden.  Einen Kategorie-Filter einzubauen, ist schon wieder etwas komplizierter, drum folgender Vorschlag:

Den Hersteller-Bereich unter "Bestellte Produkte" erweitern:

* Filter nach Zeitraum (von, bis Datum)
* nach Produkt gruppieren (damit alle verkauften Produkte schön übersichtlich mit Summe von Anzahl und Preis angezeigt werden)

Würdet das euer Problem lösen?
Lg,
Mario

**Comment by EvaSee** [comment]
Hallo Mario,

ja, stimmt!

Ich hab einfach in den Rechnungen nachgesehen, daher meine erste Anfrage bzgl. Rechnung, aber du hast vollkommen recht - es geht eigentlich nicht wirklich um die Rechnungen - dein Vorschlag, die Filtermöglichkeit beim Herstellerbereich Bestellte Produkte zu erweitern, klingt sehr gut. Meiner Meinung nach braucht es aber nur eine Filtermöglichkeit nach Produktkategorie, nicht einzelnen Produkten sein ...  falls es aber nur uns als Gemüsebetrieb mit mehreren Kategorien betrifft, ist es vielleicht gar nicht so wichtig....


Danke und liebe Grüße,

eva


________________________________
Von: Mario Rothauer <notifications@github.com>
Gesendet: Freitag, 08. Dezember 2017 10:56
An: foodcoopshop/foodcoopshop
Cc: EvaSee; Author
Betreff: Re: [foodcoopshop/foodcoopshop] Rechnung: Details nach Kategorien bzw. Produkten (#175)


Hallo Eva,

wenn ich dich richtig verstehe, gehts's überhaupt nicht um die Rechnungen. Vielmehr wollt ihr wissen, wie viele Produkte in einem bestimmten Zeitraum verkauft wurden. Einen Kategorie-Filter einzubauen, ist schon wieder etwas komplizierter, drum folgender Vorschlag:

Den Hersteller-Bereich unter "Bestellte Produkte" erweitern:

  *   Filter nach Zeitraum (von, bis Datum)
  *   nach Produkt gruppieren (damit alle verkauften Produkte schön übersichtlich mit Summe von Anzahl und Preis angezeigt werden)

Würdet das euer Problem lösen?
Lg,
Mario

**Comment by mrothauer** [comment]
Hallo Eva,

ich hab das jetzt umgesetzt und es ist beim Fairteiler zum Testen bereit. Als Hersteller (und als Admin auch) kann man jetzt die bestellten Produkte "nach Produkt gruppieren" - allerdings vorerst ohne Varianten. Wenn man Details haben möchte, bitte einfach auf das Produkt klicken, dann sieht man auch, welche Varianten verkauft wurden. 

Es bietet aber eine tolle Übersicht über die verkauften Produkte, das hat bisher echt gefehlt. Hier ein Beispiel für eure verkauften Produkte im November:
https://www.fairteiler-scharnstein.at/admin/order_details/index/dateFrom:01.11.2017/dateTo:30.11.2017/productId:/orderState:3,1,2/groupBy:product

Achtung: Beim Bestell-Status muss "abgeschlossen" und "offen" angehakt sein.

Könnt ihr damit arbeiten? Ich freu mich auf Feedback,
Mario

**Comment by mrothauer** [comment]
Du kannst die Liste jetzt auch sortieren (Klick auf die Überschrift auf die Tabelle). Hier z.B. eine Jahresübersicht, sortiert nach Betrag.
https://www.fairteiler-scharnstein.at/admin/order_details/index/dateFrom:01.01.2017/dateTo:30.11.2017/orderState:3,1,2/groupBy:product/sort:OrderDetail.total_price_tax_incl/direction:desc

**Comment by EvaSee** [comment]
Wow, vielen herzlichen Dank, Mario!!


________________________________
Von: Mario Rothauer <notifications@github.com>
Gesendet: Freitag, 15. Dezember 2017 10:16
An: foodcoopshop/foodcoopshop
Cc: EvaSee; Author
Betreff: Re: [foodcoopshop/foodcoopshop] Hersteller: Gruppierung nach "Bestellte Produkte" + Datumsfilter (#175)


Du kannst die Liste jetzt auch sortieren (Klick auf die Überschrift auf die Tabelle). Hier z.B. eine Jahresübersicht, sortiert nach Betrag.
https://www.fairteiler-scharnstein.at/admin/order_details/index/dateFrom:01.01.2017/dateTo:30.11.2017/orderState:3,1,2/groupBy:product/sort:OrderDetail.total_price_tax_incl/direction:desc

**Comment by mrothauer** [comment]
Bitte gerne. Schönes Auswerten :-)
