### ISSUE TITLE
How to update an exsisting install?

### ISSUE THREAD

**Issue by christiankaindl** [foodcoopshop/foodcoopshop#176]
I have a FoodCoopShop install with lots of products already in it and I wondered: "How do I update FoodCoopShop?" I haven't found anything in the documentation, so I thought I just ask :)

**Comment by mrothauer** [comment]
Hi Christian,
please check out the migration guide (i just updated it a bit):
https://foodcoopshop.github.io/en/migration-guide
If you found a mistake or if you want to update the guide, you are welcome to provide a pull request.
Good luck!
Mario
