### ISSUE TITLE
Change .dev host to .localhost

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#177]
.dev hosts are always redirected to https in google chrome 63 (december 2017) => change .dev to .localhost

https://tech.slashdot.org/story/17/09/18/192227/chrome-to-force-domains-ending-with-dev-and-foo-to-https-via-preloaded-hsts

**Comment by k-pd** [comment]
I hope you came across this: https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/#comment-51453

".localhost" is no SAFE alternative. Use ".test" instead, as it is intended for such use since 1999.

**Comment by k-pd** [comment]
Check: https://en.wikipedia.org/wiki/.test

**Comment by mrothauer** [comment]
thank you for the information, i changed it
https://github.com/foodcoopshop/foodcoopshop/commit/43887b018d1e1e7352c94344090d273842dabae9
