### ISSUE TITLE
Pfandrückgabe auch beim Mitglied direkt möglich?

### ISSUE THREAD

**Issue by Speis-Vorchdorf** [foodcoopshop/foodcoopshop#182]
Es kommt vor dass Mitglieder Freitags leere Pfandflaschen zurückbringen ohne aber 
eine Bestellung getätigt zu haben. Jetzt gibts keine Möglichkeit den Pfand gutzuschreiben
(außer das Mitglied nimmt zufällig etwas mit "per Sofortbestellung")

Gäbe es eine Möglichkeit das Pfand auch direkt beim Mitglied gutzuschreiben?

lg Petra

**Comment by mrothauer** [comment]
Bitte sucht euch dafür einfach eine alte Bestellung des Mitglieds raus. Am einfachsten geht das über "Mitglieder" und dann auf das Mitglied klicken. Dann werden alle Bestellungen des Mitglieds angezeigt und ihr könnt den Pfand eintragen.
Lg,
Mario

**Comment by Speis-Vorchdorf** [comment]
Ahjaaaa danke. Erledigt. Hab geglaubt dass das Öffnen von alten abgeschlossenen Bestellungen ev. wieder negative Auswirkungen hätte.....


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Mario Rothauer <notifications@github.com> Datum: 15.12.17  18:56  (GMT+01:00) An: foodcoopshop/foodcoopshop <foodcoopshop@noreply.github.com> Cc: Speis-Vorchdorf <speisvorchdorf@gmx.at>, Author <author@noreply.github.com> Betreff: Re: [foodcoopshop/foodcoopshop] Pfandrückgabe auch beim Mitglied direkt möglich? (#182) 
Bitte sucht euch dafür einfach eine alte Bestellung des Mitglieds raus. Am einfachsten geht das über "Mitglieder" und dann auf das Mitglied klicken. Dann werden alle Bestellungen des Mitglieds angezeigt und ihr könnt den Pfand eintragen.

Lg,

Mario

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/foodcoopshop/foodcoopshop","title":"foodcoopshop/foodcoopshop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/foodcoopshop/foodcoopshop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrothauer in #182: Bitte sucht euch dafür einfach eine alte Bestellung des Mitglieds raus. Am einfachsten geht das über \"Mitglieder\" und dann auf das Mitglied klicken. Dann werden alle Bestellungen des Mitglieds angezeigt und ihr könnt den Pfand eintragen.\r\nLg,\r\nMario"}],"action":{"name":"View Issue","url":"https://github.com/foodcoopshop/foodcoopshop/issues/182#issuecomment-352070707"}}}

**Comment by mrothauer** [comment]
Die Bestellung muss dazu gar nicht geöffnet werden.
Lg
Mario

**Comment by Speis-Vorchdorf** [comment]
hab jetzt extra nochmal den Compi eingeschaltet und habs gefunden -

mach nämlich sehr viel am Handy und da sieht man das Feld

"Pfand-Rückgabe" nicht. Hab scho glaubt i bin blind... :-)

 



Gesendet: Freitag, 15. Dezember 2017 um 20:53 Uhr
Von: "Mario Rothauer" <notifications@github.com>
An: foodcoopshop/foodcoopshop <foodcoopshop@noreply.github.com>
Cc: Speis-Vorchdorf <speisvorchdorf@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [foodcoopshop/foodcoopshop] Pfandrückgabe auch beim Mitglied direkt möglich? (#182)


Die Bestellung muss dazu gar nicht geöffnet werden.
Lg
Mario

**Comment by mrothauer** [comment]
Auf der mobilen Version steht der Text "Pfand-Rückgabe" aus Platzgründen nicht dabei. Das €-Zeichen sieht man aber trotzdem und der Button funktioniert.
Lg,
Mario
