### ISSUE TITLE
Mitglieder und Hersteller: Export als CSV

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#186]
Es wäre sehr sinnvoll, wenn man eine Excel-Tabelle bzw. CSV-Datei der Mitglieder und Hersteller exportieren könnte (mit möglichst allen Parametern). Ein Verein benötigt oft eine solche Tabelle (als Liste seiner Mitglieder für die Buchhaltung, Kontroll-Zwecke z.B. Einzahlungen und Mitgliedsbeiträge etc.). Derzeit muss der Verein so eine Excel-Tabelle manuell warten (doppelter Aufwand, ständig manuell ergänzen und aktualisieren).

Export-Button soll neben dem Druck-Symbol angezeigt werden.

Issue wurde für @SaibotP eingetragen.

**Comment by SaibotP** [comment]
Hallo Mario, hast du dieses Feature aus der Roadmap und Q1/2018 entfernt, weil es schon umgesetzt wurde oder weil es (vorerst) nicht kommen wird?

**Comment by mrothauer** [comment]
Siehe meine E-Mail vom 8. Februar... Ich würde das Feature gern ganz weglassen, weil ich schon weit über der veranschlagten Zeit bin. das war damals eh nur ein Nice-to-have soweit ich mich erinnere. Ok?

**Comment by AndreasEgger** [comment]
Hi Mario, auch für uns wäre das eine schöne Erleichterung. Eine alternative Möglichkeit wäre vielleicht einen lesenden Zugriff auf die DB zu geben und ein kleines Query-Tool zu bauen so deass man sich selbst immer rauszieht was man gerade braucht.

**Comment by mrothauer** [comment]
same as #321
