### ISSUE TITLE
Hersteller: Sortieren und Filtern nach offenen Bestellungen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#187]
Admin-Bereich / Hersteller:  Summe in € der OFFENEN Bestellungen in Spalte anzeigen (Zeitraum beachten!) Zum Überprüfen, ob ein Hersteller in einem Zeitraum offene Bestellungen hat.

Issue wurde für @SaibotP eingetragen.

**Comment by mrothauer** [comment]
@SaibotP auf demo.foodcoopshop.com zum Testen

**Comment by SaibotP** [comment]
Hallo Mario, Danke für dieses Feature. Statt "O.B" wäre wohl "offen" oder "offene B," besser. Leider kann man nach dieser Spalte noch nicht sortieren oder filtern ("Offene Bestellungen"). Ist das noch einfach umsetzbar? Danke und Liebe Grüße, Tobias

**Comment by mrothauer** [comment]
offene B. macht die Spalte unnötig breit, beim Mouseover steht da, was die Spalte macht. Sortieren ist leider nicht einfach umsetzbar, da das Sortieren nur dann einfach umsetzbar ist, wenn man nach einem Spaltennamen, der aus der Datenbank kommt, sortiert (z.B. Name). Berechnete Felder sind schwieriger zur sortieren. Dh. vorerst würde ich das lassen wie es ist. Lg, Mario
