### ISSUE TITLE
Filtern von Produkten in Admin-Bereich verbessern

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#188]
Die Felder Anzahl und Preis sollen auf den Wert 0 gefiltert werden können.

Dieses Issue wurde für @SaibotP erstellt.

**Comment by mrothauer** [comment]
@SaibotP auf demo.foodcoopshop.com zum Testen
lg,
Mario

**Comment by SaibotP** [comment]
Hallo Mario, habe dieses Feature getestet. "Preis 0" ist super. "Anzahl 0" ist nicht ganz das, was wir wollten. Wir wolten die Liste der Produkte nach Anzahl sortieren können, um zu sehen, welche Produkte bald aus sind (also 0 oder 1, 2, 3, 4...). Ist es noch einfach umsetzbar, nach dieser Spalte zu (aufsteigend) zu sortieren?

**Comment by mrothauer** [comment]
Das Sortieren einer Spalte, die auch von Varianten verwendet wird, ist schwierig zu lösen.

Ich könnte anbieten, dass Mengen zwischen 1 und 5 immer in einem helleren Rot angezeigt werden, als 0. Dann fällts in der Liste auch auf. Und die Checkbox ändere ich zusätzlich auf "Anzahl < 6"). Ok so?
