### ISSUE TITLE
Checkbox "Produkt-Deklaration ok" einfügen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#196]
Am besten in den Bearbeiten-Bereich des Produktes.
Issue erstellt für @SaibotP

**Comment by mrothauer** [comment]
@SaibotP ist jetzt auf demo.foodcoopshop.com eingebunden und kann dort getestet werden

**Comment by SaibotP** [comment]
Hallo Mario, ist das die Checkbox für die Kennzeichnung laut Lebensmittelinformationsverordnung?
Und kann man da jetzt schon ein zweites Foto mit dem Etikett ergänzen?

**Comment by mrothauer** [comment]
Ja, das ist schon lang erledigt. Man kann in die lange Beschreibung nun Bilder hochladen.
