### ISSUE TITLE
create database migrations

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#20]
https://phinx.org/ seems to be a good migration tool

integration should require the database credentials from cake's database.php

for updating from older versions, migrations should ideally be triggered by accessing a url (for users who host their fcs-installation and are not familiar with the console)
this url should be protected for superadmins.  eg /admin/configurations/updateDatabase (ConfigurationsController is only allowed for superadmins)

currently we have manual "migration tool" :-) (Config/sql/migrations/v.x.x.x)

**Comment by k-pd** [comment]
Didn't know that project, looks simple. In other projects I simply used some kind of "auto-updating", using a DB field as version and executing SQL files with names < version until up-to-date. No button clicking, no extra dependencies, minimum additional runtime for checking.

**Comment by mrothauer** [comment]
the goals of the tool are:

1) keeping the db in sync with the source code (for developers)
2) creating a tool for updating the db from one version to another (eg. FCS 1.1.x to 1.2) (for users)

the easier the better, but i am pretty sure that phinx would be easy to use and does the job. as you wish.

**Comment by k-pd** [comment]
Did You know https://github.com/cakephp/migrations before? Its based on Phinx and pretty much what You wish to have. Any experience with backporting from Cake3? Easy or impossible? Much of an advantage: when switching to Cake3 no need to re-do all the migrations stuff.

**Comment by mrothauer** [comment]
sorry, i have no experience with backporting cake3 plugins to cake2. but in that case (plugin for cake3 exists) the migration tool could wait (or maybe a really easy solution in between) until a possible cake update to version 3.

**Comment by k-pd** [comment]
I will analyze the cake3 plugin and decide about porting or another solution.

**Comment by mrothauer** [comment]
perfect!

**Comment by k-pd** [comment]
Cake2/3 and Phinx don't work correctly with the non-SQL ENUM data type. While Cake2 migrations plugin just does nothing, Phinx and Cake3 drop the columns on table changes. Fix: Replace these fields with an Enum() Cake model. Or a TINYINT for ease of use.

Also there are some problems with Cake2's migrations plugin as some Model booleans are actually used as ints. The values are automatically converted to boolean (0/1) on table changes. Didn't test that with Phinx/Cake3, but that is a hard violation of model goals and must be corrected anyways.

And there are Cake Models defining a PRIMARY KEY different from the DB table definitions. This kills the Cake automatisms used to read and compare schema and migration definitions. Don't know, if not defining these wrong PRIMARY KEYs will brake any Model usage.

To get a quick solution I will use the SQL migration files provided and simply apply them to the database on click. Are there plans to add this to Release 1.2 already?

**Comment by mrothauer** [comment]
#34
