### ISSUE TITLE
Bestellungen über längeren Zeitraum

### ISSUE THREAD

**Issue by gueterwege** [foodcoopshop/foodcoopshop#205]
bei uns sind die Bestellungen die über einen längeren Zeitraum gehen die fehleranfälligsten (vergessen zum abholen, ...). Mit den Sammelbestellungen lässt sich das nicht lösen, da manchmal Produzent/innen wöchtentlich Produkte anbieten und manche nur Saisonal. wir haben derzeit fast wöchentlich unregelmäßige produktangebote mit dem abholtag drei tage später oder eine woche später. 
zb: eier gibt´s von tragler jede woche, rindfleisch nur alle drei monate. und sie müssen schon vor dienstag wissen 

daher wäre ideal wenn es eine möglichkeit gibt, dass die bestellungen eine extra spalte mit abholdatum haben. wenn das produkt das abholdatum noch nicht hatte, dann läuft es (scheint auf) unter laufende bestellungen bis es abgeholt wurde. 

oder/und es gibt die möglichkeit dass ich einzelne produkte abschließe und andere nicht. weil wenn ich derzeit 7 von acht produkte abhole und abhake und auf abschließen klicke, dann übernimmt es das produkt das nicht abgehakt ist automatisch. 
bin dankbar für ideen

**Comment by mrothauer** [comment]
danke für euer feedback,
ich werds mit #83 mit im letzten quartal 2018 umsetzen - dauert also noch ein bisschen, wird aber erledigt.

**Comment by mrothauer** [comment]
mit #262 umgesetzt, hier schon mal zum nachlesen und testen:
https://foodcoopshop.github.io/de/bestellabwicklung
https://demo-de.foodcoopshop.com/
