### ISSUE TITLE
Wenn keine Bestellungen, dann leere Bestellungsmail an Hersteller

### ISSUE THREAD

**Issue by gueterwege** [foodcoopshop/foodcoopshop#206]
Bei uns kann es immer wiedermal vorkommen, dass einzelne Produzent/innen mal eine Woche haben wo garkein Produkt bei ihnen bestellt wird, obwohl es möglich wäre. Dann bekomm ich oft die Nachfrage ob wirklich nichts bestellt wurde, oder ob eventuell die Mail untergegangen ist. 
Um abzuklären ob eine Mail untergegangen ist (im Spam ist) oder wirklich nichts bestellt wurde, können sich die Hersteller/innen im Foodcoopshop einloggen und selbst nachsehen ob Bestellungen getätigt wurden. Das vergessen sie leider immer wieder. 
Heute habe ich eine Anregung von einer Produzentin bekommen. Sie fände es praktisch, wenn sie bei Null Bestellungen eine Mail bekommt wo dann der Bestellzettel leer ist. 
Was meint ihr?

**Comment by mrothauer** [comment]
Gute Idee, aber nur, wenn der Hersteller diese Benachrichtigung auch abstellen kann. Weil das passt sicher nicht für jeden.

**Comment by gueterwege** [comment]
stimmt, da hab ich nicht dran gedacht.
