### ISSUE TITLE
Preise auch für Nicht-Mitglieder sichtbar machen

### ISSUE THREAD

**Issue by veronimus** [foodcoopshop/foodcoopshop#210]
Bei uns haben wir wirklich häufig Anfragen von Interessenten, warum die Preise nicht zu sehen sind. Als Lösung haben wir einstweilen einen Beispiel-Warenkorb mit Preisen in einem Blog-Artikel veröffentlicht.

Dennoch wäre es wünschenswert dass jede Foodcoop die Möglichkeit hat, sich fürs Anzeigen der Preise auch für Nicht-Mitglieder zu entscheiden. Dafür sollte es bei den Hersteller-Einstellungen ein Kästchen zum Anhaken geben, damit sich die einzelnen Hersteller dafür oder dagegen entscheiden können.

**Comment by mrothauer** [comment]
Ich kann mir gut vorstellen, dass das dann für Verwirrung sorgt: Bei manchen Herstellern werden Preise angezeigt, bei manchen nicht. Wär's nicht besser, dass die Foodcoop entscheidet, ob Preise für nicht eingeloggte User angezeigt werden, und die Einstellung selbst global vorgibt? Nur so eine Überlegung...

**Comment by gueterwege** [comment]
hallo, 
wir hatten die anfrage bisher noch nicht, und ich vermisse sie auch nicht. ich denke auf alle fälle, es sollte jedeR produzent/in selbst entscheiden können. denn ich kann mir schwer vorstellen, da eine einigung bei den produzent/innen erzielen zu können.

**Comment by mrothauer** [comment]
Hallo Veronika,
ich hab die neue Einstellung bei euch jetzt aktiviert. Ok so?
Lg,
Mario

**Comment by mrothauer** [comment]
Hallo @veronimus ,
ich hab die neue Einstellung bei euch jetzt aktiviert. Ok so?
Lg,
Mario
