### ISSUE TITLE
Blogartikel reihen

### ISSUE THREAD

**Issue by vmvbruck** [foodcoopshop/foodcoopshop#212]
Bei den Blog-Arikeln wäre es sehr praktisch, wenn es im Admin-Bereich die Möglichkeit gäbe, sie durch Ziehen zu verschieben oder aber zu nummerieren und so in neue Reihenfolgen bringen zu können. Derzeit ist's halt mühsamer, wenn man die einzelnen Artikel öffnen und speichern muss, um sie wieder nach vorne zu bringen.

**Comment by mrothauer** [comment]
Gute Idee, ich weiß, das ist nicht optimal. Das Problem bei deinem Vorschlag ist folgender: In der Blog-Artikel-Verwaltung der Hersteller scheinen nur ihre eigenen Blog-Artikel auf. Welcher Blog-Artikel soll jetzt unter "Aktuelles" als erster angezeigt werden, wenn z. B. zwei Hersteller jeweils einen aus ihrer Liste an "ihre" erste Stelle reihen? Vielleicht gibt's ja andere Ideen oder ich denke zu kompliziert...
Lg,
Mario

**Comment by veronimus** [comment]
Aja, daran dass die Hersteller ja auch zu bedenken sind, hab ich nicht gedacht.

Vielleicht sollte die Funktion ja nur für Superadmins zur Verfügung stehen, die ja den Gesamtüberblick haben. Und die von den Herstellern reinkommenden Blogs kommen chronologisch bedingt sowieso an erste Stelle, sobald einer neu reingestellt wird.

Die Superadmins werden die Blogs der Hersteller ja im Normalfall so belassen, zumindest so lange es aktuell ist. Wäre das zu hierarchisch, die letzte Entscheidung bei den Superadmins zu lassen?
