### ISSUE TITLE
Fehler in package.json

### ISSUE THREAD

**Issue by trpouh** [foodcoopshop/foodcoopshop#224]
Foodcoopshop version 2.0.2

Beim ausführen des commands: 

`$ npm --prefix ./webroot install ./webroot` 

Bekomme ich folgenden Error:

> foodcoopshop@ install /Applications/MAMP/htdocs/foodcoopshop_privat/webroot
> bash ../bin/cake npm_post_install

: command not found9: 
'./bin/cake: line 21: syntax error near unexpected token `{
'./bin/cake: line 21: `canonicalize() {
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! foodcoopshop@ install: `bash ../bin/cake npm_post_install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the foodcoopshop@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leonkirschner/.npm/_logs/2018-05-16T08_53_04_293Z-debug.log

**Comment by mrothauer** [comment]
Hallo,
hast du dir den Build von foodcoopshop.com/download runtergeladen oder direkt von github? weil der build wurde auf windows zusammengebaut und es daran könnte es liegen. versuch bitte, die datei bin/cake direkt von github runterzuladen und ersetze sie.
ich werde das beim nächsten build berücksichtigen.
lg,
mario

**Comment by mrothauer** [comment]
hier noch der link
https://raw.githubusercontent.com/foodcoopshop/foodcoopshop/v2.0.2/bin/cake

**Comment by mrothauer** [comment]
hat's funktioniert?
lg,
mario
