### ISSUE TITLE
uploading a new slider image is buggy

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#23]
the size is defined as 905px, but every uploaded image gets a max size of 800px. makes the images look blurry
i guess the problem is in Admin/Controller/ToolsController.php saveUploadedImage

**Comment by k-pd** [comment]
It's not a bug, it's a feature...ToolsController::doTmpImageUpload() resizes all uploaded images to 800px (as configured in app.config,php::app.tmpUploadFileSize). Solutions: change this config setting, switch to not resizing the image there at all or scan config for all ImageSizes arrays and filter out maximum required. Would prefer no resizing in ToolsController::doTmpImageUpload() at all.

**Comment by mrothauer** [comment]
if the tmp image is not resized, it takes a long time to show it when the upload is finished, so resizing it there is necessary. an easy and solution would be changing app.tmpUploadFileSize to 905, a better one to figure out if the max filesize is higher and use this size instead.
