### ISSUE TITLE
simplify installation process

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#25]
* move all file-based configurations to database configuration
* automatically run migrations on first application call after updating => work already in progress
* a notification "new version available - click here to update" would be really cool :-)
* i am sure there are plenty of other important things to do to make installation and update easier

**Comment by k-pd** [comment]
My thoughts for commenting:
**TL;DR**: Installer-Skript als Grundlage für die weitere Verbreitung. Best-Practice WordPress und wie man bei FoodCoopShop sich dem annähern kann.

# Installer
Der Traum der One-Click-Installation ist natürlich nicht realisierbar. Dennoch sollte er das Ziel sein, dem es sich anzunähern gilt.

## Was ist Install und was Basic Config
Die Installation kann man recht gut von der Grund-Konfiguration so abgrenzen: Die Installation umfasst **alle Schritte**, die nötig sind, um das eigentliche System das **allererste Mal** zu starten. Bei diesem allerersten Start verlangt das eigentliche System dann die **Grund-Konfiguration**. Oder es ist bereits ausreichend vorkonfiguriert, so dass eine Weiterleitung auf die normale Einstellungsseite ausreicht.

## Best-Practice WordPress
Genau auf dieser scharfen Abtrennung beruht das Erfolgskonzept der **5-Minuten-Installation** von WordPress (es sind real weniger als 5 Minuten). Der Benutzer lädt das gesamte Programmpaket in den DocumentRoot seines Webspaces, darin ist der Installer und alle nötigen Komponenten enthalten. Nun einfach im Browser die Domain eingegeben und das Installations-System ist gestartet.

Das Installations-System fragt nicht mehr als die Datenbank-Daten und die Zugangsdaten des ersten Benutzers ab. Diese Daten werden sofort überprüft und erst nach der Prüfung wird daraus eine Grund-Konfiguration erstellt. Anschliessend wird der Benutzer sofort auf die neue WordPress-Instanz losgelassen.

Alles was ohne Dateneingabe erfolgen kann, erledigt das Installationsskript ohne Benutzer-Aktion. Natürlich wird der Benutzer informiert, was da gerade geschieht: Schreibrechte werden geprüft, benötigte Software-Pakete werden abgefragt usw. Dieser Mix aus Information und Automatik ist Teil des Erfolgskonzeptes. Im schlimmsten Fall muss man zwischendrin **eine Datei editieren** und ein paar Verzeichnisrechte einstellen. Aber zu allem wird man direkt aufgefordert und muss nicht wieder von vorne anfangen.

Beim Start der neuen WordPress-Instanz fragt das System einmalig alle Daten ab, die nötig sind, um das WordPress fehlerfrei (und störungsfrei für die Blog-o-sphäre) laufen zu lassen. Das sind Titel der Webseite, die URL und Datei-Pfade (zur Kontrolle der automatischen Ermittlung) und die Privacy-Einstellung für die robots.txt. Es empfängt den Benutzer eine großflächige Starthilfe (virtual tour), die später nicht mehr auftaucht.

## FoodCoopShop
So einfach wäre natürlich auch für den FoodCoopShop super. Realisitisch ist aber sicherlich ein Installationsskript ohne Cake, dass das Cake-System einrichtet und danach dann aufruft. Das Skript empfängt den Benutzer mit der Abarbeitung der wichtigsten Vorbedingungen (Programmversionen, benötigte Programmpakete). Das sollte mit wenigen PHP-Mitteln machbar sein (z.B. exec-Aufrufe von ``composer`` und ``bower``). Dann die Datenbank-Zugangsdaten und die eMail-Adresse des ersten Benutzers abfragen und die Konfigurationsdateien damit erstellen. Sobald das alles passt, bekommt der Benutzer seine Zugangsdaten per eMail zugeschickt, und er landet auf der Startseite seines neuen FoodCoopShops.

Als Vorarbeit dazu wäre es hilfreich, die unbedingt nötigen Einstellungen in eine Datei zu packen und alle anderen Sachen über die DB einzustellen. Das Install-Skript kann ohne Probleme schon in die DB schreiben, bevor der Benutzer sich das erste Mal anmeldet, und z.B. seine eMail-Adresse überall eintragen, wo eine erforderlich ist.

Auch eine große Verbesserung ist es, wenn das gesamte System innerhalb des DocumentRoot angesiedelt wird. Ein guter Teil der abschreckenden Install-Schritte ist die Umkonfiguration des Document-Root. Von der Sicherheit her ist es natürlich bestens, aber die Sicherheit lässt sich auch anders herstellen (grundsätzlich nur Read-Rechte für die PHP-Files z.B.).

Weiter hilft es, wenn der Benutzer praktisch keine Konsolenskripte ausführen muss. Entweder weil es keine gibt oder diese über das Web-Interface ausgelöst werden. Die Einrichtung eines Cronjobs z.B. kann auch so erfolgen, dass wget zum Aufrufen einer URL benutzt wird (oder das WordPress-Konzept der user-getriggerten Cronjobs benutzt wird, siehe dort).

## Auto-Update
Je näher man dem One-Click-Konzept kommt, desto näher kommt man auch der Auto-Update-Möglichkeit. Damit ist nicht unbedingt gemeint, dass ungefragt alle paar Tage ein Update eingespielt wird. Es geht mehr um die Aktualisierung per Knopfdruck, ohne Kommandozeile, FTP und dergleichen. Dazu ist einerseits ein System nötig, das "neben" dem eigentlichen System laufen kann, andererseits sind viele Teile identisch mit einem Install-Skript. Z.B. muss das Install-Skript die Datei-Rechte passend setzen können, composer-Pakete laden usw.

**Comment by k-pd** [comment]
Will not be ready within next 4 weeks.

**Comment by mrothauer** [comment]
thx for the info. i see, you already created a new project for the autumn release, perfect!
