### ISSUE TITLE
travis builds are slow

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#253]
since a few days the travis builds slowed down significantly and often lead to timeouts.

`The job exceeded the maximum time limit for jobs, and has been terminated.`

see https://github.com/travis-ci/travis-ci/issues/9948

**Comment by robbinjanssen** [comment]
I based our new install script on your install script, so the least I could do is create PR that should fix this :)

**Comment by mrothauer** [comment]
#256
