### ISSUE TITLE
Do not use referer

### ISSUE THREAD

**Issue by k-pd** [foodcoopshop/foodcoopshop#26]
There are many places, where the HTTP referer is used for forwarding to the previous page (e.g. add article, logout...). This referer can be faked (e.g. by privacy settings). This can be very annoying if not prevent usage at all.

Solution: Internally track last page (e.g. in session) or provide destination URL in HTTP parameter (e.g. ?redirect=/artikel). Internal tracking may cause trouble when using multiple windows, HTTP parameters must be implemented in all link creation methods concerned.

**Comment by k-pd** [comment]
Just found this in WordPress, may help with this: `<input type="hidden" name="_wp_http_referer" value="/wp-admin/network/settings.php?page=myPlugin" />`

**Comment by mrothauer** [comment]
this technique is already used in a lot of admin forms (eg. manufacturer edit). after saving the form it ensures that the redirect leads to the "real" referer, ie the page, where the link to the form was placed.
 this information would be lost when the form is submitted and there are validation errors.
