### ISSUE TITLE
Update 1.3 -> 1.4 Db update error

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#267]
So.
Setting:
I do have a website which currently runs 1.1 and I want to update that to the most current version. But in order to do that savely I wrote some scripts to do that in an automated fashion.
The script first copy the production system to second db+website and on that copied system I then run other scripts to update that from 1.1->1.2->1.3->1.4

The first two updates 1.1->1.2 and 1.2->1.3 run without any problems (ok, I have to delete the tmp/cache/models and tmp/cache/persistent files for the first update manually, and visit the website once for the auto db update to run).

But the update step 1.3->1.4 fails and when I visit the website I do get a notification "DB update error".
So. I am stuck.

Here is that migration script
```
function migrate_to_1_4(){
        new_path=$1
        old_path=$2

        mkdir ${new_path}

        tar_file=${old_path}/bla.tar.gz
        curl -L "https://github.com/foodcoopshop/foodcoopshop/archive/v1.4.0.tar.gz" --output ${tar_file}
        tar -xzf ${tar_file} -C ${old_path}
        rm ${tar_file}

        mv ${old_path}/foodcoopshop-1.4.0/{.,}* ${new_path}
        rmdir ${old_path}/foodcoopshop-1.4.0

        cp -r ${old_path}/webroot/files/. ${new_path}/webroot/files
        cp -r ${old_path}/files_private/. ${new_path}/files_private

        cp ${old_path}/Config/email.php ${new_path}/Config/email.php
        cp ${old_path}/Config/database.php ${new_path}/Config/database.php
        cp ${old_path}/Config/credentials.php ${new_path}/Config/credentials.php
        cp ${old_path}/Config/custom.config.php ${new_path}/Config/custom.config.php

        sed -i -E "s/.*write\('app\.useManufacturerCompensationPercentage'.*/\/\/ deprecated &/g" ${custom_config_path}
        sed -i -E "s/.*write\('app\.defaultCompensationPercentage'.*/\/\/ deprecated &/g" ${custom_config_path}
}
```

Any ideas?

**Comment by mrothauer** [comment]
Please execute the content of the last executed sql-files in Config/sql/migrations manually in phpmyadmin (or a similar tool), then post the error message.
If I remember correctly, before v2 there was a record in the table fcs_configuration FCS_DB_UPDATE_ERROR or similar which shows the number of the failed sql file. eg. 18 for Config/sql/migrations/018.sql

**Comment by Confuset** [comment]
What do you mean by "execute the content of the last executed sql-files in Config/sql/migrations manually"? How do i figure out what was the last one? Update 1.3->1.4 Auto runs the DB updates.

Just looked in the DB and found these entries. Don't know if they help..
![image](https://user-images.githubusercontent.com/7592535/46069884-dba61400-c17c-11e8-9df3-92f4bb9a4d96.png)

**Comment by mrothauer** [comment]
sql not executed: 5
means that 005.sql causes the error.
please try to execute 005.sql in your database, then post the error message.

**Comment by Confuset** [comment]
I see.
SQL Error (1050): Table 'fcs_email_logs' already exists
Which was empty. Dropped it and the SQL now runs without any Errors.

I also checked the production System which does not contain that table…Any clues?

**Comment by mrothauer** [comment]
very good!
if the production system does not contain the table, the migrations should not cause any errors. did I understand your question correctly?

**Comment by Confuset** [comment]
mh.
the question is than where is that table comming from in the first place?
Iam not running any of the migrations myself as you can see in that script. but still i do receive "DB update error" anytime I start from the whole update from scratch by copying that production System and then updating everything. I feels as if that script is ran twice

I will try the following this evening:
Delete the whole test DB and start the Migration again. Now I know where to look at :-)
May be, while creating my update script I failed to drop that DB and run it twice by accident.

Will Keep you updated…

**Comment by mrothauer** [comment]
Ok. Would you mind telling me which foodcoop you are updating? Of course i'm interested who uses the software.

**Comment by Confuset** [comment]
Don't know if I can do that here in public. will send you a mail.

**Comment by Confuset** [comment]
Oh wow. Its been two weeks now. Sorry for that. But I was offline on vacation :-)

So. I did run that upgrade scripts again with an empty database and empty ftp folder. Still the update is not running through. The database migration is not running.
The failing script is 008.sql. If I run that manually again I get that message:
![grafik](https://user-images.githubusercontent.com/7592535/46834298-4ecd9e00-cdab-11e8-9488-3e2803e0107d.png)

**Comment by Confuset** [comment]
Mh. I think I found the issue.
The default of date_add is 'CURRENT_TIMESTAMP'. The mysql version of our hoster is version 5.5.61.
A quick google search revealed:

> You cannot set the default for a date column to be the value of a function such as NOW() or CURRENT_DATE. The exception is that you can specify CURRENT_TIMESTAMP as the default for a TIMESTAMP column

And from there:

> As of MySQL 5.6.5, TIMESTAMP and DATETIME columns can be automatically initializated and updated to the current date and time (that is, the current timestamp). Before 5.6.5, this is true only for TIMESTAMP, and for at most one TIMESTAMP column per table.

So I guess Iam screwed for now.

**Comment by mrothauer** [comment]
as mentioned in https://foodcoopshop.github.io/en/installation-details: the minimal mysql requirement is 5.6, version 5.7 is recommended.

**Comment by mrothauer** [comment]
i think that's the best solution.
