### ISSUE TITLE
Preis nach Gewicht (Basis-Preis) für bereits getätigte Bestellungen ändern

### ISSUE THREAD

**Issue by vmvbruck** [foodcoopshop/foodcoopshop#281]
Bei Sammelbestellungen z.B. für Backzutaten (Zucker, Mohn, Nüsse etc.), bei denen erst nach erfolgter Lieferung die endgültigen Preise feststehen, kann man derzeit leider die Funktion "Preis nach Gewicht" nicht nutzen, da diese Daten ja eingegeben werden müssen, bevor von den KonsumentInnen im Shop bestellt wird. Bei der Abholung kann der Basispreis rückwirkend nicht geändert werden (wie es bei Gewicht und Preis möglich ist). 
Der Basispreis wäre aber gerade bei solchen Bestellungen von Interesse, weil die Produkte in Großgebinden bestellt und mittels Abwiegen aufgeteilt werden.

https://www.foodcoopshop.com/crowdfunding-weiterentwicklung

**Comment by mrothauer** [comment]
## Umsetzung

Wenn eine Bestellung oder mehrere Bestellungen markiert sind (Hakerl), kann unten auf den neuen Button "Basis-Preis ändern" geklickt werden. Dann kann der neue Basis-Preis eingetragen werden und die Preise berechnen sich automatisch neu. E-Mails werden an die Mitglieder (und evtl. auch an Hersteller) versendet.

**Comment by mrothauer** [comment]
hallo @vmvbruck ist das noch aktuell? könnte ich im zuge der umsetzung von #1006 mitmachen.
lg mario

**Comment by mrothauer** [comment]
wird mit #1006 miterledigt
