### ISSUE TITLE
(Ersten) Hersteller hinzufügen schlägt fehl

### ISSUE THREAD

**Issue by SigiK** [foodcoopshop/foodcoopshop#288]
- Auftreten bei beiden Versionen v2.2 und v2.3;
- Neuinstallation mit sql-scripts auf Debian Stretch, MySQL 7.2, PHP 5.7.24
- Installierte php-extensions: gd2, intl, mbstring, pdo_mysql

Habe mich soweit an die Installationsanleitung gehalten und Admin-Login funktioniert. 
Fehlt womöglich eine php-Extension o.ä?

Vielen Dank für die Mühe und den grossartigen Shop!!!

Fehlermeldung: 
`2018-12-04 11:39:42 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'no_delivery_days' doesn't have a default value
Request URL: /admin/manufacturers/add
Referer URL: http://bioseiterlstettner.hopto.org/admin/manufacturers/add
Stack Trace:
#0 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Connection.php(334): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php(68): Cake\Database\Connection->Cake\Database\{closure}()
#3 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Connection.php(337): Cake\Core\Retry\CommandRetry->run(Object(Closure))
#4 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Query.php(219): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Table.php(2114): Cake\Database\Query->execute()
#6 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Table.php(2008): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Table.php(1921): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Table.php(1634): Cake\ORM\Table->Cake\ORM\{closure}()
#9 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Connection.php(726): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#10 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Table.php(1635): Cake\Database\Connection->transactional(Object(Closure))
#11 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Table.php(1922): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#12 /var/www/foodcoopshop/plugins/Admin/src/Controller/ManufacturersController.php(149): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#13 /var/www/foodcoopshop/plugins/Admin/src/Controller/ManufacturersController.php(78): Admin\Controller\ManufacturersController->_processForm(Object(Cake\ORM\Entity), false)
#14 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Controller/Controller.php(609): Admin\Controller\ManufacturersController->add()
#15 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction()
#16 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(Admin\Controller\ManufacturersController))
#17 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 /var/www/foodcoopshop/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php(65): AssetCompress\Middleware\AssetCompressMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#25 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#26 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#27 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 /var/www/foodcoopshop/webroot/index.php(40): Cake\Http\Server->run()`

**Comment by mrothauer** [comment]
du meinst wohl php 7.2 und mysql 5.7.24 nehme ich an, oder?
ich hätte jetzt mal auf falsche mysql-version getippt, aber auch bei den tests auf travis wird die gleiche version verwendet. das müsste also passen.
see https://travis-ci.org/foodcoopshop/foodcoopshop/jobs/463201131 zeile 575
probier mal das hier bitte:
https://stackoverflow.com/questions/18751291/mysql-error-1364-field-display-name-doesnt-have-default-value#18751364
viel erfolg,
mario

**Comment by SigiK** [comment]
Php und Mysql waren copy paste Fehler :-)

Genau das war die Lösung wie im zweiten Link angeführt:

`SELECT @@GLOBAL.sql_mode;
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

um zu sehen welche Parameter eingestellt waren und dann:

**`mysql> SET GLOBAL sql_mode='';`**

Dürfte wohl am Feld "no_delivery_days" gelegen sein, das keine Nullables erlaubt und keinen default value hat:
`CREATE TABLE 'fcs_manufacturer' ( ... 'no_delivery_days' text NOT NULL... )`

Vielen herzlichen Dank für die schnelle Hilfe!!!
