### ISSUE TITLE
Bestelllisten leer - kein Bestelllistenversand

### ISSUE THREAD

**Issue by SigiK** [foodcoopshop/foodcoopshop#311]
Das ist ein

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)
* [x] Konfigurationsproblem 

* FoodCoopShop Version: v2.3.
* Browser und Betriebssystem / Browser and Operating System: unabhängig
* Platform and Target: Debian Stretch, MySQL 5.7.24, PHP 7.2

### Was hast du gemacht? What you did?
* Es wurden Bestellungen aufgegeben und sind mit Status "Bestellung getätig" vermerkt 
* Cronjobs wurde soweit konfiguriert; Backup kommt z.B. per E-Mail, Datenbankeintrag mit success (fcs_cronjob_logs: 82,6,'2019-01-23 04:30:01',1)
* kein Errorlog via Mail

### Was ist passiert? What happened?
* Im Menüpunkt Bestellungen->Bestelllisten im Adminbereich sind alle Bestelllisten leer (auch vergangene) egal welchen Abholtag ich auswähle
* Es werden keine Bestelllisten an den Hersteller versandt obwohl in den fcs_cronjob_logs ein Eintrag mit succcess steht (vielleicht weil sie leer sind?)

### Was sollte passieren? What you expected to happen?
* Die Bestelllisten sollten an die Hersteller geschickt werden und die Bestelllisten sollten nicht leer sein (oder?)

Vielen Dank und sorry, dass ich schon wieder lästig bin ;-)

**Comment by mrothauer** [comment]
Hallo Sigi,
1) Bist du wirklich sicher, dass für den entsprechenden Abholtag Bestellungen vorhanden waren?
2) Welche Werte haben die Config Variablen app.sendOrderListsWeekday und app.deliveryDayDelta?
3) Läuft der Cronjob auch am gleichen Wochentag wie app.sendOrderListsWeekday? Ggfs. in der Tabelle fcs_cronjobs den Wert ändern.

**Comment by mrothauer** [comment]
Es sollten unter Admin / "Bestellungen" mit dem entsprechenden Abholtag Bestellungen vorliegen. Die sind dann gültig.

Die Kombination  von SendOrderListsWeekday = 4 und deliverydaydelta = 1 ist nicht gängig, auch daran kanns liegen (wär dann tatsächlich ein bug). wäre es möglich, dass ihr die listen am mittwoch verschickt? SendOrderListsWeekday = 3 und deliverydaydelta = 2? diese kombination ist geläufig und funktioniert sicher.

**Comment by SigiK** [comment]
Ok, dann liegen definitv Bestellungen vor... 
Wir wollten eigentlich Bestellungen bis Mittwoch Mitternacht (also eigentlich ja 4 Uhr in der Früh). 
Ich werde es nocheinmal zurückstellen für nächste Woche und schau mal was passiert ... vielen Dank einmal vorerst! Lg Sigi

**Comment by mrothauer** [comment]
hat sich das problem erledigt?

**Comment by SigiK** [comment]
Nein noch nicht, habe noch vergessen den Tag in der Tabelle fcs_cronjobs zu ändern :-(...
Bitte noch bis Mittwoch warten, dann kann ich mehr sagen... falls es das Problem sein sollte, wäre es vielleicht überlegenswert, auch den Mittwoch als letzten Bestelltag wählbar zu machen. Lg Sigi

**Comment by mrothauer** [comment]
ok danke für die rückmeldung. theoretisch müsste es auch mit sendOrderListsWeekday = 4 hinhauen, wenn nicht dann kanns nur ein kleiner bug sein.
man müsste nur den test erweitern um eine ThursdayFriday-Config
https://github.com/foodcoopshop/foodcoopshop/blob/develop/tests/TestCase/src/View/Helper/MyTimeHelperTest.php
lg mario

**Comment by mrothauer** [comment]
hab die tests jetzt hinzugefügt - es müsste alles passen für eine donnerstag / freitag config
https://github.com/foodcoopshop/foodcoopshop/commit/872f3f3a510e78c637a8d2964175f14ecb3cb645
lg,
mario

**Comment by SigiK** [comment]
Vielen Dank Mario, 

aber leider hat der Versand scheinbar noch immer nicht geklappt (heute Mittwoch). Dürfte wohl unabhängig von dem Bestelltag sein. Habe eine Testbestellung mit Besteller mit einer gmail-Adresse mit 1c hinzugefügt und auch einen anderen Hersteller mit aon und DB-Eintrag ist wieder 

`| 133 |          6 | 2019-02-06 04:30:01 |       1 |
`

DB-Update hat wieder geklappt. Also im Endeffekt wie vorher... muss wohl noch an einer anderen Stelle suchen. Wie gesagt die Tabellen unter Bestellungen->Bestellisten sind immer und waren immer leer (sollte das so sein?).

Vielen Dank für deine Tests, zumindest können wir dann sicher sein, dass wir dann auch Mittwoch als letzten Bestelltag nehmen.

'deliveryDayDelta' => 2, in custom_config.php
'sendOrderListsWeekday' => 3, in app_config.php

Lg Sigi

**Comment by mrothauer** [comment]
steht was im /logs/error.log bzw. /logs/debug.log?

**Comment by SigiK** [comment]
Nein leider, über welchen Emailclient werden die eigentlich gesendet? Ich habe nämlich nicht alle aktiviert in den Configs.

**Comment by mrothauer** [comment]
über EmailTransport::default
wenn admin/configurations/sendTestEmail eine email versendet passt alles

**Comment by SigiK** [comment]
Ok, anbei noch meine credential.php
Übrigens mache ich persönliche Bestellungen über my-personal-mail=super admin account, sollte man wohl nicht machen oder?

[credentials-adapted.txt](https://github.com/foodcoopshop/foodcoopshop/files/2835832/credentials-adapted.txt)

**Comment by mrothauer** [comment]
ich glaub fast es ist am einfachsten wir telefonieren mal. kannst du mir deine telefonnummer schicken an office@foodcoopshop.com, dann ruf ich dich anfang nächster woche an. gehts vormittags bei dir? lg mario

**Comment by SigiK** [comment]
Gut, Problem wurde gelöst, nachdem ich das ganze mal debugged habe. Es war tatsächlich notwendig die debug-Emailadresse zumindest für die Backups anzugeben in src/Shell/BackupDatabaseShell.php Zeile 70:

`$email->setProfile('debug');`

Nachdem diese richtig konfiguriert wurde

```
    'EmailTransport' => [
        'default' => [
	    'emailFormat' => 'html',
            'className' => 'Mail',
            'host' => 'ssl://smtp.myhost.com',
            'port' => 465,
            'timeout' => 30,
            'username' => 'myusername',
            'password' => 'mypassword',
        ]
    ],
    'Email' => [
        'default' => [
             'from' => ['ourmail@ourdomain.at' => 'Our Foodcoop'],
             'charset' => 'utf-8',
             'headerCharset' => 'utf-8',
        ]
    ],
```
ging auch der Bestellistenversand.

**Comment by mrothauer** [comment]
hmmm, dürfte nichts mit dem bestelllistenversand zu tun haben, aber ich glaub dir das auf jeden fall :-) aber super, dass es jetzt funktioniert!
