### ISSUE TITLE
Sofortbestellung nur für Lagerprodukte und vice versa

### ISSUE THREAD

**Issue by AndreasEgger** [foodcoopshop/foodcoopshop#322]
Das ist ein
* Verbesserungsvorschlag / enhancement

Hi Mario, ist es möglich (und auch für andere Foodcoops nicht kontraproduktiv) dass Sofortbestellungen nur für Lagerware möglich sind und/oder umgekehrt Lagerware nur über Sofortbestellung bestellt werden kann? Zumindest das zweitere wäre eine gewissen Erleichterung.

**Comment by mrothauer** [comment]
* [ ] Lagerprodukte sollen niemals bei "normalen" Bestellungen (mit Lieferung) aufscheinen
* [ ] Nicht-Lagerprodukte sollen bei Sofort-Bestellungen niemals aufscheinen
* [ ] evtl. Übertrag eines bestellten Produktes auf ein anderes Mitgliedskonto gleich mitmachen. Damit beim Fehlen eines Produktes am Ende eines Abholtages dieses ohne Stornierung/Sofort-Bestellung auf das Vereins-Mitgliedskonto umgebucht werden kann.

**Comment by mrothauer** [comment]
Hallo Andreas,

ich hab das grad umgesetzt und bei euch eingespielt. Du kannst also die Kategorien "Lagerprodukte" löschen.

Was jetzt natürlich nicht mehr geht: Lagerprodukte mit der normalen Bestellung mitbestellen.

Weitere Ideen:
* Bei Sofort-Bestellungen könnte man Hersteller, die die erweiterte Lagerstandsverwaltung nicht aktiviert haben, ausblenden.
* Es könnten auch Kategorien mit 0 Produkten ganz ausgeblendet werden.
* Beide Ideen könnten aber auch verwirren - was meinst du?

**Comment by mrothauer** [comment]
Endgültige Umsetzung
* Normale Bestellung: Lagerprodukte werden angezeigt, sind aber nicht bestellbar.
* Sofort-Bestellung: Es werden nur Lagerprodukte angezeigt.
* Zwei neue Datenbank Einstellungen
