### ISSUE TITLE
Individueller Bestellschluss

### ISSUE THREAD

**Issue by AndreasEgger** [foodcoopshop/foodcoopshop#323]
Das ist ein
* Vorschlag für neue Funktion / feature-discussion (RFC)

Der Bestellschluss kann pro Hersteller auch unterschiedlich festgelegt werden (zB Montag Mitternacht statt Dienstag Mitternacht). Bei den Produkten des Herstellers erscheint dadurch zB am Dientag bereits das Abholdatum der nächsten Woche. Das geänderte Abholdatum soll besonders hervorgehoben sein.

**Comment by mrothauer** [comment]
Ziel: Für gewisse Hersteller / Produkte soll Montag (statt Dienstag) der letzte Bestelltag sein. Anzeige des Abholtags springt dann am Dienstag auf Freitag nächste Woche um.

* [ ] Neues Feld "delivery_rhythm_send_order_lists_delta" bei "Lieferrhythmus": Bestelllistenversand: x Tage vor Abholtag (app.deliveryDayDelta = 2) inkl. Erweitern des Netzwerk-Modules
* [ ] Defaultwert: app.deliveryDayDelta, löschen der Config-Variable (auch aus Dokus)
* [ ] Anpassen der Berechnung des Abholtages aufgrund des neuen Feldes
* [ ] Umstellen von SendOrderListsShell auf **täglicher** Aufruf
* [ ] Unit-Tests

**Comment by mrothauer** [comment]
* [x] Neue Felder "delivery_rhythm_send_order_list_day_delta" und "delivery_rhythm_send_order_list_day" 
* [x] Migration: Setzen von app.DeliveryDayDelta als Default-Wert in neuer Spalte
* [x] Neue Db-basierte Config-Variablen: FCS_WEEKLY_PICKUP_DAY und FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA
* [x] Configurations-Seite anpassen
* [x] Neue Produkte: Defaultwert für delivery_rhythm_send_order_list_day_delta: FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA
* [x] Text anpassen: Der Hersteller möchte - falls es Bestellungen gibt - diese am Mittwoch per E-Mail erhalten.
* [ ] Löschen der Config-Variable app.sendOrderListWeekday
* [ ] Unit-Tests anpassen / erweitern
* [ ] Lieferrhythmus-Formular anpassen:
wöchentliche Rhythmen: Dropdown- jeden Montag / Dienstag / Mittwoch / Donnerstag vor dem Abholtag
individuell: Datum (sinnvolle Validierungen)
* [ ] Anpassen der Berechnung des Abholtages für das Frontend
* [ ] Umstellen von SendOrderListsShell auf **täglicher** Aufruf
* [ ] Erweitern des Netzwerk-Modules
* [ ] migration guide anpassen (app.sendOrderListsWeekday löschen, app.deliveryDayDelta löschen)
* [ ] Dokus, readme.md anpassen:  app.sendOrderListsDay gelöscht
