### ISSUE TITLE
Automatisches Zurückstellen der Verfügbarkeit nach Lieferung

### ISSUE THREAD

**Issue by AndreasEgger** [foodcoopshop/foodcoopshop#324]
Das ist ein 
* Vorschlag für neue Funktion / feature-discussion (RFC)

Wenn ein Produzent in seinem Lieferrhythmus für ein Produkt immer die gleiche Stückzahl zur Verfügung hat, wäre es praktisch, wenn sich die verfügbare Stückzahl immer automatisch nach Lieferung zurückstellen würde. 
Beispiel: Scheibler Eier hat jede Woche 10 6er-Kartons und 6 10er-Kartons Eier für uns zur Verfügung. Derzeit wird jede Woche die Anzahl neu eingestellt. Dies könnte ev. auch automatisch erfolgen.

**Comment by veronimus** [comment]
Wäre wirklich in einigen Fällen sehr nützlich.
