### ISSUE TITLE
vendor/autoload.php fehlt nach upgrade/migration

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#329]
Hallo,
ich versuche gerade eine alte Installation v1.1. auf v2.0 zu heben und dabei einen wechsel des Servers durchzuführen. Bis 1.5 muss ich dabei auf dem alten Server bleiben, weil auf dem neuen Php7 läuft und CakePhp erst ab Version 3.0 mit Php7 funktionieren will…

Nachdem ich der Installations/Migrations-Anleitung gefolgt bin und versuche auf dem neuen Server auf die Website zuzugreifen, bekomme ich ein 500 und im log steht folgende Meldung:
`vendor/autoload.php): failed to open stream: No such file or directory in /srv/http/webroot/index.php`
Wenn ich in das besagte Verzeichnis gucke ist dort auch kein autoload.php.
Alle hinweise im Netz sagen mir auch brauche `composer install` allerdings, steht in der Installationsanleitung das ich den nur brauche wenn ich eine DEV Installation haben will.
Nun bin ich etwas irritiert was ich machen soll.
Eine Idee?

**Comment by mrothauer** [comment]
Hallo,
https://www.foodcoopshop.com/wp-content/uploads/releases/FoodCoopShop-v1.5.0.zip
Vendor/autoload.php ist vorhanden
Außerdem: https://book.cakephp.org/2.0/en/installation.html
CakePHP version 2.8.0 and above support PHP 7.

**Comment by Confuset** [comment]
wow. das ging fix :-)
ich habe mir die Versionen immer von github installiert `https://github.com/foodcoopshop/foodcoopshop/archive/v1.5.0.tar.gz`
da ist sie nicht enthalten…hätte ich diese nehmen sollen?
Also kann ich nun entweder den composer installieren/nutzen oder die version von deinem link benutzen?

Und zu cake: macht nix. ich habe es auf dem alten Server auf 1.5 heben können.

**Comment by mrothauer** [comment]
der unterschied der downloads über foodcoopshop.com und denen auf github, ist, der dass bei ersteren die dependencies bereits installiert sind.
für den download von github müsstest du nur "composer install" ausführen und im ordner webroot "npm install" - was aber nodejs erfordert.
viel erfolg,
mario

**Comment by Confuset** [comment]
jap. hat funktioniert :-)
danke
