### ISSUE TITLE
fcs_blog_posts fehlt nach upgrade von 1.1 auf 2.0

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#330]
Hi,
ich versuche ja gerade unseren alten Shop auf die 2.x zu aktualierien.
Nachdem ich nun bei 2.0 angelangt bin, findet sich im 'error.log' der hinweis das besagte Tabelle fehlt…Ich habe auch mal nachgeguckt und sie nicht gefunden…
In welcher Version kam die denn dazu? Evtl. ist irgendwas beim Migrieren schief gegangen…
Eine Idee?

**Comment by mrothauer** [comment]
vermutlich ist die Migration18 fehlgeschlagen und irgendwas schief gelaufen
https://github.com/foodcoopshop/foodcoopshop/blob/develop/config/Migrations/20180213193117_Migration018.php
am besten alle sql statement manuell durchführen

**Comment by mrothauer** [comment]
es kann sein, dass es genügt, die tabelle phinxlog zu leeren, die migration 20180213193116_InitPhinxlog.php zu löschen und danach bin/cake migrations migrate aufzurufen

**Comment by Confuset** [comment]
mmhh. es gab kein `*_InitPhinxlog.php`.
laut der phinxlog tabelle wurden alle migrations ausgeführt. ein erneutes aufrufen von `bin/cake migrations migrate` gibt einen fehler aus…
ich geh  nochmal auf die 1.5 runter und probiere es nochmal

**Comment by Confuset** [comment]
also mit meiner vermeintlichen 1.5 datenbank kommt es beim ausführen von `*_Migration018.php` zu dieser fehlermeldung:
`ERROR 1072 (42000) at line 82: Key column 'id_shop' doesn't exist in table`
ich guck morgen abend nochmal rein…

**Comment by Confuset** [comment]
`./bin/cake migrations migrate` läuft allerdings ohne sichtbaren fehler durch…

**Comment by mrothauer** [comment]
vor 2.0 müssen alle "alten" migrations ausgeführt sein, vielleicht ist da was vergessen worden. die files sind in 2.0 gar nicht mehr drin.
https://github.com/foodcoopshop/foodcoopshop/tree/v1.5.0/Config/sql/migrations

**Comment by mrothauer** [comment]
hat's geklappt?

**Comment by Confuset** [comment]
Entschuldige. Ich lag letzte Woche flach.

Also wie sich heraugestellt hat, ist das binärkompatible dropin replacement MariaDB doch nicht so sehr kompatibel...
Ich setze die Website gerade auf einem Archlinux Server auf und dieser installiert anstelle von mysql MariaDB. Und MariaDB hat Probleme mit dem 18. Migrationsskript..Durfte dann erstmal mysql aus AUR selbst kompilieren..Tolle Wurst..

Aber damit läufts :)

**Comment by mrothauer** [comment]
Schön, dass es läuft!
Hmmm, also ich entwickle auf Windows mit einem ziemlich aktuellen Xampp (inkl. MariaDB 10.1.37) und alles funktioniert super. Auch zum Zeitpunkt, als ich das 18. Migrationsskript laufen hab lassen hatte ich schon MariaDB.
Vielleicht könntest du die https://foodcoopshop.github.io/en/installation-details mit deinen Erkenntnissen erweitern, damit zukünftige User weniger Probleme haben?
Einfach https://github.com/foodcoopshop/foodcoopshop.github.io/blob/master/en/installation-details.md forken und Pull Request erstellen.
Vielen Dank,
Mario

**Comment by Confuset** [comment]
ich habe ja eh vor meine scripte auf github zu stellen wenn ich durch bin. aktuell habe ich welche um von 1.2 auf 2.0 zu kommen. sieht so weit ganz gut aus.

du müsstest mir aber nochmal erklären für was die rewrites sind beim sprung auf 2.0. irgendwie haben die bei mir keinen effekt oder ich brauch die nicht. ka.

funktioniert auch so…(hab aber ein nginx)

**Comment by mrothauer** [comment]
ok super. die zusätzlichen rewrites in der .htaccess sind nur dann notwendig, wenn lang mit 1.x gearbeitet wurde und alte links weiterhin funktionieren sollen (weil die sich teilweise geändert haben). ob die redirects auch mit nginx funktionieren weiß ich leider nicht.

**Comment by Confuset** [comment]
alles klar. dachte ich mir irgendwie, weil alles direkt funktioniert hat ob mit oder ohne rewrites.
es gibt einen online htaccess to nginx rewrite converter. der nur teilweise funktioniert, weil er eine location für alle /admin urls erzeugt. das ist natürlich falsch, weil das ja nur für die entsprechenden urls passieren soll…

egal. ich meld mich wenn ich die scripte fertig habe.

**Comment by Confuset** [comment]
danke auf jedenfall für deine hilfe :-)

**Comment by mrothauer** [comment]
ja, super. immer gerne!

**Comment by Confuset** [comment]
Das  Projekt lag jetzt eine Weile auf Eis, aber hier als Referenz das konkrete Problem mit MariaDB vs. MySQL und `id_shop`.
Hier der Bugreport https://jira.mariadb.org/browse/MDEV-13613
Hier die Doku zu dem Verhalten https://mariadb.com/kb/en/alter-table/#drop-column

Problematische Datei:
`config/Migrations/20180213193117_Migration018.php`

Also erstmal muss folgendes gemacht werden:
```
ALTER TABLE fcs_images
  DROP PRIMARY KEY;
```
Dann Zeile 90:
```
ALTER TABLE `fcs_images` DROP `id_shop`, DROP `cover`;
```

```
ALTER TABLE `fcs_images` ADD CONSTRAINT PRIMARY KEY (id_image);
```
