### ISSUE TITLE
Bestellliste: Summe bei Einheiten

### ISSUE THREAD

**Issue by markuskoban** [foodcoopshop/foodcoopshop#333]
kosmetisch und arithmetisch wäre es hilfreich, wenn auf den Bestelllisten statt Anzahl, Produkt, Preis, ... auch die Summe (vielleicht in Klammer) aus Anzahl und Produkteinheiten stehen würde.
Bsp. 
derzeit: 46x | Gelbe Rüben : 250g | ...
neu: 46x | Gelbe Rüben : 250g **(11500g)** | ... 

https://www.foodcoopshop.com/crowdfunding-weiterentwicklung

**Comment by mrothauer** [comment]
ja das ist sicher sinnvoll - aber nur bei produkten, bei denen der preis nach gewicht angegeben ist. sonst kann man in das feld "einheit" ja reinschreiben was man will (z.b. 1 glas, 1 paar usw.).
aber bei preis nach gewicht machts total sinn, da geb ich dir recht.
auf den rechnungen wird das übrigens (aber auch nur bei "preis nach gewicht") bereits berücksichtigt.
