### ISSUE TITLE
Verfügbare Menge nach tatsächlich entnommenem Gewicht

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#336]
**Use-Case**: Die Foodcoop hat z.B. 25 kg Nudeln gekauft. Jedes Mitglied nimmt dann x kg heraus und trägt genau das entnommene Gewicht ein.

**Problem:** Momentan wird die Anzahl um jeweils 1 verringert, das Gewicht pro Anzahl ist dann das entnommene Gewicht in kg. Die Foodcoop müsste daher für diesen Fall z.B. als Anzahl 25 Stück eintragen und die Mitglieder auffordern, sich immer ungefähr 1 kg zu nehmen, damit der Lagerstand in etwa stimmt. Kann dann dazu führen, dass jemand nicht bestellen kann, obwohl noch was da ist.

**Lösung:** Lagerstand von der entnommenen Menge in kg abhängig machen und den Lagerstand (Anzahl) gar nicht berücksichtigen.

https://www.foodcoopshop.com/crowdfunding-weiterentwicklung

**Comment by simonschmeisser** [comment]
Hallo Mario,

wir evaluieren grade lösungen für unsere foodcoop Kornkammer in Freiburg. Ist dieses issue noch aktuell?

Wir haben bei unserer bisherigen Lösung ( https://github.com/Kornkammer/foodcoapp ) massive Probleme mit dem Gewicht und numerikfehlern/rundungsfehlern. Nur so zur warnung ;) Eventuell machts auch sinn ins negative buchen zu können, würde uns momentan bei unserer app jedenfalls helfen. Also Restmenge real 759g Nudeln, Waage sagt 760g, Benutzer ist verwirrt und frustriert. Oder Usecase 2: Nudeln sind schon eingeräumt aber noch nicht eingebucht.

Vielen Dank
Simon

**Comment by mrothauer** [comment]
Hallo Simon,
ja, dieses Issue ist noch aktuell, hat aber eine niedrige Priorität. Werde ich eventuell mal umsetzen, sobald das neue Selbstbedienungs-Modul im Echtbetrieb ist.
https://foodcoopshop.github.io/de/selbstbedienungs-modus.html
Aber danke für deine Infos!
Lg,
Mario

**Comment by Podden** [comment]
Hallo, ich füge hier auch nochmal den Wunsch ein, dass das umgesetzt wird.
Wir arbeiten mit Lager und Selbstbedienung, kaufen also unabhängig von Bestellungen ein und geben alle Lebensmitten unabgepackt zum selbstwiegen raus. Wäre sehr cool, trotzdem das Einheitensystem nutzen zu können und nicht auf Gewicht umzuschwenken um die Lagerstände im Auge haben zu können.

Ein Vorschlag für die Zwischenzeit, der vielleicht einfacher umzusetzen ist, wäre die Preisberechnung für Einheiten optional nicht zu runden. Man könnte so z.B. Seife für 2,98/Liter mit der Einheit ml und der Anzahl 1000 (aka 1 Liter auf Lager) nutzen, das ist aber momentan nicht möglich, weil der Preis von 0,00298€/ml auf 0,00 € gerundet wird.

**Comment by mrothauer** [comment]
* [ ] Die Felder "Aktueller Lagerstand", "Bestellbar bis zu einer Anzahl von" und "E-Mail-Benachrichtigung ab Anzahl" müssen bis zu 3 Kommastellen speichern können (Struktur-Anpassung der Datenbank)
* [ ] Die Einheit (g/kg/l) wird beim Produkt bereits definiert, nämlich beim "Preis nach Gewicht". Die Einheit, die dort gespeichert ist, verwende ich und zeige sie neben den oben genannten Feldern an.
* [ ] Die neue Funktion ist nur für Lagerprodukte sinnvoll, deswegen würde ich sie daran koppeln.
* [ ] Wenn das Produkt ein Lagerprodukt ist, aber die Funktion "Preis nach Bestelleinheit" verwendet wird, bleibt alles beim Alten (Anzahl nach Stück).
* [ ] Vorbestellung: die bei "Preis nach Gewicht" definierte "ungefähre Liefermenge" wird vom Lagerstand abgezogen (wenn beim Feld "Anzahl" z.B. 2 ausgewählt wird, wird die Liefermenge verdoppelt)
* [ ] Selbstbedienung: der Lagerstand wird um das eingetragene Gewicht vermindert. Auch hier kann theoretisch 2x1kg bestellt werden => korrekt multiplizieren
* [ ] Die Funktion "Gewicht anpassen" von bereits bestellten Produkten muss auch die verfügbare Menge des Produktes verändern
* [ ] Anzeige der verfügbaren Menge im Produktkatalog (beim Bestellen): Einheit dazu anzeigen (z.B. 34,255 kg)
