### ISSUE TITLE
sha256 falsch download section? FoodCoopShop v2.4.1

### ISSUE THREAD

**Issue by KristijanK** [foodcoopshop/foodcoopshop#347]
* [x] Bug?
Ist der SHA Key im Download Bereich für die Version 2.4.1 korrekt eingetragen? Ich erhalte leider einen andern Wert beim prüfen. 

* FoodCoopShop Version: 2.4.1 
* Browser und Betriebssystem / Browser and Operating System: Ubuntu 18.04.2 LTS  und auch getestet auf Macosx 10.12 command line 
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### Was hast du gemacht? What you did?
curl -O https://www.foodcoopshop.com/wp-content/uploads/releases/FoodCoopShop-v2.4.1.zip
shasum -a 256 FoodCoopShop-v2.4.1.zip

### Was ist passiert? What happened?
ergebnis: c51e037482c7df8749417e1904e703cff7a9f78644c835eab5b4a1e23348c1ac
### Was sollte passieren? What you expected to happen?
Checksum (SHA256): cd26d13bd625cc88704ecf8a58924594b68b5d00439918c58d09b3b29477b30c

Stimmt der Key oder wie muss ich verifizieren das das File nicht korrupt ist...
Vielen Dank vorab 

Liebe Grüsse 

Kristijan 

P.S. Cooles Projekt

**Comment by mrothauer** [comment]
Hi Kristijan,
deine Checksum ist korrekt, ich hab sie falsch berechnet.
Danke für den Hinweis, hab die Checksum auf der Download-Seite angepasst. Die Datei ist ok.
Lg,
Mario

**Comment by KristijanK** [comment]
Hallo Mario,

ich habe klemme hier gerade bei der Installation fest, glaube aber auch nicht das es ein Bug ist.
Ich bekomme von Email.php die Fehlermeldung hast du vielleicht ein Hinweis wo der Fehler liegen könnte?
Falsche Konfiguration oder habe ich irgendwo was versammelt?

Danke Vorab
LG

Kristijan



2019-04-16 21:56:21 Error: Fatal Error (1): Uncaught InvalidArgumentException: Unknown email configuration "debug". in /home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/vendor/cakephp/cakephp/src/Mailer/Email.php:2238
Stack trace:
#0 /home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/vendor/cakephp/cakephp/src/Mailer/Email.php(2078): Cake\Mailer\Email->_applyConfig(NULL)
#1 /home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/src/Log/Engine/FileAndEmailLog.php(72): Cake\Mailer\Email->setProfile('debug')
#2 /home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/src/Log/Engine/FileAndEmailLog.php(34): App\Log\Engine\FileAndEmailLog->sendEmailWithErrorInformation('[InvalidArgumen...')
#3 /home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/vendor/cakephp/cakephp/src/Log/Log.php(384): App\Log\Engine\FileAndEmailLog->log('error', '[InvalidArgumen...', Array)
#4 /home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/vendor/cakephp/cakephp/src/Log/Log.php(453): Cake\Log\Log::write('error', '[InvalidArgumen...', Array)
#5 /home2/kkolak/foodcoop.kristijan-k.de/foodcoopsho in [/home2/kkolak/foodcoop.kristijan-k.de/foodcoopshop/vendor/cakephp/cakephp/src/Mailer/Email.php, line 2238]

**Comment by mrothauer** [comment]
hallo kristijan,
Unknown email configuration "debug" bedeutet, dass
https://github.com/foodcoopshop/foodcoopshop/blob/21edd2a3e3c88ccf360e9467791fa5438e0bc5b1/config/credentials.default.php#L75-L94
eine korrekte config darstellen und einkommentiert sein muss
lg,
mario

**Comment by TheFox** [comment]
@mrothauer In the Installation documentation it's not that clear you MUST HAVE everything in place.

**Comment by mrothauer** [comment]
it would be great if you tell me what exactly is not clear - ideally by a PR :-)
