### ISSUE TITLE
Guthabenaufladung

### ISSUE THREAD

**Issue by SigiK** [foodcoopshop/foodcoopshop#356]
* [x] Vorschlag für neue Funktion / feature-discussion (RFC)

### Was sollte passieren? What you expected to happen?
Wäre es möglich, nur für Administratoren eine Guthabenaufladung zu erlauben. Wir heben einen Unkostenbeitrag ein. Manche wissen das aber nicht oder übersehen das und überweisen deshalb den Unkostenbeitrag nicht. Theoretisch könnte jeder jederzeit sein Guthaben selbst aufladen ohne eine Banküberweisung durchgeführt zu haben.
Einfacher wäre es, wenn nur Leute mit Administratorrechten auch das Guthaben für die Mitglieder nachladen können.

**Comment by mrothauer** [comment]
Dass Mitglieder das Guthaben selbst aufladen hat einen praktischen Hintergrund: Es kann dann sofort bestellt werden und man muss nicht auf ein Freischalten warten.
Die Guthaben-Eintragungen sollten von einem Superadmin regelmäßig auf Richtigkeit überprüft werden. Das passiert unter Homepage-Verwaltung / Finanzberichte.
Nähere Infos in der Doku: https://foodcoopshop.github.io/de/guthaben-system.html
Der Unkostenbeitrag wird am Besten als Produkt des Herstellers "Eure Foodcoop" bestellt. Hier wird das anhand eines Mitgliedsbeitrags detailliert erklärt. Automatisch gibts hierbei aber nichts.
https://foodcoopshop.github.io/de/tipps-und-tricks.html
Ich erlaube mir also, das Ticket zu schließen.
