### ISSUE TITLE
Option to manage supplier products by contact person

### ISSUE THREAD

**Issue by firerain-tgz** [foodcoopshop/foodcoopshop#358]
I'd like to add a feature so that contact person could manage products (add, remove, enable, disable, update, edit, etc) and supplier info but only of those suppliers he/she is bound to.

The best option would be to have a designated CUSTOMER_GROUP for contact persons. I know that I can add another CUSTOMER_GROUP in app_config but didn't manage to make proper changes in menu.ctp.

**Comment by mrothauer** [comment]
First of all I need to say, that the group `CUSTOMER_GROUP_MEMBER` is the only group that does not allow editing all manufacturers and products.
Either we chose your idea to create a new customer group `CUSTOMER_GROUP_CONTACT_PERSON` or by default all users with `CUSTOMER_GROUP_MEMBER` that are related to a manufacturer (contact person) can edit it's products and the manufacturer itself.
I would prefer the latter as it's easier to implement (no extra group needed).
The adaptions would be in menu.ctp (check if $appAuth->isMember() and is contact person) then show menu item manufacturer and products (with preset, unchangeable filter). and the isAuthorized method of productscontroller and manufacturerscontroller need to be adapted.
and then of course existing unit tests need to be adapted an new ones created.
good luck!

**Comment by mrothauer** [comment]
... maybe it's easier to just change the group of the user to `CUSTOMER_GROUP_ADMIN` - then he can edit all manufacturers and products.

**Comment by firerain-tgz** [comment]
Of course, it would be easier to change their group to admin, but i'd like to prevent contact persons from editing other things than just products.
I haven't found any method for "is contact person" and that is the main problem.
Thanks for advises. I'll try to find proper method and report back.

**Comment by mrothauer** [comment]
the method does not exist yet and needs to be implemented (in AppAuthComponent, check customer.manufactuers is not empty)

therefore this method in CustomersTable needs to be adapted:
```
    public function findAuth(\Cake\ORM\Query $query, array $options)
    {
        $query->where([
            'Customers.active' => APP_ON
        ]);
        $query->contain([
            'AddressCustomers'
        ]);
        return $query;
    }
```

It needs to contain as well "Manufacturers"
