### ISSUE TITLE
AP09: Cronjobs mit Ausfallsicherheit

### ISSUE THREAD

**Issue by k-pd** [foodcoopshop/foodcoopshop#36]
The existing cronjob system requires console access and is not very fail safe. My thoughts for discussion (in German again) will follow asap.

**Comment by k-pd** [comment]
**TL;DR**: Einzelnes Cronjob-Skript erledigt alle anfallenden Jobs aus der Datenbank. Ausfallsicher und wartungsfrei. Flexibel wie cron, zusätzlich in der Lage, verspätete Jobs nachzuholen und bald auszuführende etwas vorzuziehen. Vorbild: WordPress.

# Cronjobs
Zeitgesteuerte Ausführung ist ein heikles Thema, vor allem weil viele Webhoster das nicht umsonst anbieten. Aber man muss zum Glück nicht alles neu erfinden, sondern kann sich bei z.B. WordPress vieles zusammenholen.

## Aufrufmöglichkeiten
WordPress hatte lange Zeit keine (bzw. nur über Plugins) Möglichkeiten der zeitgesteuerten Ausführung von Tasks. So war es eben lange Zeit nicht möglich, Artikel automatisch während des Urlaubs zu veröffentlichen. Dann kam man auf die Idee, dies mit einem Skript zu erledigen, dass von wordpress.org aus getriggert wird. Ist natürlich traffic-intensiv und war bald wieder passé. Dafür kam dann der jetzige Trigger-Mechanismus: Mit jedem Seitenaufruf wird gecheckt, ob ein Zeitintervall vorüber ist und bei Bedarf dann das Cron-Skript im Hintergrund gestartet. Bei genug Traffic auf der Seite ist das zeitlich ausreichend genau (es kommt bei den Aufgaben selten auf eine exakte Zeit an). Zusätzlich wäre es möglich, für bekannt schwache Zeiten (z.B. nachts) einen einzigen Cronjob mittels wget die Homepage abrufen zu lassen.

## Datenbankgestützte Jobs
Dadurch das alle Jobs in der Datenbank liegen, können bereits vergangene, aber noch nicht erledigte Jobs erkannt und nachgeholt werden (z.B. nach einem Serverausfall oder einer Wartung). Die DB-basierten Jobs können auch über das (Super)Admin-Interface bearbeitet werden und werden so benutzerfreundlicher. Eine fertige Konfiguration kann mitgeliefert werden. Es können auch Jobs markiert werden, die nicht nachgeholt werden sollen oder auch bei Gelegenheit früher ausgeführt werden dürfen.

## Leichtes Nachinstallieren
Durch die automatische DB-Migration können neue Jobs mit dem Update automatisch eingebaut werden. Oder individuelle Jobs erstellte und hinzugefügt werden.

**Comment by mrothauer** [comment]
https://github.com/Cron/Cron looks good

**Comment by k-pd** [comment]
That library is far from being usefull (imho). It is not at all as required. It wants You to fill in all data with every start of the scheduled cron job. You would need to translate whatever configuration input You want to accept into the crontab format, store that somewhere and read it with every call of Your cronjob script. Then You need to track when Your script was called last and decide if there where some cronjobs skipped due to server outage. So basically all this library does for You is the date comparison during normal operations. That's nothing worth an additional library.
