### ISSUE TITLE
Urlaubsfunktion FoodCoop/allgemeine Lieferpause

### ISSUE THREAD

**Issue by veronimus** [foodcoopshop/foodcoopshop#360]
Manko der Urlaubsfunktion für die Gesamt-Foodcoop: wenn man die Bestellfunktion deaktiviert hat, laufen ja naturgemäß dennoch die Lieferrhythmen weiter. Somit werden unter "Bestellungen" entsprechende Produkte für nicht stattfindende Abholungen z.B. an Feiertagen angezeigt bzw. gehen ja auch automatisierte Erinnerungsmails raus. Besser wäre das Ganze überhaupt über eine Lieferpause, die für alle ProduzentInnen auswählbar ist, abzuwickeln.

**Comment by mrothauer** [comment]
Stimmt nicht ganz - seit ein paar Monaten wird beim Setzen der Lieferpause abgeprüft, ob für das Datum bereits Bestellungen vorliegen. Wenn das der Fall ist, dann müssen zuerst die Bestellungen storniert werden, dann kann die Lieferpause gespeichert werden. Ich hab ein anderes Issue erweitert.
see #80
