### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by TheFox** [foodcoopshop/foodcoopshop#368]
When I turn off the debug `'debug' => false` in the settings, the cache is not working anymore. I get 404 on all domain.tld/cache/ paths. Like `domain.tld/cache/frontend.css`.

**Comment by mrothauer** [comment]
you need to build your assets before turning debug to false.
bin/cake asset_compress build

**Comment by TheFox** [comment]
Works fine. I now run it right after `npm --prefix ./webroot install ./webroot`, in my deployment.

**Comment by mrothauer** [comment]
same here :-) maybe this file helps more
https://github.com/foodcoopshop/foodcoopshop/blob/41f483d64e7bca0ad5c8b50abf31e49be4027e85/.travis.yml#L34
