### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by TheFox** [foodcoopshop/foodcoopshop#369]
Regarding #347:

In <https://foodcoopshop.github.io/en/installation-details.html>, *Credentials* Section, `Copy credentials.default.php to credentials.php and change the configuration`, it was not clear to me, that I have to set `'EmailTransport' => [...]` three times. After I was reading #347 it was clear to me that I have to set all `'EmailTransport' => [...]` sections in `credentials.php` file. First in `custom_config.php` file and also two times in `credentials.php` file.

**Comment by mrothauer** [comment]
thank you. I fixed it in https://github.com/foodcoopshop/foodcoopshop.github.io/commit/c78839da25467343b061654fd202edbf7ca8ee4d

**Comment by TheFox** [comment]
But why even 3 times? Why? Is it not possible to reduce it to ONE? Even two times in one and the same file is crazy.

**Comment by mrothauer** [comment]
because the different configuration are used for different use cases. eg sending debug emails, test-emails and so on
