### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by TheFox** [foodcoopshop/foodcoopshop#370]
I installed it using `composer require foodcoopshop/foodcoopshop`. After that I also run `composer install` in `vendor/foodcoopshop/foodcoopshop`. Then npm in the same directories.

When I run `npm --prefix ./webroot install ./webroot ` I get the following error:

```
npm WARN lifecycle foodcoopshop@~install: cannot run in wd foodcoopshop@ bash ../bin/cake npm_post_install (wd=/app/vendor/foodcoopshop/foodcoopshop/webroot)
added 143 packages from 97 contributors and audited 215 packages in 5.091s
found 8 vulnerabilities (7 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 14d24ab3aedd
```

This is why then the fonts are not working.

**Comment by mrothauer** [comment]
try to install another branch, as v2.4 (latest stable) is 2 months old and I think that's why you get the vulnerability errors
the develop should be fine (but not 100% testet for production!) I use it already

**Comment by TheFox** [comment]
I'm not worried about the vulnerability errors.

The post hook is not working: `cannot run in wd foodcoopshop@ bash ../bin/cake npm_post_install (wd=/app/vendor/foodcoopshop/foodcoopshop/webroot)`

**Comment by mrothauer** [comment]
hmmm, maybe this helps?
https://stackoverflow.com/a/19132229/2100184

**Comment by TheFox** [comment]
Perfect. Works. Thank you very much for your help.

**Comment by mrothauer** [comment]
no problem
