### ISSUE TITLE
Dockerfile für Entwickler erstellen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#376]
Für ein einfaches Aufsetzen der Entwicklungsumgebung gedacht.

**Comment by mantensteiner** [comment]
Hier findest du mein Repository zu Docker (Swarm) und FCS: https://github.com/mantensteiner/foodcoopshop-docker

**Comment by SigiK** [comment]
mantensteiner <notifications@github.com> schrieb am So., 13. Okt. 2019,
12:07:

**Comment by mrothauer** [comment]
Das ist ja großartig! Könntest du einen PR erstellen, hab folgendes Repo grad angelegt?
https://github.com/foodcoopshop/foodcoopshop-docker
Dann hab ich dir auch noch eine Einladung zur Gruppe fcs-devs geschickt, sodass du direkt auf diesem Branch arbeiten kannst.
