### ISSUE TITLE
DebugKit JavaScript File missing

### ISSUE THREAD

**Issue by TheFox** [foodcoopshop/foodcoopshop#381]
When I run the shop in debug mode, I get 404 on `/debug_kit/js/toolbar.js` file. I also run Composer install with `--dev`. And rerun the npm install command, but still not working.

**Comment by mrothauer** [comment]
is the file physically existing?
/vendor/cakephp/debug_kit/webroot/js/toolbar.js
afaik --dev is not necessary, but with --no-dev you exclude dev dependencies, so just try without --dev
npm has nothing to do with debug_kit

**Comment by TheFox** [comment]
I also tried without --dev, but makes no difference.

**Comment by mrothauer** [comment]
sorry i am on holiday now until 26th

**Comment by mrothauer** [comment]
does that mean, the file /vendor/cakephp/debug_kit/webroot/js/toolbar.js does not exist?

**Comment by TheFox** [comment]
Sorry for the delay. The file was missing.

**Comment by mrothauer** [comment]
after `composer install` the dev-dependency "cakephp/debug_kit": "3.*" should be installed and the file should be there.
I can't help you debugging if this is not the case, sorry.
