### ISSUE TITLE
Auswählen von E-Mail-Adressen, bevor sie in die Zwischenablage kopiert werden

### ISSUE THREAD

**Issue by vmvbruck** [foodcoopshop/foodcoopshop#383]
Wenn Emailadressen in die Zwischenablage rauskopiert werden, wäre es super, wenn man die anhaken könnte und dann nur die ausgewählten rüberkopieren. Manchmal muss man ja selektieren, weil eine Benachrichtigung nicht alle betrifft.

**Comment by mrothauer** [comment]
https://github.com/foodcoopshop/foodcoopshop/commit/8836dfc66d01be55ebf3728301775ee1f65c9b85
