### ISSUE TITLE
Produkt-Feedback an ProduzentInnen

### ISSUE THREAD

**Issue by vmvbruck** [foodcoopshop/foodcoopshop#391]
Bei der Bestellliste könnte man eine weitere Spalte hinzufügen, sodass bei jedem Produkt ein Feedback an die ProduzentInnen ergänzt werden könnte - ähnlich wie der Stornier-Button: es geht dann ein Fenster auf, wo man Beanstandungen aber vor allem auch begeisterte Rückmeldungen der KonsumentInnen reinschreiben könnte - denn dieser bei den FoodCoops ja vielbeschworene direkte Austausch zwischen den EndkonsumentInnen und den ProduzentInnen ist de facto dann doch oft nicht so umittelbar gegeben. Und wer macht sich schon die Mühe und ruft an oder setzt sich separat hin, um ein E-Mail zu schreiben? Da wäre es praktisch, das im Zuge der Abholung direkt deponieren zu können.

https://www.foodcoopshop.com/crowdfunding-weiterentwicklung

**Comment by mrothauer** [comment]
Prinzipiell finde ich das eine gute Idee.

1) Technisch kann nicht über die E-Mail-Adresse des Mitglieds versendet werden, sondern nur über die der Foodcoop. Man könnte aber die E-Mail des Mitglieds im E-Mail-Text mitschicken, so dass der Produzent antworten kann.

2) Soll die Nachricht, die eingegeben wird, wirklich "nur" als E-Mail an den Produzenten versendet werden, oder evtl. auch für andere Mitglieder lesbar sein? Das ginge dann eher in Richtung "Bewertungssystem", wo man theoretisch auch negative Nachrichten schreiben kann. Die Nachricht könnte dann z. B. direkt beim beim Produkt (da, wo es bestellt werden kann) (für eingeloggte Mitglieder) angezeigt werden.

**Comment by vmvbruck** [comment]
Für mich würde echt nur die erste Lösungsmöglichkeit stimmig sein. Zweiteres mit den Bewertungen mutet etwas zu sehr wie bei amazon an. Die Sichtbarkeit für KonsumentInnen wäre nicht so wichtig - in diesem Kreis ist man ja noch am ehesten untereinander im Austausch. 

Mir wäre vorgeschwebt, die etwas vernachlässigte Verbindung zwischen KonsumentInnen / ProduzentInnen zu verbessern. 

Generell noch zur Diskussion: wie praktikabel wäre es überhaupt (artet es in eine E-Mail-Flut für ProduzentInnen aus? / ist es zu unpersönlich?)
