### ISSUE TITLE
Yunohost packaging and LDAP support

### ISSUE THREAD

**Issue by decentral1se** [foodcoopshop/foodcoopshop#393]
Das ist ein / This is a:

* [x] Vorschlag für neue Funktion / feature-discussion (RFC)

---

Hello, thanks for this nice software. I am considering to use it for a new food cooperative here in the Netherlands. 

I have started to use https://yunohost.org/ and the packaging system to arrange applications. I am considering packaging this application under Yunohost but I need to know if there is LDAP support already?

If not, would you consider supporting LDAP?

This allows for a seamless login experience across all the Yunohost applications.

**Comment by mrothauer** [comment]
Hi and thanks for your feature request!

Great that you want to create a Yunohost package for FoodCoopShop, I didn't know the project before. Sounds great!

LDAP authentification is not yet supported, but I am sure that it can be implemented rather easily:
Maybe this works? https://stackoverflow.com/questions/33721886/ldap-authentication-with-cakephp-3-x

If you want to translate the software into Dutch, please go ahead!
https://foodcoopshop.github.io/en/translating.html

Bye,
Mario

**Comment by decentral1se** [comment]
OK nice! 

I will discuss with the others from the coop and we will see about taking it further!

**Comment by mrothauer** [comment]
Ok. If you have questions, just ask.

**Comment by mrothauer** [comment]
Hi. Any progress so far? If not, can I help? Otherwise I would close the issue.

**Comment by decentral1se** [comment]
Hey, we decided to use https://foodcoops.net/ in the end, so let's close this for now.

Best of luck with the project :fireworks:
