### ISSUE TITLE
Lagerprodukt kann bei Sofortbestellung nicht bestellt werden

### ISSUE THREAD

**Issue by markuskoban** [foodcoopshop/foodcoopshop#394]
Die lagernden Produkte von einem Hersteller können im Sofortbestell-Modus nicht in den Warenkorb gelegt werden. Da kommt die Meldung, dass diese nicht mehr bestellt werden können, obwohl die Produkte als Lagerprodukte eingetragen sind und das Kontingent auf 999 gesetzt ist.

Einstellungen / Verwaltung: 
In der Sofort-Bestellung ausschließlich Lagerprodukte anzeigen? JA

Was habe ich da falsch konfiguriert?

![image](https://user-images.githubusercontent.com/47060814/61878333-1e499180-aef1-11e9-97be-5b0021783371.png)
![image](https://user-images.githubusercontent.com/47060814/61878390-31f4f800-aef1-11e9-974e-0fc53f0972aa.png)
****

**Comment by markuskoban** [comment]
in der aktuellen Release / FCS 2.5.3

**Comment by mrothauer** [comment]
Da ist was nicht ganz sauber, wenn das Produkt von "Individuelles Datum" direkt auf "Lagerprodukt" umgestellt wird. Bitte Hakerl bei "Lagerprodukt" weggeben, dann den Lieferrhythmus umstellen auf "wöchtentlich" und dann wieder "Lagerprodukt" anhakerln. Dann sollte es gehen. Ich werds bei Gelegenheit fixen und ein neues Release erstellen.
Danke fürs Bescheid sagen!

**Comment by mrothauer** [comment]
Der Bugfix ist nun fertig, die Tests laufen durch... Ich teste ihn noch beim Fairteiler und werde in den nächsten Tagen v2.5.4 releasen.
Danke für's Bescheid sagen.

**Comment by mrothauer** [comment]
v2.5.4 released
https://github.com/foodcoopshop/foodcoopshop/releases/tag/v2.5.4
lg,
mario
