### ISSUE TITLE
neue Produkte / unterschiedlicher Bestellschluss

### ISSUE THREAD

**Issue by markuskoban** [foodcoopshop/foodcoopshop#395]
Beim einem Hersteller wurde neue neue Produkt angelegt und als Bestellschluss gibt es jetzt nur Sonntag und Montag Mitternacht, obwohl alle anderen Produkte vom Hersteller bis Dienstag Mitternacht bestellt werden können. Jetzt wurden die neuen Produkte am Dienstag in der Früh verschickt und der Rest am Mittwoch in der Früh.

Wo muss ich die Config anpassen das ich beim Bestellschluss bei neu hinzugefügten Produkten auch wieder den Dienstag als Standard und Montag und Sonntag als Alternative einstellen kann? 

FCS 2.5.3

**Comment by mrothauer** [comment]
Ich vermute mal, ihr habt FCS_WEEKLY_PICKUP_DAY oder/und FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA in fcs_configuration geändert? Evtl. auch den Cronjob ChangeWeeklyPickupDayByOneDay verwendet? Irgendwas ist auf jeden Fall durcheinander gekommen.

Auszug aus eurer Config:
Wöchentlicher Abholtag | Freitag
Lagerprodukte in Rechnungen miteinbeziehen? | 1
Bestelllisten-Versand: x Tage vor dem Abholtag | 3 (Dienstag)

Als Default Bestellschluss ist Montag Mitternacht bei euch eingestellt.
Dh. das Anlegen neuer Produkte funkioniert wie es soll.

Wenn ihr auf Dienstag Mitternacht umstellen wollt, FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA um 1 erhöhen.

Evtl. dann noch das Tabellenfeld delivery_rhythm_send_order_list_weekday in fcs_product für bestimmte Produkte manuell ändern.

Lg,
Mario

PS: Alternative Bestellschlüsse gibts immer nur einen (und nicht zwei).

**Comment by mrothauer** [comment]
Achja, vielleicht kannst du genau anführen, wie es zu dem Problem kam und evtl. die Dokus ergänzen?

**Comment by markuskoban** [comment]
die Config passt genau wie Sie ist: Abholtag = Freitag, Bestellschluss = Dienstag (respektiver Versand der Listen Mittwoch ab 00:01)
![image](https://user-images.githubusercontent.com/47060814/61931596-55678380-af81-11e9-89d0-bc0b72dc6c32.png)

Mein Problem:
"Default Bestellschluss ist Montag Mitternacht" - das will ich auf Dienstag 
![image](https://user-images.githubusercontent.com/47060814/61931727-bf802880-af81-11e9-9df5-b78c107de9e5.png)

Wenn der Default Bestellschluss auf "3" gesetzt ist, ist doch Dienstag (Mitternacht) Bestellschluss.
Oder irre ich mich da?

**Comment by mrothauer** [comment]
Nein, Tag des Bestelllistenversands ergibt sich aus FCS_WEEKLY_PICKUP_DAY - FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA (vereinfacht; funktioniert auch für z.B. dienstag / sonntag siehe https://github.com/foodcoopshop/foodcoopshop/blob/649ada3d42bff75e3d13db2ef6a1ae5277f69b3f/src/View/Helper/MyTimeHelper.php#L117-L124)

Erhöhe mal FCS_DEFAULT_SEND_ORDER_LISTS_DAY_DELTA um 1, dann stimmts.

**Comment by markuskoban** [comment]
Jetzt habe ich es auch verstanden und es funktioniert! DANKE!

**Comment by mrothauer** [comment]
Super, bitte gerne.
