### ISSUE TITLE
Sucheingaben werden ungefiltert ausgegeben (XSS Lücke in Suchmaske)

### ISSUE THREAD

**Issue by tomgrassmann** [foodcoopshop/foodcoopshop#405]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)
* [x] Sicherheitslücke

* FoodCoopShop Version: 2.6.0
* Browser und Betriebssystem / Browser and Operating System: Firefox / Windows 10
* Platform and Target: -

### Was hast du gemacht? What you did?
https://demo-de.foodcoopshop.com/suche?keyword="><script>alert('XSS')</script>
Geöffnet mit Firefox

### Was ist passiert? What happened?
Eine JavaScript alert-box wird bei Aufruf geöffnet, d.h. Cross Site Scripting Lücke

### Was sollte passieren? What you expected to happen?
Der Inhalt des Parameters hätte als HTML Entities / escaped ausgegeben werden sollen.

**Comment by mrothauer** [comment]
Fixed and part of v2.6.1 - thank's for reporting!
