### ISSUE TITLE
Unable to order if first submit was without both required checkboxes

### ISSUE THREAD

**Issue by hasslerf** [foodcoopshop/foodcoopshop#411]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* Browser und Betriebssystem / Browser and Operating System: Firefox Quantum 69.0.1 (64-Bit) / Linux
* Platform and Target: genussfairteiler.at

### Was hast du gemacht? What you did?
When submitting an order one has to check two checkboxes. If I only check one and hit submit, an error will occur and I will not be able to submit, anywaay what or how many checkboxes one will check.

### Was ist passiert? What happened?
![2019-10-13 20-53](https://user-images.githubusercontent.com/2161446/66720392-38ae4f80-edfc-11e9-9f20-7963dbff05cb.gif)

### Was sollte passieren? What you expected to happen?
Expected the Submit-Button to be reactivated again.

**Comment by mrothauer** [comment]
Hallo, ja ich kann den Bug nachvollziehen (Firefox). Wärst du bereit, den Bug selbst zu fixen? Ich kann dir  natürlich dabei helfen falls du Fragen hast. Vermutlich reicht es, die clientseitige Validierung beim Formular abzudrehen (wird eh alles serverseitig validiert).

**Comment by hasslerf** [comment]
Ich hab gerade ein anderes privates Projekt laufen, werde aber versuchen das Problem einzutackten...

**Comment by hasslerf** [comment]
Thx, am Montag im Produktivbetrieb getestet.
