### ISSUE TITLE
Nullable Problem mit bestimmten Datenbank-Feldern

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#413]
* [x] Bug

* FoodCoopShop Version: 2.6.2 
* Getestet auf MacOS/Chrome
* DB Initialisierung: clean-db-structure.sql und clean-db-data-de_DE.sql
* Getestet auf 2 unabhängigen Installationen.

### Was hast du gemacht? What you did?
Blog Artikel erstellen (funktioniert), standardmäßig ist das Feld 'Hersteller' leer. Den erstellten Artikel anschließend zu bearbeiten schlägt fehl. Im Hintergrund kommt es zu einer Exception aufgrund eines DB-Constraint.

### Was ist passiert? What happened?
Aus Benutzersicht kommt es Fehler-Bildschirm.
LOG:
2019-10-16 19:26:32 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_manufacturer' cannot be null
#0 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(38): PDOStatement->execute(NULL)
....

### Was sollte passieren? What you expected to happen?
Artikel wird upgedated.

**Comment by mrothauer** [comment]
Welche MySQL-Version verwendest du?
Versuch mal:
SET GLOBAL sql_mode = "NO_ENGINE_SUBSTITUTION";

**Comment by mantensteiner** [comment]
Version: 5.7.27

Folgende sql_modes sind aktiv:
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by mrothauer** [comment]
eigentlich sollten die mysql-default-einstellungen nicht verändert werden müssen. bei den ci-tests funktionieren alle tests (und ich teste sehr viele komponenten ab) ohne den sql_mode zu ändern und ich glaube nicht, dass von 5.7.25 auf 5.7.27 dahingehend was geändert wurde.
see https://travis-ci.org/foodcoopshop/foodcoopshop/jobs/602683354 (mysql version in zeile 306)
und ob die fehlenden modes probleme bereiten kann ich dir leider nicht sagen.

**Comment by mantensteiner** [comment]
Ich hab mir die Modes nochmal genauer angesehen und getestet - das Problem ist STRICT_TRANS_TABLES. Wenn der aktiv ist, funktionieren aufgrund strengerer Regeln gewisse Dinge nicht mehr. Dieser Modus ist seit MySQL 5.7 per default aktiv - also sollte jede Neuinstallation das Problem haben.

Hast du bei deinen Tests ev. die DB schon länger in Verwendung bzw. hoch-migriert, sodass der Strict-Mode nicht aktiv ist?

**Comment by mrothauer** [comment]
Hallo,
danke für's Eingrenzen des Problems.
hmmm, im DB-Dump stehen ein paar Zeilen Code, von denen ich nicht genau weiß, was sie machen :-)
https://github.com/foodcoopshop/foodcoopshop/blob/ddebe84aae0fc42145b7a33e2415d2205ef37107/config/sql/_installation/clean-db-structure.sql#L2-L11
Aber auch hier wird STRICT_TRANS_TABLES nicht explizit gesetzt.
Bei Travis-CI wird die Structure einmal eingespielt und vor jedem Test test-db-data.sql neu eingetragen. Das ist alles, was bei Travis DB-technisch gemacht wird, alles Standard...
https://github.com/foodcoopshop/foodcoopshop/blob/ddebe84aae0fc42145b7a33e2415d2205ef37107/.travis.yml#L27-L29

**Comment by mantensteiner** [comment]
So wie ich das verstehe wird während das Script läuft temporär der sql_mode auf 'NO_AUTO_VALUE_ON_ZERO' gesetzt (Zeile 10), am wieder auf den ursprünglichen Mode (Zeile 589). 

Wäre interessant welche Konfiguration Travis per Default für die MySql-Serverinstanz verwendet, vielleicht kannst du das zum testen in .travis.yml vor Zeile 28 und nach Zeile 29 mal mit  "mysql -e 'SELECT @@SQL_MODE;'" abfragen und im Log prüfen?

**Comment by mrothauer** [comment]
https://github.com/foodcoopshop/foodcoopshop/tree/travis-sql-mode-test
https://travis-ci.org/foodcoopshop/foodcoopshop/jobs/603804050
kannst gern auf dem branch weiterarbeiten wenn du magst

```
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@SQL_MODE                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by mantensteiner** [comment]
Ich hab versucht auf die Schnelle eine Dev-Umgebung aufzusetzen, was bei mir (MacOS, VSCode) nicht klappt. Bin daher etwas eingeschränkt in meinen Möglichkeiten ;-)

Jedenfalls bin ich mir nicht sicher ob einer der vorhandenen Testcases in das Strict-Mode  Problem läuft. Ich hab einen Test _testBlogPostDetailChangeNullManufacturer_  hinzugefügt, hier kommt es dann zum von mir beschriebenen Fehler:

https://travis-ci.org/foodcoopshop/foodcoopshop/jobs/605940067

**Comment by mrothauer** [comment]
Es scheint, als ob du wirklich einen Bug entdeckt hättest! Magst du ihn selber fixen oder soll ich's machen? Ich würde dich auf jeden Fall supporten.

mit `bin/cake migrations create MigrationName` kannst du eine neue Migration anlegen, die die notwendigen SQL-Statements enthält, den Rest (Übernahme der Migration in die verschiedenen Dumps) kann ich gern machen.

Dann sind die Schritte 1-4 hier auszuführen:
https://github.com/foodcoopshop/foodcoopshop/blob/develop/devtools/db_dump_all

**Comment by mantensteiner** [comment]
Ich könnte es selber probieren - ich würde zumindest ein paar Tests hinzufügen (meine anderen, nun geschlossenen Bugs sind wohl auch ein Problem). Wie schon erwähnt hab ich derzeit keine PHP-Umgebung die debug-fähig ist, kann also ein paar Tage dauern...

Die Frage ist wie das gelöst werden soll. Eher Wert-Prüfungen/Validierungen/Korrekturen, sodass der Strict-Mode keine Fehler wirft oder den SQL Strict-Mode als Voraussetzung definieren und keine Änderungen im Server-Code?

**Comment by mrothauer** [comment]
Super. Ich würde das Problem eher von der Datenbank-Struktur-Ebene her angehen und als Default-Werte kein `null` zulassen.
Das gleich Problem mit anderen Feldern gabs schon mal - nur wenn neue Felder dazukommen und ich das nicht abteste, merke ich den Fehler nicht (weil ich noch nicht mit MySQL 5.7 arbeite)
https://github.com/foodcoopshop/foodcoopshop/pull/109/files
(Diff für Config/sql/_installation/clean-db-structure.sql) anschauen.

**Comment by mantensteiner** [comment]
Hab mir die DB-Struktur angesehen, die problematische Column ist ja bereits nicht-nullable - daher ja auch das Problem. Oder meintest du man soll `null` schon zulassen?
Derzeit: `CREATE TABLE 'fcs_blog_posts'  ... 'id_manufacturer' int(11) unsigned NOT NULL DEFAULT '0', ... `

Falls `null` nicht zulässig sein soll müsste die Lösung eher im Code/UI erfolgen, damit immer ein Default-Wert gesetzt ist bzw. eine Auswahl im UI verpflichtend ist, oder?

**Comment by mrothauer** [comment]
Ja, ich meinte natürlich "null zulassen"

**Comment by mantensteiner** [comment]
Ich glaub es ist doch besser wenn du dich um die Umsetzung kümmerst. Ich bekomme derzeit meine Dev-Umgebung nicht so hin, dass zB Cake zur Erstellung der Migration läuft oder ich generell PHP code debuggen kann.

Für die mir bekannten Probleme würde ich folgende Statements absetzen (hab ich direkt in einer Demo-Installation von mir erfolgreich getestet):

`ALTER TABLE 'fcs_blog_posts' CHANGE 'id_manufacturer' 'id_manufacturer' int(11) unsigned NULL;`

`ALTER TABLE 'fcs_category' CHANGE 'id_parent' 'id_parent' int(10) unsigned NULL;`

`ALTER TABLE 'fcs_sliders' CHANGE 'image' 'image' varchar(255) NULL;`

**Comment by mrothauer** [comment]
Kein Problem, deine SQL-Statements haben mir schon geholfen...
Hab deinen Commit mit dem Test, der fehlschlägt, auf einen anderen Branch gecherrypickt und die neue Migration mit reingenommen - läuft alles durch.
Würde dann in den nächsten Tagen mergen, falls von dir keine Einwände mehr kommen.
@see https://github.com/foodcoopshop/foodcoopshop/pull/428
