### ISSUE TITLE
Upload Slider-Image schlägt fehl

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#414]
* [x] Bug

* FoodCoopShop Version: 2.6.2
* MacOS/Chrome
* DB Initialisierung: clean-db-structure.sql und clean-db-data-de_DE.sql
* Getestet auf 2 unabhängigen Installationen.

### Was hast du gemacht? What you did?
Upload new Slider-Image.

### Was ist passiert? What happened?
Fehlerbildschirm. 
Error-Log: 
2019-10-16 19:20:47 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'image' doesn't have a default value
#0 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(38): PDOStatement->execute(NULL)

### Was sollte passieren? What you expected to happen?
Bild wird hochgeladen.

**Comment by mrothauer** [comment]
see #413
