### ISSUE TITLE
Update einer Kategorie schlägt fehl

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#415]
* [x] Bug

* FoodCoopShop Version: 2.6.2
* Getestet auf MacOS/Chrome
* DB Initialisierung: clean-db-structure.sql und clean-db-data-de_DE.sql
* Getestet auf 2 unabhängigen Installationen.

### Was hast du gemacht? What you did?
Existierende Kategorie öffnen und ändern.

### Was ist passiert? What happened?
Fehlerbildschirm.
Error-Log:
2019-10-16 19:23:29 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_parent' cannot be null
#0 /var/www/foodcoopshop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(38): PDOStatement->execute(NULL)

### Was sollte passieren? What you expected to happen?
Kategorie wird gespeichert.

**Comment by mrothauer** [comment]
see #413
