### ISSUE TITLE
Network Module Documentation - Link broken

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#417]
This link in Readme.md (/plugins/Network) does not work: https://foodcoopshop.github.io/en/installation-network-plugin

I am currently in need for documentation on how the Network-Module works technically and how to install/activate it. Do I even need to install it, if our instance of the application is only used as Remote (Slave)-FoodCoop?

**Comment by mrothauer** [comment]
you can delete the link, it's obsolte. the network plugin used to be an extra repository - now its a plugin that's part of the core.
it's deactivated as default, to use it (as master- or remote/slave foodcoop), you need to activate it in the settings.
default-value: https://github.com/foodcoopshop/foodcoopshop/blob/5accc314659cc44992e9f1dd1dcc4b5f2f186590/config/sql/_installation/clean-db-data-de_DE.sql#L107

**Comment by mrothauer** [comment]
fyi: I just updated the docs
https://github.com/foodcoopshop/foodcoopshop.github.io/commit/8ae9de5a0e8b5c9c30d23c14c55cf1be14164a21
https://github.com/foodcoopshop/foodcoopshop/commit/ddebe84aae0fc42145b7a33e2415d2205ef37107
