### ISSUE TITLE
Selbstbedienungsmodus lässt sich nicht aktivieren (2.6.2)

### ISSUE THREAD

**Issue by entfrickler** [foodcoopshop/foodcoopshop#420]
Das ist ein (mehrere Antworten möglich)

* [x] Bug

* FoodCoopShop Version: 2.6.2
* Browser und Betriebssystem: 69.0.1 (64-bit) / Ubuntu 16.04
* Platform and Target: php 7.3 

### Was hast du gemacht?
`UPDATE `fcs_configuration` SET `value` = '1' WHERE `fcs_configuration`.`name` = 'FCS_SELF_SERVICE_MODE_FOR_STOCK_PRODUCTS_ENABLED';`
Admin-Bereich / Einstellungen: Sollen Lagerprodukte mit der wöchentlichen Bestellung bestellt werden können? auf nein gesetzt
Ich habe ein Lagerprodukt inklusive Bestand angelegt.

### Was ist passiert?
Nichts.

### Was sollte passieren?
 Ich hätte erwartet dass es jetzt möglich ist im Selbstbedienungsmodus ein zu kaufen.

Laut der Doku soll die Funktion ab Version 2.5 zum testen verfügbar sein. Was hab ich falsch gemacht? Ich habe aktuell noch keine cronjobs aktiviert. Was mich auch gewunder hat. In der Doku von 2.6 steht dass es der Super Admin im Menü aktivieren kann. Ich musste es aber in der DB machen. Installiert habe ich folgendes zip https://github.com/foodcoopshop/foodcoopshop/releases/download/v2.6.2/FoodCoopShop-v2.6.2.zip

**Comment by mrothauer** [comment]
Hallo,
der Selbstbedienungs-Modus ist leider noch nicht fertig.
Wenn du (auf eigene Gefahr) testen möchtest, musst du zusätzlich zur Datenbank-Config
https://github.com/foodcoopshop/foodcoopshop/blob/25b001a37171824179090275a2be05e562ce6f43/config/app_config.php#L104
auf true setzen. Dann siehst du einen Link in der Navi wie auf https://demo-de.foodcoopshop.com/
Idealerweise überschreibst du die Config in custom_config.php
Oder aber du rufst /selbstbedienung direkt im über die Url auf.

**Comment by entfrickler** [comment]
Ok, danke für die schnelle Antwort. Das hat funktioniert.
Wir testen den Shop gerade und da wir eine LagerCoop sind können wir ihn erst einsetzen wenn der Selbstbedienungsmodus funktioniert.

Ist der aktuelle master Branch da schon ein wenig weiter als V 2.6.2? Dann würde ich den mal installieren und Bugs melden die mir auffallen. In der aktuellen Version bei meinem Test gerade habe ich 11 Kilo Getreide gekauft wovon 2*10kilo im Lager eingebucht waren. Aber die restlichen 9 Kilo konnten danach nicht mehr gekauft werden weil die Anzahl auf 0 ging.

Wie hoch ist denn die Priorität dieser Funktion bzw. klappt es noch dass sie im 2.7er Release dieses Jahr noch einsatzbereit wird? Wir würden auf jeden Fall auch aktiv die Funktionen testen und Bugs melden. Da wir am 10.11. unsere Mitgliederversammlung haben wo wir den Umstieg auf ein neues System beschließen wollen wäre es gut zu wissen ob der FoodCoopShop in Zukunft für uns passt.

**Comment by mrothauer** [comment]
Bitte gerne.

Der master-branch ist immer gleich mit dem letzten Release, im aktuellen Fall also v2.6.2.
Der develop-branch "sammelt" commits bis zum nächsten Release. Den develop-branch kannst du installieren, der läuft danke der vielen Tests auch schon auf Live-Systemen.

Zu deiner Fehler-Beschreibung: Das kann die Software noch nicht, es gibt auch schon ein Issue dazu:
#336 

Der Selbstbedienungs-Modus hätte eigentlich schon Anfang Sommer released werden sollen, ich bin da aber auf Feedback der testenden Foodcoop angewiesen und da kommt gerade wenig. Aber es werden nur noch Bugs bereinigt, im Wesentlichen ist das Ding fertig. Und wenns ganz fertig ist, werde ich auch die Online-Doku updaten und schön mit Screenshots versehen.

Lg,
Mario

**Comment by entfrickler** [comment]
Super, jetzt sieht das doch schon wieder gut aus.

Vielleicht nimmste das noch in die https://github.com/foodcoopshop/foodcoopshop/blob/develop/README.md mit auf damit so Laien wie ich da nicht drüber stolpern.

**Comment by entfrickler** [comment]
Ok, ich dachte ich mach das mal eben schnell ;D War wohl nix, aber zumindest hab ich es jetzt am laufen. Das die Skripte eine DB Verbindung brauchen hat mich nochmal bisschen zurück geworfen.

Jetzt testen wir den developement Brach! Aber der Bug #336 ist schon recht unpraktisch. Kannst du schon abschätzen wann du dazu kommt das zu fixen oder ist das eine größere Sache?

**Comment by entfrickler** [comment]
Ja, wenn ich dazu komme werde ich die Doku erweitern!

Zu dem Feature #336 Das ist für uns essenziell um den Shop in betrieb zu nehmen denke ich. Wir haben in unserer aktuellen Lösung gerade das Problem das viele Sachen nur Halb funktionieren oder über Workarounds. Das führt dann dazu dass diejenigen die Lagerbestand pflegen einen erheblichen Mehraufwand haben und viele Fehlbuchungen korrigiert werden müssen. Davon wollen wir weg. 

Kannst du für deine Kosten eine grobe Hausnummer nennen? Dann kann ich auf unserer Mitgliederversammlung nächste Woche fragen ob Geld da ist. Eventuell gibt es andere interessierte LagerCoops und man könnte ein Funding starten. Denn die meisten Lösungen (wie FoodSoft) sind aktuell auf BestellCoops optimiert. Bzw. wir haben bis jetzt kein perfektes Tool für LagerCoops gefunden.

**Comment by mrothauer** [comment]
schick mir eine email an office@foodcoopshop.com bitte
lg,
mario
