### ISSUE TITLE
Nicht abgeholte Produkte auf einen Klick / Blick

### ISSUE THREAD

**Issue by vmvbruck** [foodcoopshop/foodcoopshop#429]
Für den Shopdiensthabenden wäre übersichtlich, wenn man mit einem Klick sehen könnte, welche Produkte erst noch abgeholt werden: Sonst muss man bei allen, die an diesem Tag noch nicht abgeholt haben einzeln reinschauen. Vielleicht oben zu den Filtern eine Checkbox dazu"Nur nicht abgeholte Produkte anzeigen"...

**Comment by mrothauer** [comment]
Momentan kann man nur angeben, dass alle Produkte an einem bestimmten Tag abgeholt wurden oder eben nicht. Das müsste man umbauen. Z.B. so, dass die Hakerl links vom Produkt gespeichert bleiben. Viele verwenden diese Hakerl eh schon beim Kontrollieren des Kisterls.
