### ISSUE TITLE
Problem mit OrderBy bei "Guthaben und Pfand-Saldo"

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#432]
* [x] Bug
* FoodCoopShop Version: 2.6.2.
* Platform and Target: MySql 5.7.28

### Was hast du gemacht? What you did?
Finanzberichte als Superadmin, dann auf "Guthaben und Pfand-Saldo"

### Was ist passiert? What happened?
Fehlerbildschirm

### Log
Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'foodcoopshop_db.OrderDetails.id_order_detail' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SQL_MODE „ONLY_FULL_GROUP_BY“ war aktiv (Info zu Defaults seit 5.7 https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html).

### Workaround
SQL-Mode ONLY_FULL_GROUP_BY entfernen.

SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

**Comment by mrothauer** [comment]
Danke für's Bescheid-Sagen. Werde bei Gelegenheit den SQL-Mode meiner lokalen Installation auf die MySQL-5.7 Defaults einstellen.
Sollte jetzt funktionieren (see #433) und kommt in v2.7 mit rein.
