### ISSUE TITLE
fixes for php 7.1

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#44]
foodcoopshop does not run on php 7.1

PHP 7.1 Fatal error: [] operator not supported for strings

customer.php constructor
        $this->hasMany['PaidCashFreeOrders']['conditions'][] = 'PaidCashFreeOrders.current_state IN (' . ORDER_STATE_CASH_FREE . ', ' . ORDER_STATE_OPEN . ')';

maybe there are other problems too, please run all tests on php7.1

**Comment by k-pd** [comment]
No PHP7.1 here, all < 5.6.

**Comment by mrothauer** [comment]
#48
