### ISSUE TITLE
Sofortbestellung/Selbstbedienungsmodus bei aktiver Lieferpause funktioniert nicht

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#441]
* [x] Bug
* FoodCoopShop Version: 2.7.0.

Wenn für den aktuellen Bestellzeitraum eine Lieferpause aktiv ist (zB für den 27.12. sind ab 18.12. keine normalen Bestellungen mehr möglich), können auch keine Lagerprodukte bestellt werden.

### Was ist passiert? What happened?
Produkte zur Sofortabholung können nicht in den Warenkorb gelegt werden. Fehlermeldung am Client: "FOODCOOP hat die Lieferpause aktiviert und das Produkt XY ist nicht mehr bestellbar."

### Was sollte passieren? What you expected to happen?
Normaler Sofortabholungs-Einkauf mit dem heutigen Datum.

**Comment by mrothauer** [comment]
Hallo, meinst du die Sofort-Bestellung oder der neue Selbstbedienungs-Modus? Oder beides?

**Comment by mantensteiner** [comment]
Habe beides ausprobiert-mit dem selben Ergebnis.

**Comment by mrothauer** [comment]
Ok, das ist in der Tat ein Bug. Ich hab nur getestet, ob die Produkte angezeigt werden, jedoch nicht, ob sie auch in den Warenkorb gelegt werden können.
Danke, das hat mir einen unangenehmen Freitag erspart (da hätte das Telefon oft geläutet...). Ich werde es morgen vormittag fixen.
Lg,
Mario

**Comment by mantensteiner** [comment]
Bitte gerne-solche (Frei)Tage gilt es zu vermeiden :)
Lg,
Michael

**Comment by mrothauer** [comment]
sollte nun gefixt sein
https://github.com/foodcoopshop/foodcoopshop/releases/download/v2.7.1/FoodCoopShop-v2.7.1.zip
