### ISSUE TITLE
Seeking help/guidance on installation

### ISSUE THREAD

**Issue by echoleaf** [foodcoopshop/foodcoopshop#466]
* FoodCoopShop Version: MASTER
* Browser und Betriebssystem / Browser and Operating System: FIREFOX 64 73.0 / Windows 10
* Platform and Target: Apache web server with mod_rewrite; PHP 7.3, mysql 5.6; hosts around 30 wordpress sites

### Was hast du gemacht? What you did?
I have not used SSH much so I tried installing via cPanel:
- downloaded the MASTER zip
- extracted zip into root folder of domain, and moved files from /foodcoopshop to the root folder
- I don't know how to set the document root but I added the domain to cpanel and the files are in the root folder associated with the domain
- did not do anything with virtual hosts, I usually don't have to do anything with that
- asked my host (I have a managed VPS) to install Node.js & npm
- chmod permissions for all folders are 755 (I'm researching what 'chmod -R a+w' translates to as a number)
- edited custom_config.default.php and renamed it custom_config.php (I edited the EmailTransport & Datasources sections, using 'localhost' for the host and submitting the details for the email & database connections)
- created the database, imported the initial structure & the initial data
- edited credentials.default.php and renamed it credentials.php (added admin emails, password and edited Emailtransport twice)

### Was ist passiert? What happened?
When I go to the domain (which I don't want to post publicly, all I see currently is the file structure. It does not appear to be connected to the database.

### Was sollte passieren? What you expected to happen?
I was hoping to see the default site. Maybe until node.js etc is installed it won't do anything? Once it's installed & running we are ok with learning how to use it via trial & error.

Thank you, Mario.

**Comment by mrothauer** [comment]
1) Please use the version you can download here: https://www.foodcoopshop.com/download/ (2.7.1) - it already contains all the vendors and you do not need nodejs or npm installed. It's recommended that you upload it as a zip file and unzip it on the server.

2) I can't help you with setting the document root, but it definitely needs to point to /webroot. Maybe your provider can help you with that.

3) If you follow the [installation guide](https://foodcoopshop.github.io/en/installation-guide.html) and still have questions, feel free to ask.

**Comment by echoleaf** [comment]
Thanks. I deleted the files and replaced them with the 2.7.1 version. I edited custom_config.php & credentials.php and changed the document root for the domain to the /webroot folder. Now instead of the seeing the folder list, I see a blank page (and the page source is blank too).

Would I be correct that custom_config.php is most important for connecting to the database? I have 'host' set to 'localhost' and 'cakeServerName' to 'https://mydomain.com.' What would you suggest testing to see if the connections work?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mrothauer** [comment]
> Would I be correct that custom_config.php is most important for connecting to the database?

absolutely

> I have 'host' set to 'localhost' 

ask your provider about the database login data (host, database name, username, password)

> and 'cakeServerName' to 'https://mydomain.com.'

thats good

> What would you suggest testing to see if the connections work?

please check logs/error.log and logs/debug.log

**Comment by echoleaf** [comment]
My host suggested 127.0.0.1 for Host and that did not change anything. I made the database and I know that the credentials are all correct.

/logs is empty except for a '.gitignore' file.

I did find an errorlog in /webroot and this is what it said:

> [20-Feb-2020 19:47:22 UTC] PHP Fatal error:  You must enable the intl extension to use CakePHP.
> in /home/myaccount/public_html/domain.com/config/requirements.php on line 31

What is the 'intl' extension?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mrothauer** [comment]
ah ok. it's a php extension that needs to be installed on the server. ask your provider to install that.

INTL_ICU_VERSION needs to be > than 50.1

**Comment by echoleaf** [comment]
OK - intl was enabled, and I added the SALT thing to the config file and the app is now loading at the domain - hooray for progress!

I'm at Create the valid Super Admin account now. I registered with my email, made the edits to the fcs_customer table in the db. I went to /request-new-password and entered my email address and I'm getting the error message An Internal Error Has Occurred.

Is this due to a problem with the email configuration? Because I do not get a new password email - and when I go to /admin/configurations/sendTestEmail. it just says Access denied, please sign in - except I don't have a sign in yet.

**Comment by echoleaf** [comment]
What does this error mean:

> 2020-02-20 21:36:33 Error: [BadMethodCallException] From is not specified.

Is that this setting in custom_config.php

> 'Email' => [
>         'default' => [
>             'from' => [],
>         ]
>     ],

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mrothauer** [comment]
great that you made progress and yes, you need to configure a valid email config.
see https://book.cakephp.org/4/en/core-libraries/email.html#configuring-transports

**Comment by echoleaf** [comment]
Great - does this error mean it's an issue with the email transport settings or something else?

> 2020-02-20 21:44:37 Error: [Cake\Network\Exception\SocketException] php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by mrothauer** [comment]
yes, the "from" field is empty. its needed for sending the email.

'default' => [
     'from' => [],
]

**Comment by mrothauer** [comment]
actually not with the EmailTransport but with the "Email" setting (the one you posted)

**Comment by echoleaf** [comment]
I got the email config working, received my password, logged into FoodCoopShop, changed my password and then copied it to credentials.php!

Am I done with installation then?

**Comment by mrothauer** [comment]
almost
https://foodcoopshop.github.io/en/cronjobs
but then you're done

**Comment by echoleaf** [comment]
Great, I just set up a 10 minute cron job for mydomain.com/cron

Is there any documentation on using FoodCoopShop? And to add other admins do I have them create an account under /sign-in and then change them to admin in the Database or in the FCS?

**Comment by mrothauer** [comment]
Excellent!
There is a good German Documentation - Please use Google Translate or a similar service to translate it. It's too much work for me to keep both up to date.
https://foodcoopshop.github.io/de/
You can change new users in the admin panel / members
I need to go to bed now! Good night!

**Comment by echoleaf** [comment]
Thank you so much Mario, I appreciate all of your help!

**Comment by mrothauer** [comment]
You're welcome! Good luck and if you want to please pass me the domain of your initiative. I would like to share it on my blog foodcoopshop.com that the software is used in the U.S. Of course only if you want.

**Comment by echoleaf** [comment]
Hi Mario - our domain is https://petalpatch727.com/

We're still trying to figure out how everything works, including styling it.

Is there a way to take the 10% fee that's added to everything and have it calculated on the total instead? Or is it designed to allow for different fees for different products?

Also, do you have any option or plans to add payment via Paypal?

**Comment by echoleaf** [comment]
Also, we noticed that the order emails & PDFs don't include the 10%. We're guessing we missed a setting? Because it wouldn't make sense to not inform customers of the fee.

**Comment by mrothauer** [comment]
Hi,

styling: you can override the app.customFrontendColorTheme in your custom_config.php

variable member fee: it can be defined globally in the fcs_configuration table and then you can override it for every manufacturer (manufacturer settings). so all products of a manufacturer need to have the same fee.

the prices need to already include the fee. only in the invoices the x% difference is visible and the manufacturer sees that he sold eg. products for 110 €, but he will be paid only 100 €. so the fee is not "added" but "subtracted" from the given price.

https://foodcoopshop.github.io/de/hersteller.html explains this - the automatic translation might be hard to read though, sorry for that.

if the variable member is enabled globally, customers are informed that the prices contain a variable member fee, but not how much.

paypal payment is not planned, its not necessary for our foodcoop workflow. but in a few months there will be an import function for exported bank transactions so that the members do not need to add their payment manually into the software.
https://foodcoopshop.github.io/de/guthaben-system-mit-automatischem-kontoabgleich

**Comment by echoleaf** [comment]
Hi Mario! Quick question: is it possible to turn ordering off & on? The issue we're having is people ordering while we are updating the inventory. I imagine this is a common issue so apologies if we've overlooked an abvious setting.

thanks,

Arp

www.Quackatoa.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by echoleaf** [comment]
Thank you!

www.Quackatoa.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
