### ISSUE TITLE
Cannot login with super admin account

### ISSUE THREAD

**Issue by ocapito** [foodcoopshop/foodcoopshop#476]
Hi there!
Following the other issue on this software I hope it's allright to pose a question here. Thanks anyways for the great work you are providing, we are hoping to get a foodccop running here soon, first steps are being made already this software seems to be exactly what we need now.

Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [?] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)
* [x] Question

* FoodCoopShop Version: v2.7.1. (german language database-set)
* Browser und Betriebssystem / Browser and Operating System: Firefox 74.0, Mac OsX 10.11.6
* Platform and Target: webserver apache on php 7.3.11, DATABASE Server Type MySQL Version 5.7.28

### Was hast du gemacht? What you did?
EXPLAIN WHAT YOU DID.
-I followede the Instructions of the installation guide up until creating the super admin account. (Only for setting up the sofware no development.)
- I created a user account with an email adress (the same adress that i put into the custom_config and the credentials file).
- I changed the id_default_group and the active status in the database (fsc_customer)
- I went to the forgotten password page put in the mail adress and recieved the email with a password and the link to activate the password
- clicked the activation link (this opened the login interface of my webserver, I'm not sure if this is correct??, and in the database a activation_new_password_code appeard for this user so something worked when following the link) 

### Was ist passiert? What happened?
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.
- when i try to login with this mail adress there is an error message "Anmelden ist fehlgeschlagen. Vielleicht ist dein Konto noch nicht aktiviert oder das Passwort stimmt nicht?"
- tried again with sending new password, same problem.
- deleted entries from the database and registered again with same mail adress, then password forgotten ... same problem
- registered with second mail adress ... same problem

### Was sollte passieren? What you expected to happen?
EXPLAIN WHAT IS TO BE EXPECTED, HERE.
- should have been able to login as a super admin

Bevor du das Issue erstellst, überprüfe bitte, ob es bereits ein ähnliches gibt.
Before you open an issue, please check if a similar issue already exists or has been closed before.
The existing issue already helped my with a problem that I was stuck with earlyer in the process (had not entered an email-adress in the from part in the config files)

**Comment by mrothauer** [comment]
hi,
most likely you forgot to set the configuration: "app.cakeServerName" in your custom_config.php
this needs to be set to your virtual host / domain. I updated the installation guide to make that clearer.
that's why the link in your activation email **did not work**. the activation_new_password_code was set when you typed in your email address to get a new password.
good luck!
ps: if you want to please tell me who you are and where you plan to set up your project. on github or to office@foodcoopshop.com

**Comment by ocapito** [comment]
Hi Thanks for the quick answer. It's a bit embarrasing but I already found out the problem was

- the http://www. in the link to activate the password.

When copying the link without this, everything worked fine. Sorry for the fuzz.
