### ISSUE TITLE
Schnittstelle für externe Systeme

### ISSUE THREAD

**Issue by geraldaistleitner** [foodcoopshop/foodcoopshop#502]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [] Bug
* [x] Verbesserungsvorschlag / enhancement
* [x] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: all
* Browser und Betriebssystem / Browser and Operating System: n/a
* Platform and Target: API

### Was hast du gemacht? What you did?
ERP für einen Betrieb eingeführt und versucht die Bestellungen aus den FoodCoopShops automatisiert ins System zu übertragen.

### Was ist passiert? What happened?
Leider gibt es diese Möglichkeit noch nicht.

### Was sollte passieren? What you expected to happen?
Perfekt wäre eine Schnittstelle (REST oder ähnliches) für Hersteller mittels derer diese ihre Daten im System warten können:
- Produkte und deren Daten (mittels externer ID aus Fremdsystem)
- Abholung der Bestellungen
- Ändern der Preise in den Bestellungen auf tatsächliche Werte

Würde mich gerne auch anbieten hier helfend zur Seite zu stehen.

**Comment by mrothauer** [comment]
Hallo Gerald,

so eine Schnittstelle wäre natürlich super. Es gibt schon eine API, die vom Netzwerk-Modul verwendet wird, allerdings ist das nicht als REST implementiert.

Hersteller können über diese API und Basic-Authentication (nur über HTTPS!) bereits jetzt Produkt-Daten abgleichen (der erste Punkt deiner Liste). Du könntest die gleiche Schnittstelle von deinem Fremd-System verwenden. Achtung: Nur mit Hersteller-Credentials möglich!

Die beiden anderen Punkte (Abholung der Bestellungen / Ändern der Preise) sind noch nicht implementiert.

Schau dir das mal an https://foodcoopshop.github.io/de/netzwerk-modul.html

Diese Methode hier
https://github.com/foodcoopshop/foodcoopshop/blob/62e6b8835a398e1353db2b1d7bafc8bba70a2e38/plugins/Network/src/Controller/ApiController.php#L113
könntest du bereits jetzt verwenden - oder dich daran orientieren.

Ich würde mich auch gerne anbieten, helfend zur Seite zu stehen :-)
