### ISSUE TITLE
Fail to sign out 

### ISSUE THREAD

**Issue by swoichha** [foodcoopshop/foodcoopshop#509]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: GENAUE VERSIONSNUMMER / EXACT RELEASE VERSION.
* Browser und Betriebssystem / Browser and Operating System: EG FIREFOX 64 / Windows 10
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### Was hast du gemacht? What you did?
- Follow the setup instruction as mentioned in https://foodcoopshop.github.io/en/installation-guide.html
- Create and login admin/user
- Click on `Sign out` button 

### Was ist passiert? What happened?
User was not able to sign out. 

### Was sollte passieren? What you expected to happen?
User should be signed out.

### ScreenShot of error message in console
![Screenshot from 2020-04-28 16-16-00](https://user-images.githubusercontent.com/17021686/80477583-e97cd600-896b-11ea-878f-66540346e3e1.png)

### Configuration
- Foodcoopshop: Current develop branch (3.1.0)
- Operating System: Ubuntu 18.04.4 LTS
- Browser:  Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)
- PHP 7.4.5 
- MySQL 5.7.29

**Comment by mrothauer** [comment]
please tell me your foodcoopshop version (version.txt)

**Comment by mrothauer** [comment]
I just updated https://demo-en.foodcoopshop.com/ with the current develop branch, everything working fine there.

You could try to pull the latest commits from develop (maybe there was an error in the codebase when you last pulled develop and which is fixed now) and try again.

Or - more likely - something is not configured correctly.

Your error tells me, that the foodcoopshop.LocalizedJs object is undefined. this object is dyamically generated by LocalizedController. Maybe the error is due to a wrong PHP intl extension?

Does https://demo-en.foodcoopshop.com/js/localized-javascript.js return the same as on your domain?

Would you mind telling me some details about your initiative? It's always interesting for me who works with FoodCoopShop.

**Comment by individual-it** [comment]
Hi @mrothauer 
I'm leading the team @swoichha is working for (@JankariTech - www.jankaritech.com ) 

Our company focus is test-automation and we saw that you have [test-related issues open](https://github.com/foodcoopshop/foodcoopshop/issues?q=is%3Aissue+is%3Aopen+label%3Atests), so we thought to see if we can get involved.
Contributing to FOSS projects is part of our vision as company, but we also using these contribution to learn from other projects, gain more experience and to get known to the FOSS community.

**Comment by mrothauer** [comment]
Hi @individual-it 

thanks for the info and your help. If you want, you can work on issue https://github.com/foodcoopshop/foodcoopshop/issues/404

I updated it just now. Please read through it and tell me, if you want to work on it or not. I think the issue would be fine for you as it does not require to deeply know the software and it's business logic itself.

The other test issue https://github.com/foodcoopshop/foodcoopshop/issues/435 is harder to resolve if one does not know the software.

**Comment by individual-it** [comment]
@mrothauer yes the installation works now, @swoichha first tried to run it with the php-dev-server, and you have been right, somehow generating the localisation js did not work in that case, then we switched over to Apache, that also had issues when we ran it in a subfolder below apache `DocumentRoot`
After setting apache `DocumentRoot`, to the root of foodcoopshop it works. 
@swoichha will now dig into your test-environment

@swoichha please close this issue, I have no permissions to do that

**Comment by mrothauer** [comment]
Cool that everything works now and thanks for sharing the problem solving!

> After setting apache DocumentRoot, to the root of foodcoopshop it works.
DocumentRoot should point to /webroot

> @swoichha will now dig into your test-environment
Happy digging!
