### ISSUE TITLE
Kategorieauswahl - Produktliste unterhalb von "Aktuelles"

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#510]
* [x] Verbesserungsvorschlag / enhancement
* FoodCoopShop Version: 3.0.2

Feedback von einem unserer User:
Nach Auswahl einer _Kategorie_ auf der Startseite werden die Produkte zwar angezeigt, jedoch unterhalb vom Bereich "Aktuelles", sodass man scrollen muss um zu den Produkten zu gelangen.

Lösung: "Aktuelles" innerhalb einer Kategorie ev. ausblenden.

**Comment by mrothauer** [comment]
Das ist erwünscht. So kann man sichergehen, dass zumindest die letzten drei Blog-Artikel beim Bestellen gesehen werden (z.B. Ausschreibungen zu Sitzungen).

**Comment by mantensteiner** [comment]
Ok, ich werde das so weitergeben - ist ja sehr unkritisch.

Mein Feedback aus Usability-Sicht wäre auch eher ausblenden. Vlt. bekommst du zukünftig ja noch mehr Rückmeldungen.

**Comment by mrothauer** [comment]
Ok, ich schau mal ob mehr Feedback kommt. Danke auf jeden Fall für dein Feedback!
