### ISSUE TITLE
Column not found: 1054 Unknown column 'ProductShops.created' in 'where clause'

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#518]
This is a 

* [x] Bug

* FoodCoopShop Version: v2.0.0
* Browser: Firefox 76.0 / Arch Linux
* Platform and Target: Arch Linux, nginx, MariaDB. 

### Was hast du gemacht? What you did?
I upgraded from 1.5 to 2.0. Then I logged in and receive the error page.

### Was ist passiert? What happened?
Error page appeared and after some investigation I found that error:
`Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ProductShops.created' in 'where clause'
Request URL: /
Stack Trace:
#0 /srv/http/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(Array)
#1 /srv/http/src/Model/Table/CategoriesTable.php(156): Cake\Database\Statement\MysqlStatement->execute(Array)
#2 /srv/http/src/Controller/FrontendController.php(120): App\Model\Table\CategoriesTable->getProductsByCategoryId(20, true, '', 0, true)
#3 /srv/http/vendor/cakephp/cakephp/src/Event/EventManager.php(416): App\Controller\FrontendController->beforeRender(Object(Cake\Event\Event))
#4 /srv/http/vendor/cakephp/cakephp/src/Event/EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#5 /srv/http/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#6 /srv/http/vendor/cakephp/cakephp/src/Controller/Controller.php(610): Cake\Controller\Controller->dispatchEvent('Controller.befo...')
#7 /srv/http/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(125): Cake\Controller\Controller->render()
#8 /srv/http/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#9 /srv/http/vendor/cakephp/cakephp/src/Http/BaseApplication.php(108): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /srv/http/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /srv/http/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /srv/http/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /srv/http/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /srv/http/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /srv/http/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php(50): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /srv/http/vendor/cakephp/cakephp/src/Http/Runner.php(65): AssetCompress\Middleware\AssetCompressMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /srv/http/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /srv/http/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /srv/http/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /srv/http/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 /srv/http/webroot/index.php(40): Cake\Http\Server->run()
#22 {main}
`

### Was sollte passieren? What you expected to happen?
I would expect to see the normal logged in area.

In the whole process in updating from an old v1.2 to a more modern 2.0, i had to switch the physical servers, database (webhosting -> MariaDb) and webserver (webhosting to nginx).
But until v.1.5 I can normally login and navigate in the admin area without any problems so far. I don't know why this column is missing. Mirgrations seem to run correctly but the error indicates otherwise.

Any ideas what i can check? I did not find anything similar to my issue.

**Comment by mrothauer** [comment]
it seems that migration 20180217191214_CakeUpdate.php was not applied. try to manually remove it from phinxlog table and run `bin/cake migrations migrate` again.

**Comment by Confuset** [comment]
So this is the 'normal' output:
` - /srv/http/config/Migrations
using seed paths 
 - /srv/http/config/Seeds
using environment default
using adapter mysql
using database shop_futterkreis

 == 20180217191214 CakeUpdate: migrating
 == 20180217191214 CakeUpdate: migrated 0,0100s

All Done. Took 0,0130s
using migration paths 
 - /srv/http/config/Migrations
using seed paths 
 - /srv/http/config/Seeds
Writing dump file `/srv/http/config/Migrations/schema-dump-default.lock`...
Dump file `/srv/http/config/Migrations/schema-dump-default.lock` was successfully written`

But additionally i receive this:
`# ./bin/cake migrations migrate >> migration.log
PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 242
Deprecated Error: Array and string offset access syntax with curly braces is deprecated in [/srv/http/vendor/cakephp/cakephp/src/Filesystem/Folder.php, line 576]

PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 242
Deprecated Error: Array and string offset access syntax with curly braces is deprecated in [/srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php, line 1006]

PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 242
Deprecated Error: Array and string offset access syntax with curly braces is deprecated in [/srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php, line 1006]

PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOutput.php on line 242
Deprecated Error: Array and string offset access syntax with curly braces is deprecated in [/srv/http/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php, line 1007]`

So i guess cake update is failing because my php(?) is to new?

**Comment by mrothauer** [comment]
> So i guess cake update is failing because my php(?) is to new?
I guess so too. In composer.json of v2.0.0 PHP 7.0 is specified, but according to https://www.php.net/manual/en/function.implode.php deprecation was introduced in PHP 7.4.
so anything from 7.0 to 7.3 should work
to avoid further problems with the update, i suggest using php 7.0

**Comment by Confuset** [comment]
I just manually patched the files to get rid of these errors and they disappeared. But the error on the website stays the same…

**Comment by mrothauer** [comment]
check your database manually if the field ProductShops.created exists. If it does not exist, the migration did not work.
if it exists, you can try to clear the cache
`bin/cake cache clear model`

**Comment by Confuset** [comment]
Its actually the table 'fcs_product_shop' correct? And the field is missing from that table, so i guess migration wasn't run to completion.
I am currently trying to get an older version of php running on arch. Its not that simple with rolling releases…

**Comment by Confuset** [comment]
I think I now run cake with php72:
```
# ./bin/cake migrations migrate
using migration paths 
 - /srv/http/config/Migrations
using seed paths 
 - /srv/http/config/Seeds
using environment default
using adapter mysql
using database shop_futterkreis

 == 20180217191214 CakeUpdate: migrating
 == 20180217191214 CakeUpdate: migrated 0,0093s

All Done. Took 0,0127s
using migration paths 
 - /srv/http/config/Migrations
using seed paths 
 - /srv/http/config/Seeds
Writing dump file `/srv/http/config/Migrations/schema-dump-default.lock`...
Dump file `/srv/http/config/Migrations/schema-dump-default.lock` was successfully written
```
But I still see the same error on my webpage. mhh

**Comment by Confuset** [comment]
Now I tried everything from scratch. Going from version 1.2 to 1.5 and then use php72 to run all the migrations. I did not receive any error during the migrations, but as soon as I login I receive the same error again…

**Comment by Confuset** [comment]
ok. tried it from scratch again. but this time I manually run that CakeUpdate against my DB to see if there are any errors:
```
# mysql database_name < ~/migrate.sql
ERROR 1072 (42000) at line 8: Key column 'id_lang' doesn't exist in table
```
I then split that CakeUpdate at line 8 and continued with the rest. Had to do that one more time. After that I still receive the error page, but this time for another column.

So I have the feeling that at least one of the other database updates: 18, 19, 20 is (silently) failing as well.
I will try them one by one tomorrow/today :-)

**Comment by mrothauer** [comment]
Maybe you also need to use an old mysql version (5.6) and maybe it's much easier to make a clean v3.0.2 install - but of course then the existing user and order data will be lost...
Good luck!

**Comment by Confuset** [comment]
I was thinking the same. Now that I found out db migration v18 is failing because of that line:
```
            ALTER TABLE `fcs_product_shop` DROP `id_shop`;
```
`id_shop` is missing in my db after v17
