### ISSUE TITLE
Cannot access sign-in page

### ISSUE THREAD

**Issue by flokadillo** [foodcoopshop/foodcoopshop#519]
Hallo Mario Rothauer,

erstmal danke für dein tolles Projekt! Wir vom Wohnprojekt KooWo bei Graz würden gerne deine Software benutzen um unsere FoodCoop ein wenig professioneller zu gestalten :). Derzeit habe ich noch folgende Installationsprobleme:

Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.0.2
* Browser und Betriebssystem / Browser and Operating System: Mozilla Firefox 76.0 / Ubuntu 18.0.4
* Platform and Target: I am currently trying to run the software on my local computer, a notebook with Ubuntu 18.0.4. 

### Was hast du gemacht? What you did?
I followed the install instructions closely, using `localhost` instead of a remote server. Everything went well until I wanted to create the Super Admin account. I wanted to create the account by clicking on `Anmelden` in the top right of the window.

### Was ist passiert? What happened?
After clicking on `Anmelden` I see the error 404 Not found.

### Was sollte passieren? What you expected to happen?
I expected to see a page where I can register with my personal email.

**Comment by Confuset** [comment]
Hi,
have you checked the log files for any errors?

**Comment by flokadillo** [comment]
Hi @Confuset , thanks for your answer. 
I have checked the following:
- The folder /var/www/foodcoopshop.test/logs/ is empty
- /var/log/apache2/access_foodcoopshop.log (CustumLog) is empty
- /var/log/apache2/access_foodcoopshop.log.1 contains:
  `
127.0.0.1 - - [11/May/2020:06:54:17 +0200] "GET / HTTP/1.1" 200 3120 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [11/May/2020:06:54:20 +0200] "GET /files/images/logo.jpg?1588413047 HTTP/1.1" 200 14118 "http://foodcoopshop.test/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [11/May/2020:06:54:20 +0200] "GET /files/images/sliders/demo-slider.jpg?1588413047 HTTP/1.1" 200 96460 "http://foodcoopshop.test/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [11/May/2020:06:54:20 +0200] "GET /js/localized-javascript.js HTTP/1.1" 404 495 "http://foodcoopshop.test/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [11/May/2020:06:54:20 +0200] "GET /js/localized-javascript.js HTTP/1.1" 404 496 "http://foodcoopshop.test/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [11/May/2020:06:54:20 +0200] "GET /img/bg.jpg HTTP/1.1" 200 61741 "http://foodcoopshop.test/cache/frontend.css?1588413044" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
127.0.0.1 - - [11/May/2020:06:54:28 +0200] "GET /anmelden HTTP/1.1" 404 496 "http://foodcoopshop.test/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"`
- /var/log/apache2/error.log
`[Mon May 11 06:56:00.207798 2020] [mpm_prefork:notice] [pid 1155] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Mon May 11 06:56:00.207847 2020] [core:notice] [pid 1155] AH00094: Command line: '/usr/sbin/apache2'`
- The ErrorLog specified in /etc/apache2/sites-enabled/020-foodcoopshop.test.conf has not been created, so I think no error from this side.

Are there any other error logs that I am not aware of?

Thanks!

**Comment by mrothauer** [comment]
Hi @flokadillo !

I'm really happy that you want to use the software within your co-housing project!

The main error log is /logs/error.log. If it's empty, maybe the permissions are wrong?

Is the url after clicking the button localhost/anmelden? or different?

**Comment by mrothauer** [comment]
please also read this:
https://github.com/foodcoopshop/foodcoopshop/issues/509

**Comment by flokadillo** [comment]
Hi Mario, thanks for your quick answer!

- The folder /var/www/foodcoopshop.test/logs is empty and has the correct permissions:
  ```
  >> ls -l
  drwxrwxrwx  2 www-data www-data   4096 Mai  2 16:44 logs
  ```
- In /etc/apache2/sites-enabled/020-foodcoopshop.test.conf there are two logs defined:
  ```
  ErrorLog ${APACHE_LOG_DIR}/error_foodcoopshop.log
  CustomLog ${APACHE_LOG_DIR}/access_foodcoopshop.log combined
  ```
  where APACHE_LOG_DIR=/var/log/apache2
  - /var/log/apache2/error_foodcoopshop.log exists but is empty
  - /var/log/apache2/access_foodcoopshop.log contains:
    `127.0.0.1 - - [11/May/2020:11:36:23 +0200] "GET /anmelden HTTP/1.1" 404 496 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"`
  - /var/log/apache2/error.log contains:
    ```
    [Mon May 11 11:36:03.960953 2020] [mpm_prefork:notice] [pid 2549] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations [Mon May 11 11:36:03.961056 2020]  [core:notice] [pid 2549] AH00094: Command line: '/usr/sbin/apache2'
    ```

- After clicking on `Anmelden`, the browser adress bar shows this adress: `http://foodcoopshop.test/anmelden`
- I had a look at #509, and as far as I understand, the DocumentRoot Variable had to be changed in their case to make it work. In my case, I have the following definition in /etc/apache2/sites-enabled/020-foodcoopshop.test.conf:
  ```
   <VirtualHost *:80>
   ServerAdmin webmaster@localhost
        DocumentRoot /var/www/foodcoopshop.test/webroot
        <Directory /var/www/foodcoopshop.test/webroot>
                Options FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>
   ```
Thanks and greetings from Volkersdorf,
Florian

**Comment by mrothauer** [comment]
Hmmm, strange... what about other links? eg.
`http://foodcoopshop.test/aktuelles` or `http://foodcoopshop.test/datenschutzerklaerung`

**Comment by flokadillo** [comment]
No, unfortunately always `404 Not Found`... Only `http://foodcoopshop.test/index.php` works...

**Comment by mrothauer** [comment]
is mod_rewrite enabled?

**Comment by flokadillo** [comment]
Hi Mario, you're a genius :). It wasn't. After `sudo a2enmod rewrite` I can access the page now!
Thanks for your quick help! Now I can go on :)
Best greetings!

**Comment by mrothauer** [comment]
:-) it's mentioned in the installation details in the requirements, I made it bold so that it's clearer...
https://foodcoopshop.github.io/en/installation-guide.html
good luck!
