### ISSUE TITLE
Selbstbedienungsmodus funktionslos & fehlerhafte Eingabeüberprüfung

### ISSUE THREAD

**Issue by ocapito** [foodcoopshop/foodcoopshop#523]
Das ist ein

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.0.2
* Firefox 76.0.1, Mac OSX 10.11.6
* Platform and Target: ?

# **Generelle Funktion des Features**
### Was hast du gemacht? What you did?
* Selbstbedienungsmodus aufgerufen
* Gewicht in kg eingeben (Produkt mit Preis nach Gewicht)
* Anzahl auf 1 belassen
* "In die Einkaufstasche" klicken
* Produkt erscheint in der Einkaufstasche
* AGB und Rücktritt anhaken
* Auf "Abholung abschießen" klicken

### Was ist passiert? What happened?
* Fehlermeldung: "Deine Einkaufstasche war leer."
* Einkaufstasche wir nun leer angezeigt.
* Wenn ich in den normalen Bestell Bereich gehe wird das Produkt in meinem normalen Warenkorb gelistet. (wrüde ich nicht erwarten)
* Feher Reproduziert von verschiedenen Accounts, mit oder ohne Guthaben, immer der gleiche Verlauf.
* Produkt was bestellt werden sollte hatte einen positiven Lagerbestand.

### Was sollte passieren? What you expected to happen?
* Bestätigungsmeldung und Guthaben reduzieren.
* Produkt sollte nicht im normalen Warenkorb erscheinen.

# **Eingabeüberprüfung**
### Was hast du gemacht?
case 1:
* Anzahl auf ein belassen
* kein Gewicht eingeben
* "In die Einkaufstasche" klicken

case 2:
* Anzahl auf eins belassen
* kein Gewicht eingeben 
* "In die Einkaufstasche" klicken
* Jetzt ein Gewicht eintragen
* Nochmals "In die Einkaufstasche" klicken

### Was ist passiert?
case 1:
* Gewichtsfeld rot
* Produkt erscheint in Einkaufstascheaber 

case 2:
* Produkt erscheint in Einkaufstasche aber mit NaN kg

### Was sollte passieren? 
case 1 & case 2:
* Fehlermeldung "Bitte trage das entnommene Gewicht ein" (wie in der Dokumentation angezeigt https://foodcoopshop.github.io/de/selbstbedienungs-modus)

**Comment by mrothauer** [comment]
Hallo,

> Wenn ich in den normalen Bestell Bereich gehe wird das Produkt in meinem normalen Warenkorb gelistet. (wrüde ich nicht erwarten)

Meinst du wirklich "Warenkorb" oder die vielleicht die Produkt-Liste? Letzeres kannst du in den Einstellungen selbst ändern: "Sollen Lagerprodukte mit der wöchentlichen Bestellung bestellt werden können?" : nein

Case 1
Klappt bei mir.

Case 2
Klappt bei mir auch.

Habs in FF76.01, allerdings auf Windows, getestet. Ich denke, es ist ein Problem, das nur auf dem Mac auftritt.

Bitte schicke mir Screenshots (wenn möglich vom ganzen Anwendungs-Fenster), vielleicht seh ich dann etwas, was mir weiterhilft.

Bitte auch die Entwickler-Toolbar öffnen, denn hier sieht man Fehlermeldungen, die mir evtl. weiterhelfen.

PS: Einen kleinen Bug hab ich gefunden: Wenn die Häkchen nicht angehakt sind, ist der Button "Abholung abschließen" nicht mehr klickbar, er bleibt ausgegraut und der Loader dreht und dreht sich. Ich werde dafür allerdings kein eigenes Release erstellen, bitte diese kleine Anpassung selbst vornehmen:
https://github.com/foodcoopshop/foodcoopshop/commit/b949d67e307289815f148a1fb8e534b85b1c2d95

**Comment by ocapito** [comment]
Hi,

> Meinst du wirklich "Warenkorb"

Ja es erscheint wirklich im Warenkorb, sogar wenn ich einfach nur in den SB Modus gehe, dort eine Sache in die Einkaufstasche lege und dann über den Home button gleich wieder zurück gehe liegt es in meinem normalen Warenkorb.
1. SB-Modus wenn ich ihn aufrufe
![SB-Blank](https://user-images.githubusercontent.com/5548912/82347980-93de9b00-99f8-11ea-8919-8befa2f5bc81.png)

1. SB-Modus nachdem ich das erste Item in Tasche gelegt habe (keine Fehlermeldung obwohl kein Gewicht eingetragen nur rotes Eingabefeld)
![SB-erstes Item in Tasche](https://user-images.githubusercontent.com/5548912/82348024-9e993000-99f8-11ea-847f-28c9cb3a80e5.png)

1. SB-Modus gleiches Item nochmals hinzugefügt aber nun Gewicht eingetragen (NaN in Mengenfeld in Einkaufstasche).
![Bildschirmfoto 2020-05-19 um 17 50 58](https://user-images.githubusercontent.com/5548912/82348712-870e7700-99f9-11ea-8987-ad6c46861f17.png)

1. Häkchen setzen und auf Abholung abschließen klicken ergibt:
![Bildschirmfoto 2020-05-19 um 17 56 52](https://user-images.githubusercontent.com/5548912/82349376-4fec9580-99fa-11ea-9a97-94bffc55c751.png)

1. Warenkorb direkt nachdem ich unten auf den Homebutton gehe (passiert auch wenn ich direkt nachdem ich das erste Item in die Tasche gelegt habe zurück gehe).
![Warenkorb](https://user-images.githubusercontent.com/5548912/82348048-a658d480-99f8-11ea-9a31-561ac0556f45.png)

> Habs in FF76.01, allerdings auf Windows, getestet. Ich denke, es ist ein Problem, das nur auf dem Mac auftritt.

Wir konnten das Problem auch unter Linux von einem andern User-Account reproduzieren (ebenfalls Firefox, weitere Systemdaten hab ich gerade nicht parat könnte ich aber erfragen.)

**Comment by mrothauer** [comment]
Danke für die Infos. Ich habe auf Browserstack mit Firefox 76.0.1, Mac OSX El Capitan getestet und konnte das Problem leider nicht nachvollziehen. Auch unter Ubuntu 18.04 / FF 76 klappt alles.
Hmmm.
Die Software kommt mit dem Warenkorb durcheinander, dazu werden die Variablen $_SERVER['HTTP_REFERER'] und $_SERVER['REQUEST_URI'] verwendet. See https://github.com/foodcoopshop/foodcoopshop/blob/c3b2fa505da81e5876d5ceb108147105a6247263/src/Controller/Component/AppAuthComponent.php#L208-L222
Hilft dir das weiter? Sonst fällt mir leider grad nichts ein, wo wir ansetzen könnten.
Kannst du mal testen, obs bei dir unter Windows funktioniert?

**Comment by ocapito** [comment]
Konnte das Problem unter Win 10 Pro (1909) mit Edge (44.18362.449.0) und Firefox (75.0 64-Bit) reproduzieren.

**Comment by mrothauer** [comment]
Hast du mal probiert, die Funktion auf der Demo-Seite auszuprobieren? https://demo-de.foodcoopshop.com/ Weil vielleicht ist es ja ein Problem am Server und dann schlägts natürlich bei jedem Browser fehl... Vielleicht kannst du mir - sofern öffentlich zugänglich - auch den Link zu deiner Installation schicken, aber vermutlich klappt's dann auch bei mir nicht.
Ansonsten: hat dir mein letzter Kommentar geholfen? Wird der HTTP_REFERER am Server evtl. überschrieben?

**Comment by ocapito** [comment]
Ich habe noch gesehen, dass nach so einem Vorgang eine Fehlermail zugesendet bekomme, vielleicht liefert das noch Anhaltspunkte:

> RequestUri:/warenkorb/ajaxAdd/
Referer:https://foodcoop.xxxxxxx.org/selbstbedienung
Message
Notice (8): Undefined index: orderedQuantityInUnits in [xxxx/foodcoopshop/src/Model/Table/CartProductsTable.php, line 236]
Request URL: /warenkorb/ajaxAdd/
Referer URL: https://foodcoop.xxxxxxx.org/selbstbedienung
Client IP: xxxxxxx
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 188
App\Model\Table\CartProductsTable::add() - APP/Model/Table/CartProductsTable.php, line 236
App\Controller\CartsController::ajaxAdd() - APP/Controller/CartsController.php, line 305
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 524
Cake\Controller\ControllerFactory::invoke() - CORE/src/Controller/ControllerFactory.php, line 79
Cake\Http\BaseApplication::handle() - CORE/src/Http/BaseApplication.php, line 229
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 77
Cake\Routing\Middleware\RoutingMiddleware::process() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 156
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Routing\Middleware\AssetMiddleware::process() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 68
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Http\Middleware\DoublePassDecoratorMiddleware::Cake\Http\Middleware\{closure}() - CORE/src/Http/Middleware/DoublePassDecoratorMiddleware.php, line 74
AssetCompress\Middleware\AssetCompressMiddleware::__invoke() - ROOT/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php, line 53
Cake\Http\Middleware\DoublePassDecoratorMiddleware::process() - CORE/src/Http/Middleware/DoublePassDecoratorMiddleware.php, line 75
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Error\Middleware\ErrorHandlerMiddleware::process() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 118
Cake\Http\Runner::handle() - CORE/src/Http/Runner.php, line 73
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 58
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 90
[main] - ROOT/webroot/index.php, line 40
Request
Array
(
    [productId] => 25
    [amount] => 1
    [orderedQuantityInUnits] => 0.05
    [PHPSESSID] => XXX
)

**Comment by Podden** [comment]
Hallo, darf ich erfahren ob und wie ihr das Problem beheben konntet? Ich habe hier nämlich das Gleiche und mein Tipp geht eher Richtung Konfigurationsfehler des Servers als Problem beim Nutzer.

**Comment by mrothauer** [comment]
Hallo @Podden 
ich hab damals leider keine Rückmeldung mehr bekommen, ob das Problem behoben werden konnte. Ich konnte es jedenfalls nicht reproduzieren.
@ocapito hast du da noch nützliche Infos?

**Comment by mrothauer** [comment]
Bitte überprüfen, ob die $_SERVER-Verriable auch die Indizes HTTP_REFERER und REQUEST_URI enthält.

**Comment by ocapito** [comment]
Ich kann leider noch nichts neues melden, das Problem besteht weiterhin (und wir nutzen den Selbstbedienungsmodus nicht), wir haben uns bisher aber auch nicht weiter damit beschäftigt und ich habe auch Updates etwas vernachlässigt. Wenn ich noch etwas rausfinde melde ich mich wieder.

**Comment by ocapito** [comment]
Habe mir gerade mal $_SERVER angesehen und finde da tatsächlich keinen der beiden Indizes im Array. Scheint also die Heiße Spur zu sein, danke für den Tipp. Da ich selber leider nicht so firm in dem ganzen bin muss ich mir dann mal Unterstützung holen, um das zu ändern und zu schauen ob es das Problem löst.

**Comment by mrothauer** [comment]
@ocapito 
@Podden hat den Fehler gefunden, bei ihm endete `app.cakeServerName` mit einem / - das war das Problem.
Ich werde das noch dementsprechend dokumentieren.

**Comment by ocapito** [comment]
Ich bin leider gerade unterwegs müsste mir das nächste Woche oder so nochmal ansehen ob wir da eine Lösung gefunden hatten. 

Lg
Paco

**Comment by ocapito** [comment]
Ok vielen Dank! Es scheint jetzt auch für mich zu funktionieren nachdem ich den / am Ende der URL entfernt habe.

Für alle die vielleicht, wie ich, weniger versierter sind:
Die Zeile 'cakeServerName' => 'https://deineDomain', findet sich in der custom_config. Dort darf am Ende der URL kein / stehen (wie es auch im Beispiel zu sehen ist).
