### ISSUE TITLE
RequestException cURL Error (3)  malformed

### ISSUE THREAD

**Issue by massilassi** [foodcoopshop/foodcoopshop#526]
Hello!

I'm a neighbor of @flokadillo  #519, we collaborated to successfully configure and install the software. Still we have some problems with the cronjobs.
 
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [x] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.0.2
* Browser und Betriebssystem / Browser and Operating System: Mozilla Firefox 76.0 / Ubuntu 18.0.4
* Platform and Target: I am currently trying to run the software on my local computer, a notebook with Ubuntu 18.0.4.

### Was hast du gemacht? What you did?
In the Database all cronjobs are active with default values. I called the /cron page to start the cronjobs.

### Was ist passiert? What happened?
The backup gets generated and I get the info by email. However I also get the following error (browser shows the error page) in a successive (debug) email:

```
[Cake\Http\Client\Exception\RequestException] cURL Error (3)  malformed in /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client/Adapter/Curl.php on line 65
Stack Trace:
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:466
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:436
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:391
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:274
- /var/www/foodcoopshop.test/src/Network/AppHttpClient.php:128
- /var/www/foodcoopshop.test/src/Network/AppHttpClient.php:143
- /var/www/foodcoopshop.test/src/Shell/SendOrderListsShell.php:75
- /var/www/foodcoopshop.test/src/Model/Table/CronjobsTable.php:115
- /var/www/foodcoopshop.test/src/Model/Table/CronjobsTable.php:97
- /var/www/foodcoopshop.test/src/Controller/CronController.php:37
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Controller/Controller.php:524
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:79
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/BaseApplication.php:229
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Runner.php:77
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:156
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Middleware/DoublePassDecoratorMiddleware.php:74
- /var/www/foodcoopshop.test/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php:53
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Middleware/DoublePassDecoratorMiddleware.php:75
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:118
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Server.php:90
- /var/www/foodcoopshop.test/webroot/index.php:41

Request URL: /cron
Client IP: 127.0.0.1


Server

Array
(
    [REDIRECT_HTTP_AUTHORIZATION] => 
    [REDIRECT_STATUS] => 200
    [HTTP_AUTHORIZATION] => 
    [HTTP_HOST] => foodcoopshop.test
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_CONNECTION] => keep-alive
    [HTTP_COOKIE] => PHPSESSID=ju2eua14gj9n92jc5rumc4rgev
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_CACHE_CONTROL] => max-age=0
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
    [SERVER_SIGNATURE] => 
Apache/2.4.29 (Ubuntu) Server at foodcoopshop.test Port 80


    [SERVER_SOFTWARE] => Apache/2.4.29 (Ubuntu)
    [SERVER_NAME] => foodcoopshop.test
    [SERVER_ADDR] => 127.0.0.1
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 127.0.0.1
    [DOCUMENT_ROOT] => /var/www/foodcoopshop.test/webroot
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/foodcoopshop.test/webroot
    [SERVER_ADMIN] => webmaster@localhost
    [SCRIPT_FILENAME] => /var/www/foodcoopshop.test/webroot/index.php
    [REMOTE_PORT] => 53412
    [REDIRECT_URL] => /cron
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [REQUEST_URI] => /cron
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1590062247.014
    [REQUEST_TIME] => 1590062247
)
```

Request and Files array are empty and User array contains my user (admin) information.

### Was sollte passieren? What you expected to happen?
No error should be triggered :D

For the enhancement part of this ticket, before stumbling upon this Exception I got another error while calling the same page, namely "Error: [Error] Class 'ZipArchive' not found in /var/www/foodcoopshop.test/src/Shell/BackupDatabaseShell.php on line 58". If the backup cronjob is active, ZipArchive is required and has to be installed, but I don't remember reading about it in the documentation.
Furthermore, the documentation about cronjobs is a bit unclear to me. Do I have to configure something particularly, simply call the /cron link to start the cronjobs everytime I need or does it get called automatically every 10 minutes?

Thanks in advance!

Best,
massilassi

**Comment by mrothauer** [comment]
Hi @massilassi 

as far as i read from your description, there are 2 different errors.

1) SendOrderListsShell: my first guess is that curl is not activated / installed on your system. can you check that please?

2) BackupDatabaseShell: is the zip command available and executable by your webserver?

to debug the errors one by one, you can call `bin/cake SendOrderLists` and `bin/cake BackupDatabase` separately

And: You need to define a cronjob that calls /cron every 5 or 10 minutes. see eg. https://wiki.ubuntuusers.de/Cron/

Good luck!

**Comment by massilassi** [comment]
Hi Mario, thanks for the quick reply!

> 1. SendOrderListsShell: my first guess is that curl is not activated / installed on your system. can you check that please?

Curl was indeed missing. I installed curl and php-curl, restarted apache but I still get that exception while calling the /cron. `php -i` tells me this:

```
curl

cURL support => enabled
cURL Information => 7.58.0
Age => 4
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => Yes
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-gnu
SSL Version => OpenSSL/1.1.1
ZLib Version => 1.2.11

Directive => Local Value => Master Value
curl.cainfo => no value => no value
```
It looks to me that the module is correctly loaded and available, what else could I check? How do I call `bin/cake SendOrderLists` exactly?


> 2. BackupDatabaseShell: is the zip command available and executable by your webserver?

Maybe I misswrote. This problem was due to the ZipArchive missing. After installing it, the exception was gone (now when I call /cron I do get an email with the daily zipped backup). All solved here :)

Thanks for the link about cronjobs, I will give it a go!

Best,
massilassi

**Comment by mrothauer** [comment]
> It looks to me that the module is correctly loaded and available, what else could I check?

If curl makes problems, you could try to change the transport adapter of cake's http client:
https://book.cakephp.org/4/en/core-libraries/httpclient.html#changing-transport-adapters
But that would result in manually updateing your application after each version update of FoodCoopShop - If changing the transport adapter would be really necessary and the only solution, you can open a PR and I will merge it in the core.

> How do I call bin/cake SendOrderLists exactly?

Open the console, switch to the path of your installation, and type `bin/cake SendOrderLists`.

> This problem was due to the ZipArchive missing.

Most of the time it's preinstalled, but I added it to the requirements list.
