### ISSUE TITLE
Ändern von Herstellerdaten (Mailadresse)

### ISSUE THREAD

**Issue by emilgast** [foodcoopshop/foodcoopshop#533]
@mrothauer 
Einer unserer Lieferanten hat umfirmiert - neue Firmenbezeichnung, neue Mailadresse, aber die gleichen Produkte. Kann ich direkt in der Datenbank in fcs_address die Mailadresse (email) ausbessern damit alle anderen Daten erhalten und zugeordnet bleiben und eine Anmeldung für den Lieferanten dann mit der neuen Mailadresse möglich ist und er dann alle anderen Datenänderungen wieder selber durchführen kann?

**Comment by mrothauer** [comment]
Hallo,
spricht was dagegen, die Daten als Admin / Superadmin direkt im Hersteller-Profil zu ändern? Die Möglichkeit gibt es ja.
