### ISSUE TITLE
Bug if server uses "en_US" and installation "de_DE" locale

### ISSUE THREAD

**Issue by MaxGitHubAccount** [foodcoopshop/foodcoopshop#540]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [X] Bug
* [X] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: v 3.0.2 stable
* Browser und Betriebssystem / Browser and Operating System: Firefox 78.0.1 64 Bit Linux
* Platform and Target: Debian Buster Apache / MySQL Latest

### Was hast du gemacht? What you did?
1. Go to "Selbstbedienung"
2. Select the weight (" Gewicht in kg: ") field of a product and type in a number with a dot separating the number.
3. add the product via "In die Einkaufstasche"

### Was ist passiert? What happened?
2. the number in the input field shows with the dot separator
3. the number is parsed ignoring the dot separator

### Was sollte passieren? What you expected to happen?
Either a dot separator should be used to determine the decimals or it should throw an error to the customer that his internationalized decimal separator is the comma. The current behaviour ignores all dot separators. So even 145.1.4.2,4.124 is a valid input ignoring all dots and only using the comma.

Easy solution:
Just check for the last separator (comma or dot) and use it as decimal separator.
See https://stackoverflow.com/questions/4325363/converting-a-number-with-comma-as-decimal-point-to-float

A more formalized solution to check for more cases:
* is there a decimal separator? (Comma or dot)
  * if no just parse the number
  * if yes check if it's unique
    * if it's unique just parse the number using this separator
    * if no either select the internationalized correct one or preset one and ignore the rest (current behaviour) or throw an error asking the user to only use one decimal separator

This last case will probably never happen and is only there to not have an undefined behaviour. However this approach would satisfy as the decimal separator is not the same throughout all kind of applications and depending on your localization. Another option would be throw an error when the user uses the "wrong" decimal separator.

However I assume that a use case to enter dots for separating thousands of kilos is not valid for input boxes. However even with copying numbers from elsewhere would result in the correct number with the defined algorithm.

Bevor du das Issue erstellst, überprüfe bitte, ob es bereits ein ähnliches gibt.
Before you open an issue, please check if a similar issue already exists or has been closed before.

I checked.

Du kannst dem Projekt zu mehr Sichtbarkeit verhelfen, in dem du ihm einen Stern ⭐ gibst. Danke!
You help making the project more visible by starring ⭐ it. Thank you!

**Comment by mrothauer** [comment]
Hi, thank's for the detailed bug report. For installations with "de_DE"-locale don't see urgent need for fixing that, as I don't think that many people use the dot in the input field.
But feel free to provide a PR.
Mario

**Comment by MaxGitHubAccount** [comment]
Hi @mrothauer 

There is a related problem. If the operation system of the client uses en_US locales when using a server installation with "de_DE" one enters commas to get the correct number in the system.

But if you enter two products with commas the total weight is calculated incorrectly and there is no possibility to get it correct.

So if you add 1 product with 1,1 and the same product again with 1,2 kg you get a sum of both products with 12.2 kg shown. As the dot is no valid decimal delimiter (1.1kg would be 11kg) there is no way to work around apart from deleting all entries and sum manually.

**Comment by mrothauer** [comment]
Hi @MaxGitHubAccount,
sorry, I don't have capacities for debugging your problem at the moment.
Is there no way to change the server's locale to "de_DE"?

**Comment by MaxGitHubAccount** [comment]
The workaround changing the servers locale works (for German inputs now)
