### ISSUE TITLE
SendOrderLists login problem

### ISSUE THREAD

**Issue by flokadillo** [foodcoopshop/foodcoopshop#544]
Hallo Mario,

hier ist mal wieder Florian vom Wohnprojekt Koowo in Volkersdorf bei Graz. Ich komme mal wieder nicht weiter beim Konfigurieren deiner wunderbaren Foodcoop Software.

Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.0
* Browser und Betriebssystem / Browser and Operating System: Mozilla Firefox 76.0 / Ubuntu 18.0.4
* Platform and Target: Apache Web Server

### Was hast du gemacht? What you did?
I wanted to test the cron jobs, particularly SendOrderLists. 
Therefore I executed `bin/cake SendOrderLists`.

### Was ist passiert? What happened?
I get the following error:
```
2020-07-16 22:29:14 Error: [Cake\Http\Client\Exception\RequestException] fopen(/:///anmelden): failed to open stream: No such file or directory in /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client/Adapter/Stream.php on line 327
Stack Trace:
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client/Adapter/Stream.php:253
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client/Adapter/Stream.php:82
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:466
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:436
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:391
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Http/Client.php:274
- /var/www/foodcoopshop.test/src/Network/AppHttpClient.php:128
- /var/www/foodcoopshop.test/src/Network/AppHttpClient.php:143
- /var/www/foodcoopshop.test/src/Shell/SendOrderListsShell.php:75
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Console/Shell.php:516
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Console/CommandRunner.php:354
- /var/www/foodcoopshop.test/vendor/cakephp/cakephp/src/Console/CommandRunner.php:168
- /var/www/foodcoopshop.test/bin/cake.php:12
```

### Was sollte passieren? What you expected to happen?
I expected that no error happens and the order list is sent.

Danke und liebe Grüße aus Volkersdorf!
Florian

**Comment by mrothauer** [comment]
Hallo,
kann es sein, dass in der custom_config.php die Einstellung "cakeServerName" nicht gesetzt ist?

**Comment by flokadillo** [comment]
Hi Mario,

danke für den Hinweis, ich hatte `cakeServerName` gesetzt, habe aber das Präfix `http://` vergessen. Das ist wohl wichtig um die Adresse aufzulösen. D.h. mein, `custom_config.php` enthält jetzt die Zeile:
```
'cakeServerName' => 'http://foodcoopshop.test',
```
und damit geht es. Vielen Dank mal wieder!

Florian

**Comment by mrothauer** [comment]
gerne! super dass es jetzt funktioniert.
