### ISSUE TITLE
Guthaben-Limit soll beim Bestellen nicht mehr unterschritten werden können

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#555]
Momentan ist es ja möglich, noch genau eine Bestellung (egal, in welcher Höhe) zu tätigen, wenn das Guthaben vor dieser Bestellung über dem Schwellwert ist.

* [x] Beschreibungs-Text in Einstellungen ändern und Werte migrieren (0 => -500, 1 => 0, rest * -1)
* [x] validierung config anpassen -1.000 € bis 0 €
* [x] Prüfung bei Klick auf "in den Warenkorb" für Produkt
* [x] Sofort-Bestellung und Gewichts- bzw. Preisänderung sollen weiterhin unbeschränkt möglich sein
* [x] Prüfung bei Klick auf "in den Warenkorb" für Varianten
* [x] im Selbstbedienungs-Modus testen
* [x] Prüfung bei Bestellabschluss (Preis könnte sich in Zwischenzeit geändert haben)
* [x] Mobile Ansicht testen
* [x] Changelog

**Comment by hasslerf** [comment]
Wenn ich ein negatives Guthaben habe, werden zwar die `In den Warenkorb`-Buttons deaktiviert, ich kann aber vergangene Bestellungen in den Warenkorb legen (zB über den Link aus dem Erinnerungsmail). 
Kann ich diese Bestellung dann auch abschicken und somit mein Guthaben noch weiter unterschreiten?

**Comment by mrothauer** [comment]
@hasslerf ja, das müsste aktuell so sein. sobald der warenkorb befüllt ist, lässt sich der auch abschicken. das problem würde durch meine änderung aber auch behoben werden (der warenkorb würde gar nicht erst befüllt werden können, auch nicht durch den link aus der mail).
