### ISSUE TITLE
CustomFrontendColor auch im (Kunden-)Adminbereich

### ISSUE THREAD

**Issue by reicharm** [foodcoopshop/foodcoopshop#613]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [x] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.1.0
* Browser und Betriebssystem / Browser and Operating System: EG FIREFOX 64 / Windows 10
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### Was hast du gemacht? What you did?
Bei Verwendung einer Hauptfarbe am Frontend (Setting customFrontendColorTheme) wird diese Farbe zwar am Frontend für den Kunden, nicht aber im Admin-Bereich des Kunden (Bestellungen, Meine Daten, Passwort ändern, ...) angezeigt/verwendet.
Wenn die verwendete Farbe ähnlich aber nicht gleich der Standardfarbe Grün ist, passt das potentiell nicht zusammen und verwirrt den Kunden potentiell.

### Was sollte passieren? What you expected to happen?
customFrontendColorTheme sollte auch im Admin-Bereich analog zum Frontend verwendet werden für ein einheitliches Erscheinungsbild. 
Auch das "Backstretch" Hintergrundbild im Admin-Bereich kann durch die direkte Einbindung im HTML-Code nicht einfach durch CSS angepasst werden - evtl könnte man hier auch eine anpassungsfähigere Lösung finden.

Vielen Dank!

lg
Michi

**Comment by mrothauer** [comment]
Hallo Michi,
ich hab das schon einige Zeit geplant, aber es gibt immer wichtigere Todos... Wenn du es umsetzen kannst und möchtest, würde ich den Pull Request auf jeden Fall annehmen.
Sonst fürchte ich, dass das noch eine Weile so bleibt, wie es ist.
Magst du mir noch sagen, von welcher Initiative du bist?
Lg,
Mario

**Comment by reicharm** [comment]
Hallo Mario,

danke für die Info. Ich hab es jetzt bei uns fürs erste mit CSS gelöst. Ich werde mir bei Gelegenheit mal ansehen, ob ich das generell einbauen kann analog zur Lösung am Frontend.
Ich bin Techniker bei "s'KerbaL" in Kremsmünster wir bauen unsere Foodcoop mit deiner Software gerade erst auf unter www.kerbal.at

lg
Michi

**Comment by mrothauer** [comment]
Ok danke auch für die Info, dann weiß ich Bescheid. Viel Erfolg mit eurem Kerbal, cool, dass es jetzt auch in Kremsmünster eine Foodcoop gibt!
