### ISSUE TITLE
Blog Artikel: Automatische Bilder-Zuordnung

### ISSUE THREAD

**Issue by tantelisl** [foodcoopshop/foodcoopshop#62]
**Bei Neuerstellung eines Blogartikels.** Wird ein Hersteller dem Artikel zugeordnet wäre es praktisch wenn automatisch das Logo des Herstellers als Bild ausgewählt ist und man nicht extra ein Bild hochladen muss.

**Comment by veronimus** [comment]
bei Blogartikeln von Produzenten, die kein eigenes Logo haben wird derzeit das Logo der jeweiligen Foodcoop als Bild verwendet. In der Übersicht wirkt das aber so, als sei es eine Nachricht der ganzen Foodcoop (zB. steht mitunter "wir machen Pause bis...." und es handelt sich um Urlaub des Herstellers  - es wirkt aber, als mache die ganze Foodcoop Pause)

Könnte da vielleicht auf irgendein Produktbild des Herstellers zurückgegriffen werden oder zumindest nur der Name als Schriftzug aufscheinen?

**Comment by tantelisl** [comment]
@wintersim Danke fürs erledigen
