### ISSUE TITLE
Besseres Symbol: Kontaktdaten Mitglieder

### ISSUE THREAD

**Issue by tantelisl** [foodcoopshop/foodcoopshop#63]
## Adminbereich- Mitglieder - Kontaktdaten (Name)
Da bei einem Abholdienst die Telefonnummern öfters gebraucht werden wenn jemand vergisst seine Waren abzuholen, wäre es super wenn die Telefonnummer besser ersichtlich ist. Vorschlag: Telefonsymbol statt Buch.

**Comment by mrothauer** [comment]
habs auch gleich bei den herstellern geändert - da ist die problematik ja die gleiche

**Comment by mrothauer** [comment]
https://github.com/foodcoopshop/foodcoopshop/commit/0d02056fd5bb04e616b2e58d2cbcb69be4632b6c
