### ISSUE TITLE
Dorfladen - Registrierungsprozess

### ISSUE THREAD

**Issue by toblinga** [foodcoopshop/foodcoopshop#633]
* [ ] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)
* [x] Frage zur Konfiguration 

* FoodCoopShop Version: 3.2.0-dev (Konfiguriert als Dorfladen wie in der Anleitung)
* Browser und Betriebssystem / Browser and Operating System: 
* Platform and Target: 
* 
### Was sollte passieren? What you expected to happen?
ist es möglich den Login-Prozess so zu konfigurieren, dass man neue Benutzer nicht bestätigen muss. Sprich der Benutzer gleiche eine Mail mit PW usw. bekommt. Wenn ja wie?
DANKE!

**Comment by mrothauer** [comment]
ja das geht schon lang
homepage-verwaltung / einstellungen / Neue Kunden automatisch aktivieren? : Ja
Lg,
Mario

**Comment by toblinga** [comment]
sorry, aber da hatte ich was auf den Augen :/
DANKE!
