### ISSUE TITLE
Kommentarfunktion für Produkt

### ISSUE THREAD

**Issue by tantelisl** [foodcoopshop/foodcoopshop#64]
Kommentarfunktion für den Besteller

* Kommentarfunktion beim Artikel z.b bei Jungpflanzen, Sortenwunsch
 oder Gemüsekiste, welches Gemüse nicht gewünscht ist
oder bei Sammelbestellungen wenn es Mindestbestellmengen gibt um anzugeben wie viel ich nehmen würde wenn die Menge nicht erreicht wird um zu bestellen.

* Diese Funktion im Herstellerbereich  bzw. bei der Artikelverwaltung für die Hersteller zum aktivieren und deaktivieren.
* Kommentar auch in den Bestellisten.

**Comment by veronimus** [comment]
Ähnlicher Sachverhalt: Ein Produzent bietet diverse Kräuter an. Derzeit müsste man jede einzelne Sorte im  Shop anlegen. Mit so einer Funktion, könnte der Konsument beim Bestellen einen Kommentar an den Hersteller schicken, welche Sorte er haben möchte...
