### ISSUE TITLE
Fehlende Migrations in v3.2

### ISSUE THREAD

**Issue by mantensteiner** [foodcoopshop/foodcoopshop#649]
* [x] Bug
* FoodCoopShop Version: 3.2

Nach dem letzten Update kommt es bei der Funktion "Produkte abgeholt" in der Bestellliste zu einem Fehler wenn die Bestellung als abgeholt markiert wird.

Aus dem Errorlog: 'Column not found: 1054 Unknown column 'OrderDetailUnits.mark_as_saved'.

Im vorliegenden Fall fehlte die Spalte _mark_as_saved_ in der Table _fcs_order_detail_units_. Nach erster Prüfung ist mir keine Migration aufgefallen wo die neue Spalte hinzugefügt werden würde.

Habe die Spalte testweise hinzugefügt: _ALTER TABLE fcs_order_detail_units ADD COLUMN mark_as_saved TINYINT(3) unsigned NOT NULL DEFAULT 0;_. 
Die Bestellung kann jetzt zwar als abgeholt markiert werden, es kommt im UI (nicht im Errorlog) jetzt dennoch eine Fehlermeldung 'Das Gewicht wurde bei 2 Produkten noch nicht angepasst. Mitglied: XYZ'.

LG Michael

**Comment by mrothauer** [comment]
poste bitte mal den inhalt der tabelle phinxlog

**Comment by mrothauer** [comment]
hmmm, ich glaub das ist beim mergen kurz vor dem release von 3.0 was durcheinandergekommen, weil ich hab da mal alle alten migrations gelöscht (weils schon so viele waren).
es müsste wieder alles passen, wenn du die zwei migrations hier in den entsprechenden ordner kopierst und dann `bin/cake migrations migrate` aufrufst
https://github.com/foodcoopshop/foodcoopshop/blob/1d7561acd589eb0f4cc04b33c960dcef6cb4c414/config/Migrations/20200319092123_ChangeDefaultTableCollationToUtf8mb4.php
https://github.com/foodcoopshop/foodcoopshop/blob/1d7561acd589eb0f4cc04b33c960dcef6cb4c414/config/Migrations/20200319192745_MarkPricePerUnitAsSaved.php

**Comment by mantensteiner** [comment]
Danke für die Prüfung, hab die Spalte nochmal entfernt und wie von die vorgeschlafen beide Migrationen entfernt. Der Zustand ist aber gleich wie oben: Es funktioniert die Markierung als "Abgeholt", jedoch kommt im UI eine verwirrende Felhermeldung bezüglich der Abwiegeprodukte in der Bestellung (aber kein Errorlog): 
![Fehler_Abgeholt](https://user-images.githubusercontent.com/1150353/111900503-327dc300-8a33-11eb-8951-eca40a9d2627.png)

Vielleicht ist die Fehlermeldung ja nur ein Anzeigeproblem, bekomme im UI aber keine Javascript-Fehler. Aber mir ist aufgefallen das es im UI etwas "glitcht", z.B. beim "Neues Produkt"-Dialog:

![New Product Dialog](https://user-images.githubusercontent.com/1150353/111900655-1af30a00-8a34-11eb-99fb-de744db52f46.png)

Ist mir nur aufgefallen muss nicht zusammenhängen ...

**Comment by mrothauer** [comment]
> Danke für die Prüfung, hab die Spalte nochmal entfernt und wie von die vorgeschlafen beide Migrationen entfernt. Der Zustand ist aber gleich wie oben: Es funktioniert die Markierung als "Abgeholt", jedoch kommt im UI eine verwirrende Felhermeldung bezüglich der Abwiegeprodukte in der Bestellung (aber kein Errorlog):
> ![Fehler_Abgeholt](https://user-images.githubusercontent.com/1150353/111900503-327dc300-8a33-11eb-8951-eca40a9d2627.png)

Kann es sein, dass es in der entsprechenden Bestellung tatsächlich Produkte gibt, deren Gewicht noch rot (also unverändert) ist? Weil dafür ist die "Fehlermeldung" (die eher ein Hinweis ist) ja da.

> Vielleicht ist die Fehlermeldung ja nur ein Anzeigeproblem, bekomme im UI aber keine Javascript-Fehler. Aber mir ist aufgefallen das es im UI etwas "glitcht", z.B. beim "Neues Produkt"-Dialog:
> 
> ![New Product Dialog](https://user-images.githubusercontent.com/1150353/111900655-1af30a00-8a34-11eb-99fb-de744db52f46.png)
>
Das wurde in diesem Commit hier bereinigt, wird Teil von der nächsten Version 3.2.1, die evtl. nächste Woche erscheinen wird.
https://github.com/foodcoopshop/foodcoopshop/commit/71058d4d388019481a0254709eb19b05bf82396e

> Ist mir nur aufgefallen muss nicht zusammenhängen ...

Hängt ziemlich sicher nicht zusammen.

**Comment by mantensteiner** [comment]
> Kann es sein, dass es in der entsprechenden Bestellung tatsächlich Produkte gibt, deren Gewicht noch rot (also unverändert) ist? Weil dafür ist die "Fehlermeldung" (die eher ein Hinweis ist) ja da.

Nein, die Produkte sind bereits abgewogen (Gewicht angepasst, Zeile ist nicht mehr rot).

**Comment by mrothauer** [comment]
hmmmm. schau mal in die datenbank, ob die spalte "mark_as_saved" in den bestellungen auch wirklich 1 enthält. das rot ist nämlich auch dann weg, wenn der wert ein anderer ist. ich hab mir bei der fehlermeldung / warnung den zweite fall gespart. es wird nur "mark_as_saved" überprüft.

**Comment by mantensteiner** [comment]
Die Spalte "mark_as_saved" ist für alle Datensätze 0 (was mich auch schon verwundert hat). D.h. das Problem tritt vermutlich auf dem Versuch den Wert auf 1 zu setzen. Die Bestellung in der Liste wird dann aber schon grün markiert.

**Comment by mrothauer** [comment]
`bin/cake cache clear_all` könnte nach der migration auch notwendig sein fällt mir grad ein.
dann sollte eigentlich alles klappen.

**Comment by mrothauer** [comment]
Wenn dir das Verhalten nicht klar sein sollte, kannst du es auf der demo-de.foodcoopshop.com Seite testen. Da funktioniert alles.

**Comment by mantensteiner** [comment]
Super, schaut nach einem ersten Test gut aus nachdem ich `bin/cake cache clear_all` ausgeführt habe! 

 Vielen Dank für deine Hilfe und schönen Abend noch!

LG

**Comment by mrothauer** [comment]
Super. Gerne, dir auch einen schönen Abend!
