### ISSUE TITLE
Sofort-Bestellung mit vielen Produkten: In den Warenkorb wird nicht angezeigt

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#650]
Weil die Liste zu lang ist... Beim normalen Bestellen funktioniert es, dann kommt eine Scrollbar.

**Comment by mrothauer** [comment]
https://github.com/foodcoopshop/foodcoopshop/commit/0709d8bd2ffbefe6791cb26d4b3434e82eb6bf40

**Comment by pabneukistl** [comment]
Verhalten tritt aktuell wieder auf.
verwendeter Webbrowser: Google Chrome Version 96.0.4664.110
UseCase:
Angemeldet als Admin - Bestellungen - Sofort-Bestellung für heute - anderen Benutzer auswählen - so viele Produkte in den Warenkorb legen dass über die Seite hinausgeht
NOK: es wird kein Scrollbalken angezeigt und der Button "Warenkorb anzeigen" ist nicht mehr sichtbar und kann nicht geklickt werden
-> möglicher Workaround: rechts in die Liste der Produkte im Warenkorb klicken, solange die Tabulator-Taste klicken bis der Fokus auf dem Button "Warenkorb anzeigen" liegt und Enter klicken

**Comment by mrothauer** [comment]
screenshot bitte danke!

**Comment by pabneukistl** [comment]
![Screenshot](https://user-images.githubusercontent.com/90574232/147765315-df1e213f-6586-4721-badb-d4bafebb7a19.JPG)

**Comment by mrothauer** [comment]
sollte wieder passen
lg
mario
https://github.com/foodcoopshop/foodcoopshop/commit/375333d3a843bdc4aeb47406719170e034794ff1
