### ISSUE TITLE
translate french

### ISSUE THREAD

**Issue by yvoeg** [foodcoopshop/foodcoopshop#670]

**Comment by mrothauer** [comment]
Hi,
I prepared a branch for you:
https://github.com/foodcoopshop/foodcoopshop/tree/feature/issue-670-french-translation

Please go ahead and fork the foodcoopshop/foodcoopshop repository (click on "Fork" button in top right corner).
Then continue with the docs: https://foodcoopshop.github.io/en/translating.html

When you translate all the files create a pull request (PR).
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

If thats too complicated for you, let me know. We'll find another solution.

Happy translating!

**Comment by mrothauer** [comment]
Hi @yvoeg 
I see that you are working on the translation, please be aware not to work on the develop branch of your fork, but on the branch I prepared for you. This branch has all the files you need for translating:
https://github.com/yvoeg/foodcoopshop/tree/feature/issue-670-french-translation
