### ISSUE TITLE
Bestellen zum Einkaufspreis / Nullpreis

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#672]
* Bestimmte Nutzer (z. B. der Betreiber selbst) sollen im Einzelhandels-Modus zu Einkaufspreisen einkaufen können, die Umsatzsteuer für den Eigenverbrauch ist sonst höher als notwendig.
* Lagerprodukte werden über bestimmten User vorbestellt: Einkaufen zum Nullpreis ermöglichen (Produkte würden sonst zweimal verkauft werden
* Auf bereits getätigte Bestellungen soll die Änderung des Dropdowns keine Auswirkung haben => man müsste die Bestellungen stornieren, dann den Wert ändern und dann neu bestellen.

**Infos**
*  Umbuchen ist nicht sinnvoll - bleibt aber erst mal ungesperrt
* Bei Bestellungen zu Einkaufspreisen weicht gerade bei Anzahl > 1 ab und zu der gespeicherte EP und VP (Gewinnansicht) um ein paar Cent voneinander ab. Das liegt vermutlich an Rundungsdifferenzen beim Umrechnen von EP / brutto / netto. Wird erst mal ignoriert :-)

**erledigt**
* [x] Ist die ausgewiesene USt. im Warenkorb korrekt? Nein, aber sie wird korrekt gespeichert. Kann also ignoriert werden.
* [x] Einkaufen zum Nullpreis umsetzen
* [x] Docs updaten
* [x] Gewinn-Übersicht: -0.00 auf 0.00 ändern (damit die Zeile nicht durchgestrichen ist)
* [x] Bei Bestellungen zu Nullpreisen auch den Einkaufspreis auf 0 setzen
* [x] Discount und Discount-Wording überall weg (auch db feld): Default für neues feld: "SP" für selling price
* [x] Hinweis im Warenkorb anzeigen
* [x] Selbstbedienung mit Gewicht testen
* [x] Pfand: Bei Nullpreis 0, bei EP normaler Pfand
* [x] Neues Feld in fcs_users: discount: varchar(3) values: PP, 0-100
* [x] Unit-Test testFinishCartWithPricesArePurchasePrices: Preis nach Gewicht: Abweichung EP / VP netto (Gewinnansicht)
* [x] Neues Feld in fcs_order_details: discount in fcs_order_details mitspeichern
* [x] Neues Dropdown im User-Profil: Optionen "Bestellen zum Einkaufspreis", "Bestellen zum Nullpreis (Vorbestellung von Lagerware)", evtl. auch 10% - 90% Rabatt? / Initialwert = Verkaufspreis, Dropdown-Anzeige an EP-Einstellung koppeln
* [x] Validierung
* [x] Ausgewählter Rabatt in der Kunden-Liste im Admin anzeigen
* [x] Einkaufspreis an Einstellung koppeln?
* [x] Nullpreis + Prozente an Einzelhandelsmodus koppeln
* [x] Frontend-Preise: Ohne Varianten / Preis pro Einheit / x %
* [x] Frontend-Preise: Ohne Varianten / Preis nach Gewicht / x %
* [x] Frontend-Preise: Ohne Varianten / Preis pro Einheit / EP
* [x] Frontend-Preise: Ohne Varianten / Preis nach Gewicht / EP
* [x] Frontend-Preise: Alles dann auch mit Varianten
* [x] Steuer überall ok (VP-Steuer auf EP-Netto)?
* [x] Beim Bestellen neue Preise speichern: Preis nach Einheit / Nach Gewicht, Basis-Preis auch extra speichern (für spätere Gewichts-Anpassung)
* [x] Was tun, wenn EP ausgewählt ist, aber kein EP angegeben ist? Default VP
* [x] Neue Preise auch auf der Warenkorb-Übersichtsseite

**Comment by pabneukistl** [comment]
Ergänzung zum Todo1: Neue User-Einstellung im Profil (nur von Superadmin sichtbar): Preis-Dropdown: Einkaufspreis / Verkaufspreis
-> **Initialwert = Verkaufspreis**
-> hier die Möglichkeit zum "Nullpreis-Einkauf" gleich mittels drittem Dropdownwert "Nullpreis"oder "100% Rabatt" oä. umsetzen? Dann brauchts kein eigenes neues Feld? Bzw. wenn man alles über dieses Dropdownfeld laufen lassen würde, könnte man zB mal für eine Erweiterung kA -10% Einkauf auch das Feld dann nehmen?

Todo 4 und 5: was genau wäre da ein Problem, hätte jetzt bisschen nachgedacht drüber aber da bin ich jetzt zuwenig im Detail drin?

Was mir noch einfällt zum Überlegen: Thema Pfand? Würd ich jetzt so verstehen, dass bei Nullpreis-Bestellungen Pfand auch alles unter 0,- laufen sollte, bei allen anderen Bestellungen (EK/VK-Preise) sollte immer normaler Pfandwert sein, der würd sich in dem Fall nicht ändern.
