### ISSUE TITLE
Hersteller über Sofortbestellungen informieren 

### ISSUE THREAD

**Issue by gueterwege** [foodcoopshop/foodcoopshop#69]
Produzent/innen sehen nicht, wenn eine Sofortbestellung gemacht wurde. Beispiel: Heute hat beim Fairteiler jemand einen Spargel storniert obwohl wir ihn geliefert haben. softwareempfehlung: spargel stornieren und dann via Sofortbestellung über den Vereinsaccount zu bestellen. Als Produzent/in muss ich dann im Herstelleraccount unter Bestellungen nachsehen ob die Artikel nachbestellt/sofortbestellt wurden, zur Kontrolle. super wäre wenn da auch eine mail kommt wie bei den nullpreisprodukten bzw. stornierungen wo die produzent/innen ja auch per mail informiert werden. 
oder:
Wir haben einen Lagerbestand von 5 Hanfnudelpackungen. Jemand macht eine Sofortbestellung von 5 Packungen und der Produzent bekommt das nicht mit und weiß somit nicht, dass keine Artikel mehr im Lager sind.
So wie ich das verstehe, wird die Sofortbestellung mit dem Datum rückdatiert, daher bekommen die Produzent/innen keine Nachricht über die Bestellung. Wäre sehr wichtig, denn die Prouzent/innen sollten erfahren, wenn jemand ein Produkt von ihnen kauft.
Daher unsere Frage. Mit welchen Aufwand ist es möglich, dass die Produzent/innen eine Mail bekommen wenn jemand eine Sofortbestellung macht?

**Comment by mrothauer** [comment]
Ich würde vorher gerne noch wissen, wann ihr Sofort-Bestellungen verwendet. Beim Fairteiler - soweit ich weiß:
* Um Lager-Produkte zu bestellen (z.B. Säfte, Äpfel)
* Um Fehler beim Abholen auszugleichen (Stornierung beim Mitglied und neue Sofort-Bestellung vom Fairteiler-Konto) - damit das Mitglied nicht zahlt und der Hersteller das Geld bekommt.

**Überlegungen**
* In einer Bestellung (auch Sofort-Bestellung) können ja mehrere Produkte auf einmal bestellt werden, also auch mehrere (verschiedene) Produkte vom gleichen Hersteller. Der Hersteller dürfte dann aber pro Sofort-Bestellung nur eine E-Mail bekommen, mit einer Auflistung der aller Produkte, die von ihm bestellt wurden. Sonst bekommt er wieder viele E-Mails - das würde ich gern vermeiden.
* Eine Kopie der Bestell-Bestätigung des Mitglieds kann er nicht bekommen, weil das auch eventuell Produkte anderer Hersteller drin sind, dh. es muss eine neue E-Mail-Vorlage erstellt werden.
* Es gibt bestimmt Hersteller (z.B. bei uns Äpfel-Lieferant), die diese E-Mails nicht bekommen möchten - sie sollte also für jeden Hersteller auch deaktivierbar sein - oder?

Fällt euch noch was dazu ein?

**Comment by gueterwege** [comment]
wann verwenden wir sofortbestellungen: wie bei euch
überlegungen: ja, ich denke benachrichtigung wollen alle die, die auch bestellbenachrichtigung wollen. könnte man koppeln. 
mehr morgen,

**Comment by gueterwege** [comment]
zu den vielen mails. bei nullpreisprodukten/preisänderungen bekommt man ja auch pro produkt eine mail. ich finde das passt schon wenn man da auch mehrere mails bekommt. es ist ja im sinne des herstellers. und löschen ist wirklich nicht umständlich. 

und ja, scheinbar wieder notwendig dass das deaktivierbar ist. finde ich aber dass man wieder koppeln kann, weil apfellieferant will ja garkeine mails, also entweder alles oder nichts.
