### ISSUE TITLE
AP08: Lagerbestand für Lagerprodukte steuern

### ISSUE THREAD

**Issue by gueterwege** [foodcoopshop/foodcoopshop#70]
wir haben einige produkte im abhollager auf lager. der lagerbestand lässt sich derzeit nur schwer mithilfe der software managen. gut wäre eine neue Rubrik mit Lagerbestand. Weil: Wenn die rubrik Anzahl null ist, dann kann nicht mehr bestellt werden. Das ist für die Lagerbestandleute schlecht, weil sie würden ja eh rechtzeitig die fehlenden Produkte nachbringen. dass bei anzahl null nicht bestellt werden kann ist für Gemüse aber gut, weil wenn nicht mehr als 2 Kohlrabi da sind, dann sollen auch nicht mehr als zwei bestellt werden können. mit einer zweiten rubrik könnten wir beides haben.

super wäre auch ein warnmail an Produzent/innen wenn Lagerbestand leer ist.

**Comment by k-pd** [comment]
A well-known feature in many shops: Sell product if not on stock. Can be a bool value in product table.

Also a well-known feature using a bool value in product table: send eMail if product out of stock.

**Comment by mrothauer** [comment]
**1) sell product if not on stock**

i recommend using the existing column "Anzahl" for that and allow it to be negative, if the new option "sell product if not on stock" mentioned by @k-pd is set to true.

adding a checkbox "Allow further orders if quantity is set to 0" in the overlay where the "Anzahl" can be changed (Admin / Produkte). Maybe also add a maximum negative quantity (eg. -10). default to infinitive?

there are a some manufacturers that only have stock products. a new manufacturer option should define the default value for the new option for all products of a specific manufacturer. so new products do not need to be changed and adding the new option can not be forgotten.

**todos**
* CartsController (including CartsControllerTest, write new Test for the new option!)
* New migration for field in table product "sellProductIfNotOnStock", eventually remove unsigned flag from table StockAvailable.quantity - can be negative
* Add new flag in amount overlay
* Add manufacturer option (saved as json - no migration needed)
* Add default value in database configuration


**2) send email if product out of stock**

after implementing 1) it should be relatively simple to trigger an email to the manufacturer if the quantity is 0 (in CartsController)

**Comment by k-pd** [comment]
At 2): Do not test for 0, must be first time quantity becomes <= 0.

**Comment by gueterwege** [comment]
Hi sorry, i was on holiday. all very very good

versteh ich nicht: "there are a some manufacturers that only have stock products. a new manufacturer option should define the default value for the new option for all products of a specific manufacturer. so new products do not need to be changed and adding the new option can not be forgotten"

**Comment by mrothauer** [comment]
Manche Hersteller haben nur Lagerprodukte. Es sollte also für Hersteller eine neue Option "ich bin ein Lagerprodukt-Hersteller" geben. Diese neue Option legt für neue Produkte dieses Herstellers automatisch fest, dass das neue Produkt die Einstellung "Produkt bestellbar, wenn nicht auf Lager" bekommt. Wie beim dem Standard-Steuersatz, der dem Hersteller zugewiesen werden kann, der dann auch genau diese Einstellung auf neue Produkte dieses Herstellers übernimmt. So kann das bei neuen Produkten nicht vergessen werden.
