### ISSUE TITLE
Seiten mit vielen Produkten sind langsam

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#700]
* [x] Daten für Produkt-Listen cachen (Nach Kategorie / Hersteller)
* [x] dom size verringern (eg. product-wrapper => pw) - auch css und js anpassen.
* [x] Menüs cachen - Die Zahlen in Klammer sind bei vielen Produkten ein Performance-Killer (Hersteller, Kategorien)
* [x] Cake Cache aktivieren für Debug = false (production)
* [x] redis server installieren
* [x] default filecache auf redis cache umstellen
* [x] für production dynamische generiertes JS-File /js/localized-javascript.js cachen und mit packen
* [x] achtung. session-handling nicht auf 'cache' umstellen, weil sonst fliegen alle user raus bei cache::clearAll!
* [x] unterschied zwischen redis und filecache minimal => filecache verwenden (keep it simple)
* [x] Cache::ClearAll als Trait nach AfterSave / AfterDelete
* [x] Mehr Datenbank-Indizes setzen
* [x] anzahl ändern bei variante triggert cache löschen nicht: saveMany statt updateAll verwenden: $this->ProductAttributes->StockAvailables->updateAll($product[$productId], [
* [x] ist cache nach bestellen gelöscht? NEIN. stock available ändert sich: auch in CartsComponent saveMany statt updateAll verwenden
* [x] Changelog

**Comment by pabneukistl** [comment]
temp QS-Feedback:
bisher OK getestet bei Änderung der Produkte als Admin und Suche der Produkte unangemeldet oder mit Kunden-Login auf der "normalen" Bestellseite oder auch SB-Modus: oder Lagerprodukte bestellen als Admin
- Änderung Lagerprodukt/Nicht-Lagerprodukt
- Änderung verfügbare Anzahl
- Änderung zusätzliche Kategorie für das Produkt
- Änderung Produktname
- Änderung Einheit
- Änderung Kurze Beschreibung
- Änderung Lange Beschreibung
- Änderung Produktbild
- Änderung Preis
- Änderung/Hinzufügen Varianten
- Änderung Hersteller-Daten (Logo, Name)
- Eingabe Lieferpausen für Hersteller
- Änderung Lieferrythmen für Produkt
- Eingabe Lieferpause für den Onlineshop
-> Produktdaten werden immer korrekt angezeigt, auch Mengenangaben in Klammern in den Kategorien korrekt
-> Performance ist deutlich besser!! Sowohl bei Eingabe im Suchfeld als auch Öffnen von Kategorien auch mit zB vielen Produkten.
