### ISSUE TITLE
"Bestelllisten prüfen Produkt/Mitglied" funktioniert nicht

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#724]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug

* FoodCoopShop Version: v3.2.2
* Browser und Betriebssystem / Browser and Operating System: FIREFOX, multiple Windows 7/10
* Platform and Target: nginx, mariadb, arch linux

### Was hast du gemacht? What you did?
Im Adminbereich, unter Hersteller, bei "Bestelllisten prüfen" entweder auf "Produkt" oder "Mitglied" geklickt.

### Was ist passiert? What happened?
Allgemeine Shop Fehlermeldung wird angezeigt.

### Was sollte passieren? What you expected to happen?
Anzeige der Bestellungen.

Hi, 
ich habe ein Problem mit meinem Shop. Ich glaube ja nicht mal, dass es wirklich ein Bug ist sondern eher ein Fehler auf meinem Server. 
Ich habe bereits in meine Logs geguckt und dort dieses gefunden:

2021-10-18 23:15:52 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1630 FUNCTION shop.DATE_FORMAT does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual in /srv/http/shop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
- /srv/http/shop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:39
- /srv/http/shop/src/Model/Table/ManufacturersTable.php:537
- /srv/http/shop/src/Lib/PdfWriter/OrderListPdfWriter.php:58
- /srv/http/shop/plugins/Admin/src/Controller/ManufacturersController.php:637
- /srv/http/shop/plugins/Admin/src/Controller/ManufacturersController.php:596
- /srv/http/shop/vendor/cakephp/cakephp/src/Controller/Controller.php:531
- /srv/http/shop/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:151
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/BaseApplication.php:313
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Runner.php:77
- /srv/http/shop/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:161
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /srv/http/shop/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:77
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /srv/http/shop/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php:57
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /srv/http/shop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:126
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Runner.php:58
- /srv/http/shop/vendor/cakephp/cakephp/src/Http/Server.php:90
- /srv/http/shop/webroot/index.php:40

Request URL: /admin/manufacturers/getOrderListByProduct.pdf?manufacturerId=2&pickupDay=23.10.2021
Referer URL: https://shop.xxx.de/

Eine Idee dazu?
Danke und Grüße

**Comment by mrothauer** [comment]
Hallo @Confuset,

> 1630 FUNCTION shop.DATE_FORMAT does not exist

Die Funktion fehlt bei deinem MySQL- / MariaDB-Server. Kannst du sie irgendwie nachinstallieren? Genauer kenn ich mich da leider auch nicht aus, ich lese die Fehlermeldung zum ersten Mal. Auf ganz vielen anderen Seiten müsste der gleiche Fehler auftreten, da ich die Funktion oft verwende.

**Comment by Confuset** [comment]
Ok. Ich habe es selbst fixen können. Nach Deiner Aussage bin ich nochmal auf Recherchetour gegangen und habe dieses hier gefunden:

https://debianforum.de/forum/viewtopic.php?t=174273

Danach habe ich ein wenig im SourceCode gesucht und bin hier fündig geworden:

`            ORDER BY {$orderClause}, DATE_FORMAT (od.created, '%d.%m.%Y, %H:%i') DESC;";
`

man beachte das Leerzeichen bei `DATE_FORMAT (`
Ich habe dann bei mir die Zeile geändert zu 
`            ORDER BY {$orderClause}, DATE_FORMAT(od.created, '%d.%m.%Y, %H:%i') DESC;";
`

Damit funktioniert es.

Datei: src/Model/Table/ManufacturersTable.php:534

Also doch ein Bug? ;-)

**Comment by Confuset** [comment]
Ja, ist schon ein wenig pingelig von mariadb aber was solls..
Ich hab mal eine Volltextsuche gemacht und nur diese Stelle gefunden. PR ist erstellt.
