### ISSUE TITLE
fix "line exceeds 120 characters" in git hook

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#73]
i recently installed stickler and stumbled across a fixable issue:
Line exceeds 120 characters; contains 156 characters

https://github.com/foodcoopshop/foodcoopshop/pull/72/files/219906b3dc379856f30b2c89a4c755dcb5f0b08e

could this be added to our pre commit hook?

**Comment by k-pd** [comment]
Adjusting the CodeSniffer config is no problem, but I didn't see a fixer for the issue. That means: if line length is exceeded, commiting is refused and manual change must be done. Which is, for the first introduction, a nightmare in terms of time consumption.

Why not tell stickler not to complain about line length? BTW: Stickler does no more than phpcs does...

**Comment by mrothauer** [comment]
fixed in #72
