### ISSUE TITLE
AP04: Vergangene Bestellungen in Warenkorb laden

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#74]
info von dax:

"Was wirklich helfen würde is a dauerbestellfunktion, also z.B i hob fix jede wochen mei brot, milch, gemüsekistl im warenkorb (außer i duas manuell außa) und bestell zusätzlich extraguzzis"

@gueterwege: vielleicht könnt ihr noch mehr infos dazuschreiben?

**Comment by tantelisl** [comment]
Vorschlag: Im frontend unter "In den Warenkorb" "Abonieren"
Rechts beim Warenkorb unter "Mein Guthaben" den Punkt "Meine Abos" Linka auf Backend mit den abonierten Artikeln zum deaktivieren oder löschen

Backend:
Unter Bestellungen ein Unterpunkt Meine Abos

**Comment by gueterwege** [comment]
vorschlag von tante lisl find ich gut bzw. denk ich stellen sich konsument/innen darauf ein
- hersteller sollten auch beim produkt anhaken können: abo möglich... bei saisonalen produkten 
- abo würde ich wöchentlich stornierung möglich machen, weil ich denk produzent/in bekommt sowieso wöchtenliche bestellmenge

**Comment by gueterwege** [comment]
in meiner vorstellung gliedern sich die abo bestellungen in den regulären bestelllisten der produzent/innen ein, das heißt ich würde auch abo optionen anbieten. zb. einmal im monat, oder alle zwei wochen.

**Comment by mrothauer** [comment]
Bei unserer letzten Plenumssitzung kam folgende Idee auf: Man kann bestimmte Produkte (inkl. Anzahl) "als Favorit markieren" (kleiner Button aus/an direkt beim Bestellen, kein Backend). Und dann wird in der Bestellerinnerungs-Email ein Link eingefügt: "Jetzt deine Favoriten in den Warenkorb laden". Es werden dann alle meine Favoriten in den Warenkorb gelegt und ich muss nur noch auf "Zahlungspflichtig bestellen" klicken (und natürlich die Hakerl setzen).

**Vorteile**
- Es passiert keine Bestellung automatisch (Abos haben das Problem, dass evtl. mal bestellt wird, obwohl man das gar nicht will).
- Keine zweigleisige Bestell-Logik (Abo vs. "normales" Bestellen)
- Man kann seinen Warenkorb noch anpassen
- Einfache Bestellung des "Notwendigsten", für Leute, die am Abend noch schnell bestellen wollen, aber eigentlich gar keine Zeit dafür haben :-)

Eventuell gibts auch noch irgendwo am Frontend einen Button "Favoriten in den Warenkorb laden", sodass diese Funktion nicht nur aus der E-Mail heraus aufgerufen werden kann.

**Comment by gueterwege** [comment]
hallo, bin ganz bei euch, dass diese funktion im mail wichtig ist, am frontend zweitrangig. hab andi das thema weitergeleitet, mal sehen was er sagt, schließlich kommt die bitte von ihm.

**Comment by SaibotP** [comment]
Ich finde das ganz toll, würde aber unbedingt darauf achten, dass man den Warenkorb noch anpassen kann. Ich würde mir auf jeden Fall wünschen, dass man verschiedene Gruppen von Favoriten anlegen kann (die man selbst benennen kann): 1-wöchig, 2-wöchig, Sommer (Gemüse), Herbst, Kekse-Backen etc. Dann kann man sich beliebige Warengruppen anlegen und mit einem Mausklick laden.
Was passiert, wenn Produkte einer Gruppe gerade nicht oder gar nicht mehr verfügbar sind? Stehen sie mit 0 im Warenkorb? Bekommt man eine Meldung. Das wäre schon wichtig. Damit ich das auch wirklich mitbekomme und alternative Produkte bestellen kann.

Liebe Grüße,

Tobias
