### ISSUE TITLE
Automatisierter Urlaubsmodus für Hersteller

### ISSUE THREAD

**Issue by tantelisl** [foodcoopshop/foodcoopshop#75]
Funktion: Zeitraum festlegen können wann der Urlaub beginnt und endet, also wann der Hersteller bzw. die Produkte automatisch deaktiviert und nach dem Urlaub aktiviert werden sollen.

Die gleiche Logik auch für den gesamten Shop zum automatischen deaktivieren und aktivieren mit Zeitraumeinschänkung. Derzeit hier einstellbar: (Einstellungen/Bestellfunktion aktiviert)

**Comment by gueterwege** [comment]
find ich suuuuper idee. es wäre gut wenn ich beim aktivieren den aktivierten zeitraum auf endlos oder limitiert angeben kann. 
wenn bestellfunktion aktiviert geklickt, könnte sich fenster mit kalender öffnen

**Comment by mrothauer** [comment]
vielleicht bekomm ich ja feedback, auf der demo-seite könnt ihr euch den verbesserten urlaubsmodus anschauen:
https://demo.foodcoopshop.com/admin/manufacturers
email: fcs-demo-admin@mailinator.com
passwort: foodcoopshop

dann auf bearbeiten klicken

**Comment by mrothauer** [comment]
das issue für das aktivieren / deaktivieren vom ganzen shop (wenn die foodocoop urlaub macht) befindet sich hier: #80 das ist noch nicht umgesetzt

**Comment by gueterwege** [comment]
hallo, hab mir die demo version angesehen, und hätt tatsächlich noch ein kommentar. denn jetzt kann man angeben wann der hersteller auf urlaub geht. bei unserer foodcoop haben wir gerade das umgekehrte problem. und zwar vergessen die hersteller mit eingeschränkten bestellzeiten oder sammelbestellungen immer wieder ihre produkte offline zu stellen. dafür würden wir es derzeit dringender benötigen.das heißt es wäre gut wenn bei aktiv genau die selben dinge auszuwählen wären wie bei urlaubsmodus. und zusätzlich ein hakerl mit immer aktiv. wenn hakerl an, dann keine datumsauswahl möglich. wenn bei immer aktiv kein hakerl, dann datumsauswahl.

**Comment by mrothauer** [comment]
@gueterwege ja das ist ein eigenes thema... bitte erstelle ein eigenes issue dafür. danke!
