### ISSUE TITLE
Preis je Stück

### ISSUE THREAD

**Issue by hasslerf** [foodcoopshop/foodcoopshop#751]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Vorschlag für neue Funktion / feature-discussion (RFC)

### Was hast du gemacht? What you did?
Wenn kleine Landwirte Eier verkaufen kommt es vor, dass die Hendl mal nicht so viel legen. Wenn die Landwirte dann gerne die Eier auf die Bestellungen aufteilen, erhalten manche Menschen dann nur noch 9 oder 8 Eier.

### Was sollte passieren? What you expected to happen?
Gleich wie der `Preis nach Gewicht (für Gewichtsanpassung nach Lieferung)` wäre in diesem Fall ein `Preis je Stück` praktisch, damit die Ladenhüter:innen den Preis bei der Abholung anpassen können.

### Disclaimer
Wenn dieses Verhalten mit den Bordmitteln möglich ist bitte mich aufzuklären und das Issue discarden, thx.

**Comment by mrothauer** [comment]
Hallo, @hasslerf,
dafür gibts keine eigene Funktion. Ich würde das einfach so lösen:
* Preis ausrechnen und ändern (Stift links neben Preis, auf der gleichen Seite wo auch das Gewicht eingetragen werden kann).

Es gäbe dann noch die Möglichkeit, Eier einzeln zu bestellen und dann über die Funktion "Anzahl ändern" ein Ei wegzugeben, dann müsste man nichts rechnen... Aber es könnten dann halt auch z.B. 7 Eier bestellt werden. Drum würde ich das nicht machen.

Ich sehe da keinen Bedarf einer neuen Funktion.
