### ISSUE TITLE
Migrations Tablenamen sind hardcoded

### ISSUE THREAD

**Issue by reicharm** [foodcoopshop/foodcoopshop#761]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.3
* Browser und Betriebssystem / Browser and Operating System: Windows 10

### Was hast du gemacht? What you did?
Wollte auf einer Testinstanz (selber Server, selbe Datenbank - unterschiedliche Tables, bzw unterschiedliche Tableprefixes), eine neue Version des Foodcoopshop testen/uggraden

### Was ist passiert? What happened?
Die Migrations verwenden allerdings die "original" Tablenamen hardcoded => die Migrations wurden auf die produktiven Tables durchgeführt und nicht auf die vorgesehene Testinstanz.

### Was sollte passieren? What you expected to happen?
Nur die Tables, die auch lt Config-File verwendet werden, sollten migriert werden!

Wichtig wäre zumindest ein entsprechender Hinweis bei den Entwickler-Anleitungen - hier kann ein nicht unwesentlicher Datenverlust entstehen (bei uns konnte ein Backup eingespielt werden - ist aber natürlich trotzdem ein zusätzlicher Aufwand).

**Comment by reicharm** [comment]
Versteh ich grundsätzlich, dass du das nicht unbedingt ändern willst - aber änderbar ist es in der custom-config.php ganz leicht (sonst hätte ich es auch nicht getan): https://github.com/foodcoopshop/foodcoopshop/blob/64672832613232047c030782cfc164959411d192/config/custom_config.default.php#L45 

Aber wenn ich jetzt weiß, dass das zu Problemen führt, werd ich das in Zukunft anders handhaben ...

lg
Michi

**Comment by mrothauer** [comment]
Ah daher hast du das :-) Ich glaub, das ist ein Überbleibsel von CakePHP 2, da gabs noch ein prefix-Config. Es dürfte aber aktuell keine Auswirkungen haben, wenn du das Präfix änderst und gehört eigentlich aus der custom_config.default.php gelöscht. Kannst du das bestätigen und evtl. gleich mit machen bitte? Also das Löschen.
