### ISSUE TITLE
Bei Änderung Anzahl/Preis einer Variante werden manchmal Varianten anderer Produkte fehlerhafterweise mitgeändert

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#765]
Es ist ja schon paarmal aufgefallen, dass bei Änderung eines EK-Preises einer Variante fehlerhafterweise die Varianten anderer Produkte/des gleichen Produktes auf den selben Preis mitgeändert wurden. War aber bisher nicht reproduzierbar/auffindbar.
Habe bei mir im System nun einen reproduzierbaren Fall bei dem die Änderung der verfügbaren Anzahl einer Variante die Anzahl der zweiten Variante beim selben Produkt mitändert:
Vorgehensweise:
-Admin-Bereich - Hersteller - Klick auf Button Produkte beim Hersteller "Bio-Kräuterhof Aufreiter"
-die beiden Varianten des Produktes steht zB bei aktueller Lagerstand 0
-aktuellen Lagerstand der ersten Variante "70g" die Anzahl auf 2 ändern, Speichern
-> IST: es wird die verfügbare Anzahl BEIDER Varianten des Produktes auf 2 gesetzt -> NOK
-> SOLL: nur die Variante "70" sollte auf 2 gesetzt werden, die anderen Variante soll auf 0 bleiben

Vielleicht hilft dieser Fall das Problem dieser manchmal ungewollten "Mehrfachänderungen" zu finden

**Comment by mrothauer** [comment]
war ein problem, das sich durch die cache-umstellung #764 eingeschlichen hat
