### ISSUE TITLE
Fehlerhafter Bon-Druck bei Kunde=Admin

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#766]
Voraussetzungen:
System mit HelloCash-Aktivierung
Kunde A = Gruppe "Admin"
UseCase:
Kunde A in Selbstbedienung anmelden
Produkte bestellen -> Klick auf Abholung abschließen
-> IST: anstelle eines korrekten Bons wird nur die Übersichtsseite der Selbstbedienung gedruckt -> NOK
-> SOLL: es soll der korrekte Bon gedruckt werden
Info: bei allen anderen Gruppen Kunde = Superadmin/Kunde/SB-Kunde funktioniert der Bondruck korrekt

**Comment by mrothauer** [comment]
gruppe admin ist eigentlich für abholdienst bei foodcoops gedacht und hat bei dorfläden gar keinen sinn, drum hab ich die prüfung da weglassen
jetzt funktionierts auch mit admin
