### ISSUE TITLE
EAN-13 für variable Gewichts- und Preiseinheiten

### ISSUE THREAD

**Issue by toblinga** [foodcoopshop/foodcoopshop#776]
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

### Was sollte passieren? What you expected to happen?
Es sollen EAN-Codes mit Geiwcht scannbar sein

Siehe https://docplayer.org/28990861-1-ean-13-fuer-variable-gewichts-und-preiseinheiten.html

**Comment by mrothauer** [comment]
#1019
