### ISSUE TITLE
Rabatt auf Ganze Rechnung

### ISSUE THREAD

**Issue by toblinga** [foodcoopshop/foodcoopshop#780]
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)
Es soll möglich sein auf die ganze Rechnung einen Prodzentsatz an Rabatt zu geben.
Achtung: bei diesem Vorgang müssen alle Verkaufspreise einteln Rabattiert werden, da es sont mit der UST nicht passen könnte. Sprich ein Produkt mit -xx€ ist zu wenig.

**Comment by mrothauer** [comment]
moved to #782
