### ISSUE TITLE
Rabatt auf Produkt

### ISSUE THREAD

**Issue by toblinga** [foodcoopshop/foodcoopshop#781]
* [X ] Vorschlag für neue Funktion / feature-discussion (RFC)
Es soll auf ein bestimmtes Produkt in der Einkaufstasche Rabatt (Prozentsatz), bzw. Produktpreis geändert werden können.
Vorschlag: Stift/Editbutton neben dem (x) "Produkt entfernen"-Button mit dem dann Ein Dialog geöffnet wird ähnlich dem Dialog (Preis / Gewichtanpassung) in der Bestellübersicht, jedoch beide Dialoge in einem, und ein Eingabefeld für Rabatt-Prozent Eingabe.

**Comment by mrothauer** [comment]
moved to #782
