### ISSUE TITLE
Integration Registrierkassa Start, Monats und Jahresbeleg

### ISSUE THREAD

**Issue by toblinga** [foodcoopshop/foodcoopshop#785]
Hallo,
wie wird aktuell der Monats und Jahresbelegt im Kassasystem (hellochash) angetriggert? Muss man sich dafür in Hellocash einloggen und dort den Monats/Jahresbeleg erstellen?

Das ist keine offizielle Stelle, aber hier finde ich ist es ganz gut und leicht verständlich zusammen gefasst:
https://offisy.at/ein-muss-der-monatsbeleg/

Hier eine etwas offiziellere Stelle, dass Start, Monats und Jahresbelege verpflichtend sind:
https://www.wko.at/service/steuern/pruefung-jahresbeleg-registrierkasse.html

**Comment by mrothauer** [comment]
Laut HelloCash-Hilfe funktioniert werden beide Belege vollautomatisch erstellt:

Jahresbeleg:
https://hellocash.at/faq/jahresbeleg-erstellung-mit-hellocash/11001

Monatsbeleg:
https://hellocash.at/faq/belegarten-im-rahmen-der-signaturpflicht/11959

**Comment by mrothauer** [comment]
Auch der Startbeleg wird automatisch erstellt.
