### ISSUE TITLE
migrations: automatisches anpassen von datenbank-dumps

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#79]
es wäre aber gut, wenn der structure-dump (Config/sql/_installation/clean-db-structure.sql) und auch Config/sql_installstions/clean-db-data.sql und Test/test_files/Config/sql/test-db-data.sql mitangepasst werden könnten, sodass sie immer das schema / die daten nach ausgeführter migration enthalten.

momentan mach ich das für die drei dateien bei jeder migration manuell über phpmyadmin => export (structure / daten) und das ist mühsam.

ein script , das auf Configure::read('app.mysqlDumpCommand') zugreift (gibts ja schon) und dann die dumps richtig anpasst, wär super! mit der migration / der migration range als parameter. kann gern manuell aufgerufen werden müssen, kein integration in pre-git-commit notwendig.

wichtig sind diese optionen beim export
* drop table if exists hinzufügen
* auto-increment wert weglassen
* nur struktur für struktur-dump
* nur daten für daten-dump
* fcs_configurations: FCS_DB_VERSION und FCS_DB_UPDATE updaten

**Comment by k-pd** [comment]
Du möchtest Dir das Erstellen der DB-Dumps ersparen? Ist bereits erspart für die Installation. Warum? Beim Setup wird die DB von V1.2 importiert und dann beim ersten Aufruf auf die aktuellste Version migriert. Keine Dumps mehr nötig.

Aktuellere Dumps braucht es also nur für die Test-Daten. Ein Skript, dass die bisher manuellen Dumps erstellt, wäre gut machbar.

Bei den Developer-Skripten bin ich in der Regel dafür, nicht die Application-Infrastructure zu verwenden. Für geeigneter halte ich ein PHP oder Shell-Skript in devtools/ oder vendor/bin/ für solche Sachen.

Was ich nicht ganz verstehe ist die Sache mit den Parametern. Du änderst für neue / modifizierte Tests die Test-DB bis alles läuft. Dann machst Du einen DB-Dump von der Test-DB. Das sollte doch schon reichen.

**Comment by mrothauer** [comment]
1) Verstanden, das funktioniert auch super.

2) Genau. Die Test-DB besteht aus clean-db-structure.sql und dump (Pfade siehe Kommentar 1), ich verwende structure 
aber (und clean-db-data.sql) aber auch für Neuinstallationen, darauf könnte der Installer auch zugreifen. Und genau die sollten immer aktuell sein (damit man evtl. ganz alte Migrations auch mal löschen kann).

3) Vendor/bin find ich gut, vielleicht könnte man bei der Gelegenheit auch gleich den Inhalt des Ordners devtools dorthin verschieben. Das würde das Root überschaubarer machen und alles wär an einer Stelle.

4) Wenn ich für einen Test neue Test-Daten benötige, ist das Vorgehen wie gehabt: Frischen Dump einspielen, Test-Daten eintragen bis alles läuft, Dump exportieren, einchecken. Es geht darum, die Migrations in die Test-DB automatisiert zu integrieren. Das Skript sollte also clean-db-structure.sql einlesen, die übergebene(n) Migration(s) darauf ausführen und mit den in Kommentar 1) erwähnten Optionen den Dump wieder exportieren. Das Gleiche auch für Test-Data, weil wenn man zB. in einer Migration ein Feld löscht, dann funktionieren die INSERTS im Data-Dump nicht mehr.

Also: Ziel ist, die Migrations über ein (oder mehrere) Skript(s) in clean-db-structure.sql, clean-db-data.sql, und test-db-data.sql zu integrieren.

**Comment by k-pd** [comment]
Zu 2: Kann auch ein Dump-Skript für die Installationsdaten erstellen. Aber siehe dazu ganz unten...

Zu 3: in devtool/ liegen auch nicht-ausführbare Dateien. Vendor/foodcoopshop dafür?

Zu 4. Mir leuchtet noch immer nicht ein, wie Du einen Vorteil erhalten willst bzw. wo die Optionen sinnvoll wären. Ich mache echt sehr ungern Arbeit, die dann keiner gebrauchen kann...

Du erstellst eine Änderung mit DB-Migration. Die Migration wird auf die DB angewendet, sobald die Webseite aufgerufen wird. Daraus erstellst Du mit meinem neuen Skript (aus 2.) die DB-Struktur und die DB-Daten für die Installation.

Soweit, so gut. Nun kommt das, wo ich keinen Vorteil bzw. Bedarf an Optionen sehe: Ich gehe davon aus, dass Deine Test-DB auf dem Stand des letzten ausgeführten Tests der Version ist, auf dem Deine Änderung aufbaut (branch base). Wenn das nicht der Fall ist, Import beider Test-DB SQL-Dumps durch Starten eines beliebigen Tests. Der geht schief, aber die Dumps sind in der DB.

Bevor Du nun die Test-Daten der Test-DB ändern kannst, muss die DB-Migration auch auf die Test-DB anwendet sein. Dazu führst Du das Migration-SQL einfach direkt auf der DB aus (per Kommandozeile oder über Dein Tool, mit dem Du die Test-Daten änderst). Dann ist die Test-DB auf dem Stand, den Du brauchst. Nun einmal Test-DB und Test-Daten dumpen, von mir aus mit einem weiteren Skript wie in 2. Und wenn Deine Test-Daten dann fertig sind, nochmal Dumpen. An welcher Stelle liege ich falsch, so dass irgendwelche Optionen Sinn machen?

Schon das Dumpen der Installations-SQLs zu automatisieren macht eigentlich keinen wirklichen Sinn, immerhin brauchst Du eine frische Installation dafür. Oder man muss die vorhandene DB überschreiben (samt Sicherungskopie des vorherigen Inhalts) und noch die Migration-SQL ausführen. Oder es muss extra eine DB dafür angelegt werden. All das ist im Verhältnis zum manuellen Dump in 10 Sekunden recht aufwendig. Das rohe SQL einlesen und selbst umzuschreiben ist utopisch.

**Comment by k-pd** [comment]
mysqldump erzeugt mir zwar die Struktur mit `DROP TABLE IF EXISTS`, aber bei den Daten kann es kein `TRUNCATE TABLE`. Das ist für die Test-DB ein Problem.

Ein weiteres Problem machen mir die Zeichensätze. Warum weiss ich zwar nicht, aber der Dump enthält keine korrekt encodierten utf-8-Zeichen. Vielleicht stimmt was nicht mit meiner MySQL-Installation, die ist seit 6 Jahren immer nur aktualisiert worden (damals war utf-8 noch nicht Standard).

Bitte probier mal, ob das Skript (gespeichert in devtools/) bei Dir überhaupt was tut.
```php
#!/usr/bin/env php
<?php
/**
 * Dump DB structure and data for installation
 */

if (!isset($argv[0])) {
	exit('Use from commandline only.');
}

if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}

echo 'Loading config...' . PHP_EOL;

// get the project dir from being in [project]/devtools/
$dir = dirname(dirname(realpath($argv[0]))) . DS;

// include DB config
include $dir . 'Config' . DS . 'database.php';

$db = new DATABASE_CONFIG();
if (!isset($db->default)) {
	exit('Cannot read Config' . DS . 'database.' . PHP_EOL);
}
$db_conf = $db->default;  // ease switching to Test-DB

if (!isset($db_conf['datasource'])
	|| $db_conf['datasource'] != 'Database/Mysql'
	|| !isset($db_conf['persistent'])
	|| $db_conf['persistent'] !== false
	|| !isset($db_conf['encoding'])
	|| $db_conf['encoding'] != 'utf8'
) {
	exit('Cannot use config in Config' . DS . 'database.php.' . PHP_EOL);
}

if (!isset($db_conf['prefix'])
	|| $db_conf['prefix'] != 'fcs_'
) {
	exit('Cannot use prefix from Config' . DS . 'database.php. Must use default fcs_' . PHP_EOL);
}

echo 'Host: ' . $db_conf['host'] . PHP_EOL;
echo 'Database: ' . $db_conf['database'] . PHP_EOL;
echo 'User: ' . $db_conf['login'] . PHP_EOL;
echo 'Password: ' . $db_conf['password'] . PHP_EOL;

echo PHP_EOL;
echo 'Reading dump command...' . PHP_EOL;

$dump_cmd = '';

$lines = file($dir . 'Config' . DS . 'app.config.php');
if (!is_array($lines)
	|| empty($lines)
) {
	exit('Cannot load Config' . DS . 'app.config.php.' . PHP_EOL);
}

foreach ($lines as $line) {
	if (($pos = strpos($line, '\'app.mysqlDumpCommand\',')) !== false) {
		$line = substr($line, $pos + strlen('\'app.mysqlDumpCommand\','));
		$line = explode('\'', $line, 3);
		$dump_cmd = $line[1];
	}
}

if (empty($dump_cmd)) {
	exit('Cannot read app.mysqlDumpCommand from Config' . DS . 'app.config.php.' . PHP_EOL);
}

if (strpos($dump_cmd, 'mysqldump') === false) {
	exit('Cannot use app.mysqlDumpCommand from Config' . DS . 'app.config.php. Must use mysqldump' . PHP_EOL);
}

echo 'Dump command: ' . $dump_cmd . PHP_EOL;

echo PHP_EOL;

echo 'Dumping structure...' . PHP_EOL;
$result = array();
$cmd = sprintf('%1$s --host="%2$s" --user="%3$s" --password="%4$s" --no-create-db --no-data --events --routines --skip-opt --add-drop-table --create-options --disable-keys --extended-insert --quick --set-charset --quote-names --skip-comments --skip-add-locks --single-transaction --force --result-file="%5$s" %6$s', $dump_cmd, $db_conf['host'], $db_conf['login'], $db_conf['password'], $dir . 'Config' . DS . 'sql' . DS . '_installation' . DS . 'clean-db-structure.test.sql', $db_conf['login']);
echo $cmd . PHP_EOL;
exec($cmd, $result);
foreach ($result as $line) {
    echo $line.PHP_EOL;
}

echo 'Dumping data...' . PHP_EOL;
$result = array();
$cmd = sprintf('%1$s --host="%2$s" --user="%3$s" --password="%4$s" --no-create-info --skip-opt --create-options --disable-keys --extended-insert --quick --set-charset --quote-names --skip-comments --skip-add-locks --single-transaction --force --result-file="%5$s" %6$s', $dump_cmd, $db_conf['host'], $db_conf['login'], $db_conf['password'], $dir . 'Config' . DS . 'sql' . DS . '_installation' . DS . 'clean-db-data.test.sql', $db_conf['login']);
echo $cmd . PHP_EOL;
exec($cmd, $result);
foreach ($result as $line) {
    echo $line.PHP_EOL;
}

echo 'Done.' . PHP_EOL;
```

**Comment by mrothauer** [comment]
der letzte parameter muss bei mir die datenbank sein und nicht der login name: $db_conf['database'], sonst bekomm ich eine fehlermeldung, dass die datenbank "benutzername" nicht existiert. wohlgemerkt: ich bin auf windows unterwegs.
dann hab ich die test-db von develop eingespielt und dein skript laufen lassen. als txt weil github lässt sql als endung nicht zu):
[clean-db-data.test.sql.txt](https://github.com/foodcoopshop/foodcoopshop/files/1083358/clean-db-data.test.sql.txt)
[clean-db-structure.test.sql.txt](https://github.com/foodcoopshop/foodcoopshop/files/1083359/clean-db-structure.test.sql.txt)

vielleicht ist das ein workaround für truncate table:
https://stackoverflow.com/questions/25778365/add-truncate-table-command-in-mysqldump-before-create-table-if-not-exist

**Comment by k-pd** [comment]
Sowas, der letzte Parameter sollte schon die DB sein. Ist bei mir identisch zum User, daher nicht aufgefallen. Sonst funktioniert es wohl. Auch der Zeichensatz passt. Dann mach' ich das mal weiter.

Den Rewrite mit `sed` hatte ich auch gefunden, aber sed unter Windows hat einige Unterschiede zum sed unter Linux. Daher würde ich eher in PHP arbeiten. Das ist aber auch nochmal einiger Aufwand...

PS: Das sind bisher schon 4h Arbeit...

**Comment by k-pd** [comment]
#82
