### ISSUE TITLE
Anzahl Produkte in Warenkorb/Einkaufstasche anzeigen

### ISSUE THREAD

**Issue by sttanja** [foodcoopshop/foodcoopshop#800]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

Vorschlag:
Im täglichen Doing habe ich öfter den Fall dass man zB gemeinsam mit einem Kunden eine Geschenkekiste zusammenstellt, dann öfter auch zwischenzeitlich bereits Produkte in der Sofort-Bestellung/Lagerprodukt-Bestellung erfasst um Zwischensummen zu haben, dann werden manchmal nochmal Produkte getauscht, etc.. 
Sind solche Geschenke dann fertig zusammengestellt prüft man natürlich nochmals die erfassten Produkte bzw. zähle ich in der Regel die eingepackten Produkte und die erfassten Produkte im Warenkorb nochmals durch um zu prüfen ob Anzahl gleich.
Super wäre es, wenn irgendwo zB am Ende des Warenkorbs/der Einkaufstasche die Anzahl der im Warenkorb/Einkaufstausche liegenden Produkte angezeigt wäre, dann hätte man die Anzahl der Produkte in der Liste gleich auf einen Blick und müsste diese nicht mehr extra durchzählen.

**Comment by mrothauer** [comment]
Also wenn man ein Produkt mehrmals bestellt, soll das dann auch die Gesamtanzahl mehrmals erhöhen, richtig?
Beispiel: 2x Apfelsaft (1 l) + 1x Birne = 3x Gesamt

**Comment by sttanja** [comment]
Genau!

**Comment by mrothauer** [comment]
Danke, ich erledige das demnächst.
