### ISSUE TITLE
Fehler beim ausführen von 'composer migrate'

### ISSUE THREAD

**Issue by aroscha** [foodcoopshop/foodcoopshop#817]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug

* FoodCoopShop Version: 3.3.0
* Browser und Betriebssystem / Browser and Operating System: Firefox 98.0.2 (64-Bit) Linux Arch
* Platform and Target: PHP 8.0, MySQL, manitu.de, phpMyAdmin 5.0.4, freiburg.vorratskiste.org

### Was hast du gemacht? What you did?
 Update von 3.3.0 auf 3.4.2 beim ausführen von `composer migrate`

### Was ist passiert? What happened?
Nach dem ersetzen des Source Codes beim ausführen von ` composer migrate` in in /foodcoopshop/ trat folgender fehler auf:

```
composer migrate
> bash bin/cake migrations migrate
Script bash bin/cake migrations migrate handling the migrate event returned with error code 255
```

### Was sollte passieren? What you expected to happen?
Das Upgrade Skript hätte ausgeführt worden sein um das Update ab zu schließen.

**Comment by mrothauer** [comment]
hmmm, probier mal 

`bin/cake migrations migrate && bin/cake migrations migrate -p Queue`

**Comment by aroscha** [comment]
Das führt leider zu gar keinem Output, hatte ich auchs schon probiert.

Vielleicht ist das noch spannend:

```
composer migrate -vvv
Reading ./composer.json (/home/sites/site100007377/web/fcs-main/foodcoopshop/composer.json)
Loading config file ./composer.json (/home/sites/site100007377/web/fcs-main/foodcoopshop/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): git branch -a --no-color --no-abbrev -v
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): hg branch
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): fossil branch list
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): fossil tag list
Executing command (/home/sites/site100007377/web/fcs-main/foodcoopshop): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /home/sites/site100007377/sshusers/ssh300000931/.composer/composer.json

Reading /home/sites/site100007377/web/fcs-main/foodcoopshop/vendor/composer/installed.json
Loading plugin Cake\Composer\Plugin (from cakephp/plugin-installer)
Running 2.1.3 (2021-06-09 16:31:20) with PHP 7.4.28 on Linux / 5.15.32
> migrate: bash bin/cake migrations migrate
Executing command (CWD): bash bin/cake migrations migrate
Script bash bin/cake migrations migrate handling the migrate event returned with error code 255

```

**Comment by mrothauer** [comment]
`Running 2.1.3 (2021-06-09 16:31:20) with PHP 7.4.28 on Linux / 5.15.32`

Vielleicht macht PHP 7.4 hier Probleme, es sollte PHP 8.0 sein

**Comment by mrothauer** [comment]
oder mit `composer self-update` zur Sicherheit nochmal die aktuellste Version installieren?

**Comment by mrothauer** [comment]
Hallo @aroscha 
kann ich noch helfen? Sonst würde ich das Issue in ein paar Tagen schließen.
