### ISSUE TITLE
Install vendor packages cake npm_post_install fails with error 255

### ISSUE THREAD

**Issue by sebarnd** [foodcoopshop/foodcoopshop#820]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.4.2
* Browser und Betriebssystem / Browser and Operating System:  FIREFOX 64 / Arch linux
* Platform and Target: Debian Bullseye (in Docker), Node 16
 
### Was hast du gemacht? What you did?
Ich habe den main brach geclont und ein Dockerfile mit dem inhalt: 
```Dockerfile
FROM php:cli AS php_build

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && install-php-extensions @composer intl gd zip

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

WORKDIR /var/www/html
COPY . .
RUN composer install
RUN npm --prefix ./webroot install ./webroot
```
erstellt und `docker bulid .` ausgeführt. 

### Was ist passiert? What happened?
```
code 255
npm ERR! path /var/www/html/webroot
npm ERR! command failed
npm ERR! command sh -c bash ../bin/cake npm_post_install
```

ich denke cake findet `npm_post_install`nicht. Ich habe es auch nirgendwo gefunden

### Was sollte passieren? What you expected to happen?
Ich glaube da fehlt eine konfiguration für cake. Kann das sein? Vielen Dank und Grüße

**Comment by mrothauer** [comment]
Hallo @sebarnd,

diese Datei sollte mit `bin/cake npm_post_install` ausgeführt werden.
https://github.com/foodcoopshop/foodcoopshop/blob/main/src/Shell/NpmPostInstallShell.php

Ich denke, es liegt am Dockerfile, damit kenn ich mich aber leider zu wenig aus um dir helfen zu können.

Vielleicht hilft dir das hier (Section "Install vendors")
https://github.com/foodcoopshop/foodcoopshop/runs/5604848440?check_suite_focus=true

Lg,
Mario

**Comment by sebarnd** [comment]
Hallo @mrothauer,

danke für die schnellen Tipps. Ich habe das Problem nun weiter eingrenzen können: `npm_post_install` braucht eine fertig konfigurierte Datenbank weil in `bootstrap.php` zeile 224ff

```php
FactoryLocator::get('Table')->get('Configurations')->loadConfigurations();
if (in_array(Configure::read('appDb.FCS_DEFAULT_LOCALE'), Configure::read('app.implementedLocales'))) {
    ini_set('intl.default_locale', Configure::read('appDb.FCS_DEFAULT_LOCALE'));
    locale_set_default(Configure::read('appDb.FCS_DEFAULT_LOCALE'));
    I18n::setLocale(Configure::read('appDb.FCS_DEFAULT_LOCALE'));
    Configure::load('Locale' . DS . Configure::read('appDb.FCS_DEFAULT_LOCALE') . DS . 'date', 'default');
    setlocale(LC_CTYPE, Configure::read('appDb.FCS_DEFAULT_LOCALE').'.UTF-8');
    setlocale(LC_COLLATE, Configure::read('appDb.FCS_DEFAULT_LOCALE').'.UTF-8');
}
```
auf die Datenbank zugegriffen wird. Für sowas wie den Docker Container wäre es sehr hübsch wenn das nicht nötig wäre. Wäre es möglich, diesen Datenbankzugriff wo anders hin zu verschieben?

**Comment by mrothauer** [comment]
Hallo @sebarnd,
kann ich noch helfen? Sonst würde ich das Issue in ein paar Tagen schließen.

**Comment by sebarnd** [comment]
Hey @mrothauer,

ich habe das vorerst mit einem `try... catch` um die entsprechenden Zeilen "gelöst" finde ich aber nicht schön. Eine andere Idee war wenn die Commandline genutzt wird auf die Lokalisierungen zu verzichten oder hat das dann andere Nachteile?

**Comment by mrothauer** [comment]
Hallo @sebarnd ,

das Skript `npm_post_install` benötigt keine Übersetzungen, alle anderen im Ornder `src/Shell` aber schon. 

> Vielleicht kannst du ein wenig experimentieren und die besagte Codesequenz für einen Request von npm_post_install ausklammern - und schauen ob dann alles läuft, oder obs woanders auch zu Problemen kommt?
