### ISSUE TITLE
Blog-Artikel an Mitglieder versenden

### ISSUE THREAD

**Issue by gueterwege** [foodcoopshop/foodcoopshop#85]
Hallo, 
wir kommunizieren bei unserer Foodcoop über einen Mail Verteiler und über die Blog Einträge vom Foodcoopshop. Dieses zweigleisige System ist oftmals mühsam oder führt zu Missverständnissen. 
Außerdem ist es kompliziert den Abholdienst vor Ort zu erreichen. zB für Hersteller, die spontan Lieferschwierigkeiten haben, oder für Mitglieder die ihre Produkte nicht abholen können. 
Ein Kommunikationstool auf der Homepage wünschen wir uns daher. 
was soll es können:
- blog Einträge an Mitglieder versenden
- "Chat" Seite für Mitglieder, dann wäre zum Beispiel Abholdienst vor Ort erreichbar.

**Comment by gueterwege** [comment]
bei einer andere Bestellungen hatten wir ein Kommentar Feld bei den ausgedruckten Bestellungen. Das wurde genutzt um dem Abholdienst etwas mitzuteilen (zb: ich kann meine Produkte nicht abholen). War sehr hilfreich. Vielleicht auch bei foodcoopshop möglich

**Comment by mrothauer** [comment]
* blog-artikel automatisch an alle mitglieder (und mit hakerl auch noch optional an aller hersteller) zu versenden find ich eine sehr gute idee
* chat-seite für abholdienst: ist vielleicht einfacher mit dem kommentarfeld beim bestellen lösbar. dieses müsste dann auch noch im nachhinein abänderbar sein, weil vielleicht weiß ich ja beim bestellen noch nicht, dass ich die sachen nicht abholen kann. der kommentar sollte dann bei der bestell-übersicht (admin-bereich: bestellungen) einsehbar sein.

**Comment by mrothauer** [comment]
Das Kommentar-Feld für Info an Abholdienst hat ein eigenes Issue: #95

**Comment by mrothauer** [comment]
@wintersim 

* in plugins/Admin/src/Controller/BlogPostsController.php eine neue Methode "sendBlogPost" anlegen (Parameter $blogPostId und $sendToManufacturer=false)

Diese Methode macht dann:
* E-Mail-Adressen aller aktiven Mitglieder holen
* Erstellen einer neuen Email-Instanz (z.B. hier: https://github.com/foodcoopshop/foodcoopshop/blob/a1c5c54694a133a7f0e8281718a8b4136b9a75ae/src/Controller/CartsController.php#L171)
* setTo: FCS_APP_EMAIL
* setBcc / addBcc: alle Mitglieder-E-Mail-Adressen
* $email->send()

Dann brauchst du eine neue E-Mail-View unter plugins/Admin/src/Template/Email/html
* name: send_blog_post.ctp
* beispiel: plugins/Admin/src/Template/Email/html/order_detail_price_changed.ctp
* element greeting macht keinen sinn, da wir nicht einzelne emails verschicken sondern eine (mit ensprechend vielen bccs)
* das beinhaltende html muss immer als table aufgebaut sein, damits richtig dargestellt wird

Unit Test
fürs erste einfach in diesen Test mit reingeben:
* tests\TestCase\src\Controller\BlogPostsControllerTest.php
* neue methode: testSendBlogPost
* url aufrufen $this->browser->get('/admin/blog-posts/sendBlogPost/xxx/1;
* emails überprüfen wie zb. hier: https://github.com/foodcoopshop/foodcoopshop/blob/a1c5c54694a133a7f0e8281718a8b4136b9a75ae/tests/TestCase/src/Controller/CartsControllerTest.php#L273
* die emails werden in der test-datenbank in der tabelle email_logs gespeichert, so kann man überprüfen, ob die emails "verschickt" wurden

gutes gelingen!
