### ISSUE TITLE
DB Migration auf 3.5 schlägt fehl

### ISSUE THREAD

**Issue by Podden** [foodcoopshop/foodcoopshop#903]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug

* FoodCoopShop Version: 3.4.2 / 3.5
* Browser und Betriebssystem / Browser and Operating System: FIREFOX 106 / Windows 10
* Platform and Target: nginx, mysql, plesk, Hoster: wint.global

### Was hast du gemacht? What you did?
Ich wollte die migration auf 3.5 durchführen. Hauptverzeichnis in _old umbekannt, neues Archiv entpackt, Config rüberkopiert und credentials.php angepasst.
Danach hab ich mich per Putty auf meinen Server eingeloggt und `bin/cake migrations migrate && bin/cake migrations migrate -p Queue`.

### Was ist passiert? What happened?
Eine PDOException beim migrate Befehl. Die Webseite funktioniert soweit zwar, aber im Adminbereich können die Reiter "Einstellungen" und "Bestellungen" nicht mehr aufgerufen werden.

Console Log:
```
bash-4.4$ php-8.1 bin/cake.php migrations migrate && php-8.1 bin/cake.php migrations migrate -p Queue
using migration paths
 - /***********.de/foodcoopshop/config/Migrations
using seed paths
using environment default
using adapter mysql
using database *************_db
ordering by creation time

 == 20220321103059 PrefixForInvoices: migrating
PDOException: SQLSTATE[HY000]: General error: 1273 Unknown collation: 'utf8mb4_0900_ai_ci' in /***********.de/foodcoopshop/vendor/robmorgan/phinx/src                                                                                                                                                     /Phinx/Db/Adapter/PdoAdapter.php:193
Stack trace:
#0 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(193): PDO->exec()
#1 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(156): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(156): Phinx\Db\Adapter\AdapterWrapper->execute()
#3 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(198): Phinx\Db\Adapter\AdapterWrapper->execute()
#4 /***********.de/foodcoopshop/config/Migrations/20220321103059_PrefixForInvoices.php(24): Phinx\Migration\AbstractMigration->execute()
#5 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): PrefixForInvoices->change()
#6 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(385): Phinx\Migration\Manager\Environment->executeMigration()
#7 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#8 /***********.de/foodcoopshop/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#9 /***********.de/foodcoopshop/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(37): Phinx\Console\Command\Migrate->execute()
#10 /***********.de/foodcoopshop/vendor/cakephp/migrations/src/Command/Phinx/Migrate.php(85): Migrations\Command\Phinx\Migrate->parentExecute()
#11 /***********.de/foodcoopshop/vendor/symfony/console/Command/Command.php(308): Migrations\Command\Phinx\Migrate->execute()
#12 /***********.de/foodcoopshop/vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Command\Command->run()
#13 /***********.de/foodcoopshop/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#14 /***********.de/foodcoopshop/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#15 /***********.de/foodcoopshop/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(126): Symfony\Component\Console\Application->run()
#16 /***********.de/foodcoopshop/vendor/cakephp/cakephp/src/Console/BaseCommand.php(189): Migrations\Command\MigrationsCommand->execute()
#17 /***********.de/foodcoopshop/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(198): Cake\Console\BaseCommand->run()
#18 /***********.de/foodcoopshop/vendor/cakephp/cakephp/src/Console/CommandRunner.php(334): Migrations\Command\MigrationsCommand->run()
#19 /***********.de/foodcoopshop/vendor/cakephp/cakephp/src/Console/CommandRunner.php(172): Cake\Console\CommandRunner->runCommand()
#20 /***********.de/foodcoopshop/bin/cake.php(12): Cake\Console\CommandRunner->run()
#21 {main}
```

### Was sollte passieren? What you expected to happen?
Keine Exception und eine ordentliche Database migration. Volle Funktion der Webseite

**Comment by mrothauer** [comment]
Hallo,
hilft dir das?
https://tecadmin.net/resolved-unknown-collation-utf8mb4_0900_ai_ci/
Welche mysql-version verwendest du?

**Comment by Podden** [comment]
Auch gerade gefunden. Der Reimport schlägt leider auch fehl mit "Unknow collation utf8mb4_0900_ai_ci". Aber ich habs gerade auch andersrum versucht und deine "20220321103059_PrefixForInvoices.php" auf "utf8mb4_general_ci" gestellt. Jetzt läufts durch, allerdings quittiert die Page nun komplett den Dienst. Ich muss mir das morgen nochmal genauer anschauen.

```
bash-4.4$ php-8.1 bin/cake.php migrations migrate && php-8.1 bin/cake.php migrations migrate -p Queue
using migration paths
 - /********.de/foodcoopshop/config/Migrations
using seed paths
using environment default
using adapter mysql
using database **********_db
ordering by creation time

 == 20220321103059 PrefixForInvoices: migrating
 == 20220321103059 PrefixForInvoices: migrated 0.0101s

 == 20220323075926 TaxBasedOnNetInvoiceSum: migrating
 == 20220323075926 TaxBasedOnNetInvoiceSum: migrated 0.0036s

 == 20220407093247 AddIsCompanyFieldForCustomer: migrating
 == 20220407093247 AddIsCompanyFieldForCustomer: migrated 0.0243s

 == 20220412131842 Newsletter: migrating
 == 20220412131842 Newsletter: migrated 0.0083s

 == 20220525092822 BiggerQueuedJobDataField: migrating
 == 20220525092822 BiggerQueuedJobDataField: migrated 0.0221s

 == 20220620091755 RemoveTimebasedCurrencyModule: migrating
 == 20220620091755 RemoveTimebasedCurrencyModule: migrated 0.0436s

 == 20220717194215 UserFeedback: migrating
 == 20220717194215 UserFeedback: migrated 0.0057s

All Done. Took 0.1309s

Dumps the current schema of the database to be used while baking a diff

using migration paths
 - /******.de/foodcoopshop/config/Migrations
using seed paths
Writing dump file `/*******.de/foodcoopshop/config/Migrations/schema-dump-default.lock`...
Dump file `/*******.de/foodcoopshop/config/Migrations/schema-dump-default.lock` was successfully written
using migration paths
 - /*******.de/foodcoopshop/vendor/dereuromark/cakephp-queue/config/Migrations
using seed paths
using environment default
using adapter mysql
using database ************_db
ordering by creation time

All Done. Took 0.0064s

Dumps the current schema of the database to be used while baking a diff

using migration paths
 - /*******.de/foodcoopshop/vendor/dereuromark/cakephp-queue/config/Migrations
using seed paths
Writing dump file `/*******.de/foodcoopshop/vendor/dereuromark/cakephp-queue/config/Migrations/schema-dump-default.lock`...
Dump file `/*******.de/foodcoopshop/vendor/dereuromark/cakephp-queue/config/Migrations/schema-dump-default.lock` was successfully written
```

**Comment by Podden** [comment]
Okay, my bad. Restarted the process again with a more wakeup head and everything went fine :). Don't know what happened though.

**Comment by Podden** [comment]
I was too hasty. A user told me that she could not get a password reset Mail. Digging into it I found out that no Emails are going out.
I've adjusted the credentials.php according to the migration guide:
[errorandconfig.zip](https://github.com/foodcoopshop/foodcoopshop/files/10003604/errorandconfig.zip)

I found no "Mail Sending failed" error on the server or in the logs. I did not touch the credentials after 3.5 upgrade but after getting the error, I've also tested a config with TLS on Port 465 with no luck. E Mails from this Address are send normally via Thunderbird SMTP, so no issues there.

Also debugging that, I've noticed that our instance of foodcoopshop only works with `'debug' => true,` after updating to 3.5. Setting this to false results in two errors:
<details>
<summary>error.log</summary>
2022-11-14 14:32:31 error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Customers.timebased_currency_enabled' in 'field list' in [...]/foodcoopshop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:39
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Database/Connection.php:359
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Database/Connection.php:362
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Database/Query.php:254
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Query.php:1148
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:288
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/ORM/Query.php:1096
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:495
- [...]/foodcoopshop/src/Controller/AppController.php:99
- [...]/foodcoopshop/src/Controller/AppController.php:111
- [...]/foodcoopshop/src/Controller/FrontendController.php:114
- [...]/foodcoopshop/src/Controller/PagesController.php:32
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Event/EventManager.php:309
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Event/EventManager.php:286
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php:92
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Controller/Controller.php:644
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:129
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Controller/ControllerFactory.php:114
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/BaseApplication.php:320
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php:77
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:186
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:68
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- [...]/foodcoopshop/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php:57
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php:131
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php:73
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php:58
- [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Server.php:90
- [...]/foodcoopshop/webroot/index.php:40

Request URL: /
Referer URL: https://**********/neues-passwort-anfordern
Client IP: 24.134.41.45
2022-11-14 14:32:31 warning: Undefined variable $isMobile
Request URL: /
Referer URL: https://shop.koope.de/neues-passwort-anfordern
Client IP: 24.134.41.45
Trace:
include [...]/foodcoopshop/templates/layout/error.php, line 40
Cake\View\View::_evaluate() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1220
Cake\View\View::_render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1177
Cake\View\View::renderLayout() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 860
Cake\View\View::render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 819
Cake\Controller\Controller::render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Controller/Controller.php, line 773
Cake\Error\Renderer\WebExceptionRenderer::_outputMessage() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Renderer/WebExceptionRenderer.php, line 413
Cake\Error\Renderer\WebExceptionRenderer::render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Renderer/WebExceptionRenderer.php, line 284
Cake\Error\Middleware\ErrorHandlerMiddleware::handleException() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php, line 162
Cake\Error\Middleware\ErrorHandlerMiddleware::process() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php, line 135
Cake\Http\Runner::handle() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php, line 73
Cake\Http\Runner::run() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php, line 58
Cake\Http\Server::run() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Server.php, line 90
[main] [...]/foodcoopshop/webroot/index.php, line 40

2022-11-14 14:32:31 warning: Undefined variable $isMobile
Request URL: /
Referer URL: https://**********.de/neues-passwort-anfordern
Client IP: 24.134.41.45
Trace:
include [...]/foodcoopshop/templates/element/customThemeStyleSheet.php, line 127
Cake\View\View::_evaluate() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1220
Cake\View\View::_render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1177
Cake\View\View::_renderElement() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1712
Cake\View\View::element() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 699
include [...]/foodcoopshop/templates/layout/error.php, line 44
Cake\View\View::_evaluate() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1220
Cake\View\View::_render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 1177
Cake\View\View::renderLayout() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 860
Cake\View\View::render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/View/View.php, line 819
Cake\Controller\Controller::render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Controller/Controller.php, line 773
Cake\Error\Renderer\WebExceptionRenderer::_outputMessage() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Renderer/WebExceptionRenderer.php, line 413
Cake\Error\Renderer\WebExceptionRenderer::render() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Renderer/WebExceptionRenderer.php, line 284
Cake\Error\Middleware\ErrorHandlerMiddleware::handleException() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php, line 162
Cake\Error\Middleware\ErrorHandlerMiddleware::process() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php, line 135
Cake\Http\Runner::handle() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php, line 73
Cake\Http\Runner::run() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Runner.php, line 58
Cake\Http\Server::run() [...]/foodcoopshop/vendor/cakephp/cakephp/src/Http/Server.php, line 90
[main] [...]/foodcoopshop/webroot/index.php, line 40


</details>

Again, going back to debug mode, everything works fine. I don't know if this is related, should I open another ticket?

**Comment by mrothauer** [comment]
`debug => true` should be turned off
did you download from foodcoopshop.com/download or clone from github?
if you cloned from github, the vendors need to be installed and assets need to be compressed manually
did you follow https://foodcoopshop.github.io/en/cronjobs.html and set up the queue? in 3.5 all emails are sent via queue.

if you checked everything and it still does not work, please post an error log with the email error log (can eventuelly be found in table `queued_jobs`, fieldname `failure_message`.

**Comment by Podden** [comment]
okay, after setting up the new queue cronjob everything works as expected. Now waiting for all the testmails waiting in the queue to finish :D. Thanks for the help

**Comment by mrothauer** [comment]
Gern geschehen.
If something is missing in https://foodcoopshop.github.io/en/migration-guide.html please update via github pull request.
Thank you,
Mario

**Comment by ocapito** [comment]
> Welche mysql-version verwendest du?

Bei uns ist der gleiche Fehler aufgetreten. Haben es nach den obigen Hinweisen gelöst.

Unsere Datenbank läuft unter 10.5.15-MariaDB-0+deb11u1
