### ISSUE TITLE
Probleme nach Servermigration (apache -> nginx): Warenkorb aktualisiert sich nicht und Produktpreise können nicht mehr eingegeben werden

### ISSUE THREAD

**Issue by alexanderharm** [foodcoopshop/foodcoopshop#925]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.5.0
* Browser und Betriebssystem / Browser and Operating System: Firefox ESR 102.6.0/Brave 1.47.171, macOS
* Platform and Target: Docker linuxserver.io/nginx (nginx, php-fpm 8.1)

### Was hast du gemacht? What you did?
Migriert von Apache Hoster zu Docker nginx

### Was ist passiert? What happened?
Seit Migration lassen sich Produktpreise nicht mehr eingeben (falsches Inputformat) und der Warenkorb aktualisiert sich nicht richtig.

![Screenshot 2023-01-22 at 11 01 30](https://user-images.githubusercontent.com/16108584/213915915-b762f452-f6d7-46d9-939a-92803051a4da.jpg)
![Screenshot 2023-01-22 at 11 01 49](https://user-images.githubusercontent.com/16108584/213915931-fef437e7-8132-4361-a7e4-b5a92cd0a433.jpg)
![Screenshot 2023-01-22 at 11 33 45](https://user-images.githubusercontent.com/16108584/213915942-a1c0b980-cd86-4abb-91d7-d0317b60d471.jpg)

### Was sollte passieren? What you expected to happen?
Warenkorb und Produktpreise funktionieren weiterhin.

**Comment by alexanderharm** [comment]
Das hat wahrscheinlich irgendetwas mit Umleitungen zu tun, weil ich nun auch bei jedem Speichern auf der Startseite lande... nginx-Konfig entsprechend Wiki/CakePHP Kochbuch.

**Comment by mrothauer** [comment]
und beim ändern des preises muss statt 8.00 8,00 eingegeben werden

**Comment by alexanderharm** [comment]
Mit den Preisen habe ich alle Variationen ausprobiert aber wie gesagt, ich glaube, dass der Fehler woanders liegt:

- Jedes Speichern bringt einen zurück zur Startseite (interessanterweise ist die Antwort auf ein POST immer ein Link auf http://startseite, ohne https)
- Denke, dass dadurch auch etwas im Warenkorb durcheinanderkommt, weil man einmal Reload machen muss und dann geht es erst. Im PDF per Mail stimmt aber alles, d. h. am Format ist alles OK. In der DB passt auch alles.
- Die Logs sind leer. Weder nginx, php noch fcs haben etwas zu meckern seltsamerweise, auch die Browserkonsole beanstandet nichts.
- Ich habe auch noch einmal ein rsync --dry-run gemacht, um zu sehen, ob bei der Migration etwas verloren ging aber da gibt es auch nichts.

Ich versuche einmal die Dev-Umgebung und melde mich dann noch einmal. Vielen Dank für deinen Input.

**Comment by alexanderharm** [comment]
So sieht das aus:

```
Request URL: https://fcs.example.com/admin/configurations/edit/559
Request Method: POST
Status Code: 302 
Remote Address: 194.59.204.206:443
Referrer Policy: strict-origin-when-cross-origin
cache-control: no-store, no-cache, must-revalidate
content-type: text/html; charset=UTF-8
date: Sun, 22 Jan 2023 19:48:45 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
location: http://fcs.example.com/
pragma: no-cache
server: nginx
:authority: fcs.example.com
:method: POST
:path: /admin/configurations/edit/559
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.8
cache-control: max-age=0
content-length: 144
content-type: application/x-www-form-urlencoded
cookie: PHPSESSID=oeloid7jlk2jqg11a49ur65bbo
origin: https://fcs.example.com
referer: https://fcs.example.com/admin/configurations/edit/559
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
sec-gpc: 1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
```

```
_method: 
PUT
referer: 
/
Configurations[value]: 
_Token[fields]: 
491cb48d678cfa60826950a305c8b9c4297c0448%3Areferer
_Token[unlocked]: 
```

Passt da irgendetwas nicht?

**Comment by alexanderharm** [comment]
Habe jetzt folgendes gemacht:

- Dev-Image gebaut und mir von dort die nginx-Konfig gezogen
- Neue Datenbank angelegt
- Noch einmal das Release geladen

Gleicher Fehler.

Dev-Image gestartet und dann meine Datenbank und Konfigs importiert: funktioniert.

Ich begebe mich noch etwas auf Fehlersuche.

**Comment by mrothauer** [comment]
Guten Morgen,
sehr schön, freut mich, wenn's jetzt funktioniert.
Wenn du noch was Hilfreiches findest bitte Issue ergänzen oder PR erstellen.
Cool wär auch, wenn du deine Docker Production-Settings teilen könntest, ich hoste meine Kunden noch nicht mit Docker würde aber auch gerne mal umstellen.
Danke,
Mario

**Comment by alexanderharm** [comment]
Mache ich. Irgendeine Präferenz bzgl. Images?

**Comment by mrothauer** [comment]
Cool, danke! Am besten best practices folgen (nur offizielle Images verwenden, feste Versionsnummern und kein :latest). Aber vermutlich kennst du dich da besser aus als ich. https-Zertifikate vermutlich über traefik? Funktionieren soll es :-)

Es gibt schon dieses (unmaintained) Repo hier:
https://github.com/foodcoopshop/foodcoopshop-docker

Wenn du möchtest, geb ich dir die Rechte für das Repo.

**Comment by alexanderharm** [comment]
Ich kann es einmal versuchen, komme aber frühestens kommende Woche dazu.

**Comment by mrothauer** [comment]
Ja wann immer es dir reinpasst. Vielleicht forkst du das Repo erst mal und dann schauen wir.
Gutes Gelingen und vielen Dank!
