### ISSUE TITLE
Frage: Liefergewicht bei Preis nach Gewicht ändern für alte Bestellungen

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#927]
Hallo.

Wir haben das Problem, dass wir lauter alte abgeschlossene Bestellung bei uns im Shop haben, bei denen vergessen wurde ein Gewicht beim Abschluss einzugeben und diese nun ein Gewicht von 0 aufweisen.
Früher war es mal möglich abgeschlossene Bestellungen nochmal zu öffnen um Anpassungen vorzunehmen.
Gibt es noch eine Möglichkeit dies in der Version 3.2 durchzuführen?
Oder gibt es eine andere Möglichkeit dort ein Gewicht zu hinterlegen?

Grüße.

* FoodCoopShop Version: 3.2

**Comment by mrothauer** [comment]
Hallo,
nein, das ist nicht vorgesehen. In früheren Versionen war das nicht sauber. Der Grund für die Änderung (und die ist schon lange her) war folgender: Sobald die Bestellung abgerechnet ist wird das Geld normalerweise rasch an den Hersteller überwiesen. Wenn man dann im Nachhinein das Gewicht ändert (oder zb. storniert), stimmt es nicht mehr überein.
Man müsste solche Fehler in der kommenden Periode ausbuchen, dann stimmt es wieder und es ist nachvollziehbar.
Schöne Grüße,
Mario

**Comment by Confuset** [comment]
Das habe ich fast vermutet.
In der der Datenbank rumfuddeln möchte ich auch nicht wirklich, wer weiß was dann hinten herunterfällt..

Also beste Option ist dann wohl alle raussuchen, die das gemacht haben und dann nachbuchen.
Danke Dir :-)
