### ISSUE TITLE
Plugin DebugKit fehlt im Installationspackage 

### ISSUE THREAD

**Issue by reicharm** [foodcoopshop/foodcoopshop#931]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.5.0
* Browser und Betriebssystem / Browser and Operating System:
* Platform and Target:

### Was hast du gemacht? What you did?
Ich habe das aktuelle Installationspackage für die Version 3.5.0 von der Webseite heruntergeladen und auf einem frischen Testserver installiert. Dann hab ich (nach Setup von DB usw) 'debug' => true gesetzt.

### Was ist passiert? What happened?
Jeder Seitenaufruf produziert den Fehler "Missing Plugin"

### Was sollte passieren? What you expected to happen?
Foodcoopshop sollte im Debug-Modus starten

Ist jetzt nicht tragisch und lässt sich natürlich auch beheben, schöner wäre aber natürlich ein funktionsfähiges Installationspackage.

**Comment by reicharm** [comment]
![Screenshot 2023-02-03 204553](https://user-images.githubusercontent.com/7581111/216694272-3a321245-905d-426b-83bf-f4b8411e9da4.png)

**Comment by mrothauer** [comment]
https://book.cakephp.org/debugkit/4/en/index.html
Ist nur für lokale Entwicklungssysteme gedacht, darum ist es nicht mit dabei.
Mir reichen zum Debuggen meistens die logs (zu finden unter /logs)
Lg,
Mario

**Comment by reicharm** [comment]
Ja, verstehe ich wie gesagt. Aber in der Doku verweist du drauf, dass man den Debug-Modus einschalten kann/soll um css/js-Anpassungen zu testen - nur geht das halt nicht ... Vielleicht kann man ja es einfach irgendwo vermerken, dass das bei der Downloadversion nicht dabei ist, die habe ich in dem Fall ja extra genommen, weil ich nichts mit Composer nachinstallieren wollte (weil das auf meinem Testserver nicht geht).

**Comment by mrothauer** [comment]
Ok ich verstehe. Hast du Shell-Zugriff? Denn du müsstest dann ja auch mit `bin/cake asset_compress build` deine css/js-Änderungen packen.
Falls du keine Shell- Zugriff hast, könntest du lokal ganz schnell eine Docker Dev Environment aufsetzten, alles auf deinem Rechner erledigen und dann nur den Inhalt des Ordners webroot/cache hochladen.

**Comment by reicharm** [comment]
Ja, hab Shell-Zugriff, nur Composer geht nicht vom Provider aus. Ist auch kein Problem für mich konkret - ich hab mir DebugKit eh nachinstalliert und packe dann wenn notwendig die Assets neu. Ich wollte es nur generell festhalten, falls das mal für wen anderen ein Problem ist oder zu Verwirrung führt.
Gerade wenn man den FoodCoopShop nur mal ausprobieren will, ist das ja eine interessante Option das Downloadpaket zu verwenden und wenn (so wars zumindest bei mir beim ersten Mal auch) dann nicht alles auf Anhieb funktioniert, liegt das Umschalten auf "Debug-Modus" ja irgendwie nahe.

Leider hat das Docker Dev-Environment auch nicht auf Anhieb bei mir funktioniert, aber das liegt vmtl an den spezifischen (Security-)Settings bei mir am Rechner.

**Comment by mrothauer** [comment]
> Ja, hab Shell-Zugriff, nur Composer geht nicht vom Provider aus. Ist auch kein Problem für mich konkret - ich hab mir DebugKit eh nachinstalliert und packe dann wenn notwendig die Assets neu. Ich wollte es nur generell festhalten, falls das mal für wen anderen ein Problem ist oder zu Verwirrung führt.

Wie hat du denn DebugKit nachinstalliert, wenn composer nicht geht? Würde mich interessieren.

> Gerade wenn man den FoodCoopShop nur mal ausprobieren will, ist das ja eine interessante Option das Downloadpaket zu verwenden und wenn (so wars zumindest bei mir beim ersten Mal auch) dann nicht alles auf Anhieb funktioniert, liegt das Umschalten auf "Debug-Modus" ja irgendwie nahe.

Ok, das verstehe ich. Aber ich will trotzdem nur ungern ein Package, das eigentlich nur für lokale Entwicklungsumgebungen gedacht ist, mit in das Downloadpaket geben. Ich werde nächste Woche die Doku dazu ergänzen. Oder könntest du das evtl. erledigen?

> Leider hat das Docker Dev-Environment auch nicht auf Anhieb bei mir funktioniert, aber das liegt vmtl an den spezifischen (Security-)Settings bei mir am Rechner.

Falls du noch draufkommen solltest, worans lag: Entweder Docker-Dev-Environment-Doku direkt ergänzen oder mit Bescheid geben, dann nehm ich das mit auf. Danke!

**Comment by reicharm** [comment]
Es genügt, wenn man das Github Package von DebugKit in den Ordner "plugins/DebugKit" kopiert.

Docker-Dev schau ich mir sicher noch mal an, ich melde mich, wenn ich weiß woran es liegt.

Ich schließe das Ticket jetzt damit - danke fürs Zeit nehmen und drüber diskutieren!

**Comment by mrothauer** [comment]
> Es genügt, wenn man das Github Package von DebugKit in den Ordner "plugins/DebugKit" kopiert.

Ah genau, so gehts auch!

> Ich schließe das Ticket jetzt damit - danke fürs Zeit nehmen und drüber diskutieren!

Danke auch fürs Bescheid sagen - ist ja wirklich verwirrend. Ich hab die Doku überarbeitet:
https://foodcoopshop.github.io/en/installation-guide.html#customizing-css
