### ISSUE TITLE
The "short" cache configuration does not exist.

### ISSUE THREAD

**Issue by Confuset** [foodcoopshop/foodcoopshop#935]
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [x] Bug
* [ ] Verbesserungsvorschlag / enhancement
* [ ] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: 3.4.2
* Platform and Target: nginx, MariaDB

### Was hast du gemacht? What you did?
Ich habe eine Migration von 3.3.2 auf 3.4.2 gemacht.
Dabei soll jetzt der Cache konfiguriert werden.
In der Migrationsanleitung ist folgendes:
```
'Cache' => [
  'default' => [
      'prefix' => 'example_com_',
  ],
  '_cake_core_' => [
      'prefix' => 'example_com_',
  ],
  '_cake_model_' => [
      'prefix' => 'example_com_',
  ],
],
```
In der custom_config.default.php findet sich dieses:
```
   'Cache' => [
        'default' => [
            'prefix' => 'example_com_',
        ],
        'short' => [
            'prefix' => 'example_com_',
        ],
        '_cake_core_' => [
            'prefix' => 'example_com_',
        ],
        '_cake_model_' => [
            'prefix' => 'example_com_',
        ],
    ],
```
Hierbei die Konfiguration von `short` beachten.
Ich habe mich beim Update an der custom_config.default.php orientiert. Dies führt aber zu diversen Fehlern auf der Website, diese finden sich auch im error.log.
```
2023-02-19 13:41:56 error: [Cake\Cache\InvalidArgumentException] The "short" cache configuration does not exist. in /srv/http/vendor/cakephp/cakephp/src/Cache/Cache.php on line 148
Stack Trace:...
```
Wenn ich allerdings die Konfiguration `short` entferne scheint alles zu gehen. Ich vermute also, dass die custom_config.default.php nicht ganz passt.

**Comment by mrothauer** [comment]
die short-config kam erst in 3.5.0 dazu, sie ist auch in der custom_config.default.php von 3.4.2 nicht mit drinnen:
https://github.com/foodcoopshop/foodcoopshop/blob/v3.4.2/config/custom_config.default.php

https://github.com/foodcoopshop/foodcoopshop/commit/1a5a6e0db0d7a45bc4e3e4683f89ae127cf54249
du kannst sie also weglassen.

lg,
mario
