### ISSUE TITLE
Falsche Preise in der Sofort-Bestellung!

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#937]
In der Sofort-Bestellung werden falsche Preise angezeigt! Die betroffenen Produkte werden auch so in den Warenkorb gelegt und abgerechnet!
Bsp lt. Screenshots in Whatsapp

**Comment by mrothauer** [comment]
"Nur" ein Anzeige (Caching) -Problem - Bestellung und Abrechnung ist korrekt. ich schaus mir an.

**Comment by mrothauer** [comment]
Bei der Anzeige der Preise in der Sofort-Bestellung wurde immer der Preis angezeigt, mit dem der Cache generiert wurde. Dann wurde nicht mehr unterschieden. Also ab und zu Einkaufspreis bei Verkaufspreis-Usern und umgekehrt.
