### ISSUE TITLE
Barcodesuche liefert Produkt ohne EAN13Barcode

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#938]
Voraussetzung:
2 Produkte im System:
1x Apfel-Holunder-Essig OHNE EAN13Barcode
1x Birnensaft mit Variante 1L Flasche mit EAN13Barcode "9311111111120"

UseCase:
Scannen des Barcodes 9311111111120 im Suchfeld

Ergebnis:
NOK: es werden beide oben genannten Produkte gefunden und angzeigt
SOLL: es sollte nur Birnensaft 1L gefunden und angzeigt werden

Video vom Usecase bei Bedarf vorhanden, kann ich dir gerne schicken.

**Comment by mrothauer** [comment]
Ja bitte Video, danke!

**Comment by mrothauer** [comment]
In dem konkreten Fall sind die ersten 4 Zeichen vom SHA1-Hash der beiden Produkte gleich. Das kommt extrem selten vor. Ich kann die Anzahl der Zeichen nicht erhöhen, sonst müsste man alle generierten Produktkarten neu ausdrucken. Der Vergleich wird jetzt nur durchgeführt, wenn das $keyword 8 Zeichen (=selbstgenerierter Barcode) hat. Das sollte reichen, sodass alles korrekt funktioniert.

**Comment by mrothauer** [comment]
https://github.com/foodcoopshop/foodcoopshop/commit/3575b8f050870735c15dda6e5d3491eb9830d9a1
