### ISSUE TITLE
Bei Produkt mit Varianten wird bei Barcodesuche im SB -Modus nur die erste Variante direkt in den Warenkorb gelegt

### ISSUE THREAD

**Issue by pabneukistl** [foodcoopshop/foodcoopshop#939]
Voraussetzung:
Produkt A mit 2 Varianten, beide Varianten enthalten einen eignenen EAN13Barcode (Achtung Reihenfolge der Varianten wichtig!):
Variante 100ml (Standardvariante)
Variante 500ml

UseCase:
SB-Modus
Scannen Barcode Variante 100ml
-> OK: die Variante 100ml wird gefunden und automatisch in den Warenkorb gelegt
Scannen Barcode Variante 500ml
-> NOK: das Produkt wird gefunden und angezeigt, die gescannte Variante wird jedoch NICHT automatisch in den Warenkorb gelegt (es wird auch nicht die gescannte Variante ausgewählt, es ist die Standardvariante ausgewählt. Auch Tausch der Standardvariante ändert nichts am Verhalten, dass die Variante nicht automatisch in den Warenkorb gelegt wird. Die automatische Warenkorbübernahme funktioniert immer nur mit der ersten Variante des Produktes)
SOLL: die gescannte Variante 500ml sollte automatisch in den Warenkorb gelegt werden

**Comment by mrothauer** [comment]
Kannst du mir hier bitte auch ein Video machen oder ein konkretes Beispiel geben? Danke.

**Comment by mrothauer** [comment]
ist auch gefixt - war schlampig programmiert. wenn ich den erwische :-)
