### ISSUE TITLE
Photos.

### ISSUE THREAD

**Issue by guland2000** [foodcoopshop/foodcoopshop#942]
Didn't found.... Cam we make more then 1 photo in product preview/ description?
Das ist ein (mehrere Antworten möglich) / This is a (multiple allowed)

* [ ] Bug
* [x] Verbesserungsvorschlag / enhancement
* [x] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: GENAUE VERSIONSNUMMER / EXACT RELEASE VERSION.
* Browser und Betriebssystem / Browser and Operating System: EG FIREFOX 64 / Windows 10
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### Was hast du gemacht? What you did?
EXPLAIN WHAT YOU DID.

### Was ist passiert? What happened?
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

### Was sollte passieren? What you expected to happen?
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

Bevor du das Issue erstellst, überprüfe bitte, ob es bereits ein ähnliches gibt.
Before you open an issue, please check if a similar issue already exists or has been closed before.

Du kannst dem Projekt zu mehr Sichtbarkeit verhelfen, in dem du ihm einen Stern ⭐ gibst. Danke!
You can help making this open source project more visible on GitHub by starring ⭐ it. Thank you!

**Comment by mrothauer** [comment]
Hi

you can only add one product image as "main" product image, but you can include more images into the description field using the button in the editor.

![image](https://user-images.githubusercontent.com/527787/223765012-d455af92-2717-43a2-8f30-2bf8c6eb5598.png)
