### ISSUE TITLE
Nachricht an Abholdienst - Kommentarfeld beim Bestellen

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#95]
Unterhalt der Hakerl beim Bestellen einen Link anzeigen "Nachricht an Abholdienst verfassen", bei Klick wird ein Textfeld angezeigt, in dem man eine Nachricht reinschreiben kann. Z.B. "Kann meine Sachen am Freitag nicht abholen."

Unter "Bestellungen" sieht der Abholdienst dann ein **rotes Rufzeichen** links vom Namen, wenn man mit der Maus darüber fährt, kann man den Text lesen.

Bei Bestellungen ohne vorhandenem Kommentar wird ein **ausgegrautes Rufzeichen** angezeigt, auf das man klicken kann und so im Nachhinein einen Kommentar zur Bestellung verfassen kann. Es wird dann rot, wenn ein Text vorhanden ist.

**Comment by mrothauer** [comment]
@gueterwege fyi

**Comment by mrothauer** [comment]
https://www.fairteiler-scharnstein.at/aktuelles/238-neue-kommentar-funktion-beim-bestellen

**Comment by gueterwege** [comment]
Hallo, 
genial. danke. sehr gut sichtbar. 
kommentar ist mit dem bestellvorgang verbunden. ist es auch möglich, dass jemand nach dem bestellen, zb am abholtag ein kommentar an den abholdienst schickt? zb indem man eine leere bestellung macht und diese abschickt?

**Comment by mrothauer** [comment]
hallo,
es ist so vorgesehen, dass der kommentar immer an eine bestellung gebunden ist. **ich kann aber meinen kommentar im nachhinein löschen oder hinzufügen (auf das rufzeichen im admin-bereich klicken).** aber es muss eine bestellung vorhanden sein. macht doch sinn so, oder? leere bestellungen nur wegen einem kommentar zu ermöglichen halte ich nicht für sinnvoll.

**Comment by gueterwege** [comment]
ja macht sinn, geht ja nur um die abholung. habs übersehen.

**Comment by mrothauer** [comment]
oki doki dann betrachte ich das ganze mal als fertig! danke fürs testen.

**Comment by gueterwege** [comment]
danke fürs machen;)
