### ISSUE TITLE
Fehler bei testen von Mailversand

### ISSUE THREAD

**Issue by aroscha** [foodcoopshop/foodcoopshop#961]
* [x] Bug

* FoodCoopShop Version: 3.6.0
* Browser und Betriebssystem / Browser and Operating System: Firefox 115.0.1 (64-Bit), Manjaro
* Platform and Target: Apache, mysql, Hoster: Uberspace

### Was hast du gemacht? What you did?
Konfiguration des Mailversand in `custom_config.php` und `credentials.php`
Testen der Einstellungen über https://yourdomain.tld/admin/configurations/sendTestEmail

### Was ist passiert? What happened?
Keine Mail wird versendet. Im Browser wird nach dem Aufrufen des Links zum Testen der Mail-Config folgendes angezeigt, ich weiß nicht ob das beabsichtigt ist:

`Cake\View\ViewBuilder Object ( [_templatePath:protected] => [_template:protected] => send_test_email_template [_plugin:protected] => [_theme:protected] => [_layout:protected] => default [_autoLayout:protected] => 1 [_layoutPath:protected] => [_name:protected] => [_className:protected] => Cake\View\View [_options:protected] => Array ( ) [_helpers:protected] => Array ( [0] => Html ) [_vars:protected] => Array ( ) ) 
`
### Was sollte passieren? What you expected to happen?
Es sollte eine automatische Mail versendet werden die bestätigt das das die Einstellungen zum automatischen Mailversand korrekt sind.

In den Logs tauchen keine Einträge dazu auf.
Das Problem besteht meiner Beobachtung seit Version 3.5.1. Ich habe die Konfiguration mit Mail von unterschiedlichen Hostern probiert, was leider nicht half.

Hier die Konfiguration, vielleicht verstehe ich es auch einfach nicht:

custom_config.php

```
debug' => false,
    'EmailTransport' => [
        'default' => [
            'className' => 'Smtp',
            'host' => 'mail.hoster.de',
            'port' => 465,
            'timeout' => 30,
            'username' => 'post@domain.org',
            'password' => 'password',
            'client' => true,
            'tls' => true,
        ]
    ],
    
 'Email' => [
        'default' => [
            'from' => ['post@domain.org' => 'Shop FoodCoop' ], // [email-address => name] 
        ]
    ],
```

credentials.php

```
'EmailTransport' => [
         'debug' => [
             'className' => 'Smtp',
             'host' => 'mail.hoster.de',
             'port' => 465,
             'timeout' => 30,
             'username' => 'post@domain.org',
             'password' => 'password',
             'client' => null,
             'tls' => true,
         ],
     ],
     'Email' => [
         'debug' => [
             'emailFormat' => 'html',
             'transport' => 'debug',
             'from' => ['post@domain.org' => 'Shop FoodCoop'],
             'charset' => 'utf-8',
             'headerCharset' => 'utf-8',
         ],
     ],
     ```

**Comment by mrothauer** [comment]
Hallo,
alle Mails werden über eine Queue versendet. Wird die Queue auch ausgeführt?
https://foodcoopshop.github.io/en/cronjobs.html

**Comment by aroscha** [comment]
Hallo,
ja, die Cronjobs sind konfiguriert und werden ausgeführt.
Allerdings sollte der Versand der Testmail beim Aufrufen von https://yourdomain.tld/admin/configurations/sendTestEmail doch unabhängig vom Ausführen der Cronjobs passieren? Oder verstehe ich das falsch?

**Comment by mrothauer** [comment]
Das Aufrufen von https://yourdomain.tld/admin/configurations/sendTestEmail erzeugt nur einen Eintrag in der fcs_queue_jobs Tabelle, der worker (punkt 2 in der cronjob doku) arbeitet das dann ab.

**Comment by aroscha** [comment]
Danke der Nachfrage. 
Ich habe die Datenbank von Hand migriert und es über Port 587, damit klappt es.
