### ISSUE TITLE
Sofortbestellung während Lieferpause

### ISSUE THREAD

**Issue by hasslerf** [foodcoopshop/foodcoopshop#981]
* [x] Vorschlag für neue Funktion / feature-discussion (RFC)

* FoodCoopShop Version: latest

### Was hast du gemacht? What you did?
Sofortbestellung während Lieferpause probiert. Allerdings sind alle Produkte aller Hersteller nicht auffindbar, auch die als Lagerware markierten.

### Was ist passiert? What happened?
Während einer Lieferpause kann auch ein Abholtag stattfinden. Dann möchte ich natürlich Lagerwaren sofort bestellen können.

### Was sollte passieren? What you expected to happen?
Sofortbestellungen sollen immer funktionieren. Dh, auch während einer Lieferpause möchte ich Produkte finden und für unsere Kunden bestellen können.

**Comment by mrothauer** [comment]
@hasslerf Es gibt eine Einstellung "In der Sofort-Bestellung ausschließlich Lagerprodukte anzeigen?	" Die ist bei euch auf "ja". Stell das mal auf "nein".

**Comment by mrothauer** [comment]
@hasslerf Falls das nicht die Lösung ist, schick mir bitte ein konkretes Beispiel, welches Produkt von welchem Hersteller bestellbar sein sollte, aber nicht ist.

**Comment by hasslerf** [comment]
Auf `nein` gestellt und benutzt. Fühlt sich irgendwie schmutzig an, weil nicht sehr offensichtlich. Wenn das aber des Rätsels Lösung ist, kann ich damit leben. Ich lasse die Option bei uns auf `nein` damit ich das nächstes mal nicht suchen muss. 
Mein Feature request bleibt aber bestehen.

**Comment by hasslerf** [comment]
An dieser Stelle muss ich alles zurücknehmen und das Gegenteil behaupten: 
- Meine Lieferantin hatte überall das Lagerprodukt-Hackerl ✅ rausgenommen 😊 
Danke @mrothauer für deinen Anruf 📞
